import type { DealCase } from './types';

export const B4_CASES: DealCase[] = [
  {
    code: 'B4-001',
    role: 'Big 4 Advisory',
    difficulty: 'Intermediate',
    title: 'Financial Due Diligence — Buy Side',
    situation: 'Your firm is engaged by a PE fund to conduct buy-side financial due diligence on a target company before a ₹240 Cr acquisition.',
    company_overview: 'MedEquip Distributors Pvt Ltd distributes 14 international medical device brands across 8 Indian states. Top 3 distributors account for 44% of revenue. One key brand (38% of revenue) has a contract expiring in 14 months.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['198', '241', '284'] },
        { label: 'Reported EBITDA (₹ Cr)', values: ['24', '30', '38'] },
        { label: 'EBITDA Margin', values: ['12.1%', '12.4%', '13.4%'] },
        { label: 'One-time Govt Tender Revenue (₹ Cr)', values: ['—', '—', '12'] },
        { label: 'Q4 Revenue Timing Issue (₹ Cr)', values: ['—', '—', '8'] },
        { label: 'Working Capital (₹ Cr)', values: ['48', '62', '74'] },
        { label: 'Debtor Days', values: ['72', '82', '94'] },
        { label: 'Industry Norm Debtor Days', values: ['60', '60', '60'] },
        { label: 'Key Brand Revenue Share', values: ['42%', '40%', '38%'] },
      ],
    },
    market_context: 'Indian medical device distribution growing 18% CAGR driven by hospital expansion and insurance penetration. However, the sector is consolidating — large global OEMs are bringing distribution in-house, reducing reliance on third-party distributors.\n\nGovernment tenders are one-time in nature and do not represent recurring revenue. Timing differences in Q4 revenue recognition are a common area of FDD scrutiny.',
    task: '1. Identify key quality of earnings adjustments.\n\n2. Calculate adjusted EBITDA after removing non-recurring items.\n\n3. Assess normalised working capital.\n\n4. Flag the top 3 due diligence risks requiring further investigation.\n\n5. Present your view: is the reported ₹38 Cr EBITDA sustainable?\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Calculates a bear case combining brand contract non-renewal (38% revenue at risk) with stripping the one-time government tender (₹12 Cr) and Q4 timing issue (₹8 Cr). Shows adjusted sustainable EBITDA could be ₹18-22 Cr — roughly half of reported.',
      critical_gap: 'Accepts reported EBITDA at face value or makes minor adjustments without combining the risks. Fails to connect the expiring brand contract with the revenue sustainability question.',
      non_obvious_signal: 'The expiring brand contract (38% of revenue) plus non-recurring government tender (₹12 Cr) means sustainable EBITDA could be materially lower than reported. The two risks compound when considered together.',
    },
  },
  {
    code: 'B4-002',
    role: 'Big 4 Advisory',
    difficulty: 'Intermediate',
    title: 'Vendor Due Diligence',
    situation: 'Your firm is engaged by the seller (promoter) of a logistics company to prepare a vendor due diligence report for potential buyers.',
    company_overview: 'SwiftMove Logistics Pvt Ltd is a last-mile delivery company serving B2B and B2C e-commerce. 5,200 delivery partners (gig workers). Operational in 34 cities. Top 2 customers (both large e-commerce platforms) = 71% of revenue.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['248', '284', '318'] },
        { label: 'EBITDA (₹ Cr)', values: ['24', '26', '28'] },
        { label: 'EBITDA Margin', values: ['9.7%', '9.2%', '8.8%'] },
        { label: 'Revenue per Delivery (₹)', values: ['54', '50', '47'] },
        { label: 'Cost per Delivery (₹)', values: ['42', '43', '43'] },
        { label: 'Gig Worker Churn (annual)', values: ['28%', '31%', '34%'] },
        { label: 'On-Time Delivery Rate', values: ['95.1%', '94.8%', '94.2%'] },
        { label: 'Customer Concentration (top 2)', values: ['64%', '68%', '71%'] },
        { label: 'Total Deliveries (Cr)', values: ['4.6', '5.7', '6.8'] },
      ],
    },
    market_context: 'Indian last-mile delivery market growing 24% but commoditising rapidly. Revenue per delivery declining as e-commerce platforms push pricing pressure. Gig worker classification is a regulatory overhang — India is expected to introduce formal gig worker protections within 2-3 years.\n\nIf gig workers are reclassified as employees, cost per delivery could increase 30-40% due to ESI, PF, and minimum wage compliance.',
    task: '1. As VDD lead, prepare an honest assessment of margin sustainability.\n\n2. Model 3 scenarios for next 3 years: base, downside (gig worker reclassification), upside (automation investment).\n\n3. Recommend how the seller should present this business to maximise transaction value while maintaining factual accuracy.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies the ethical tension in VDD — prepared for the seller but read by buyers. Recommends transparent disclosure of gig worker regulatory risk rather than minimising it. Calculates the P&L impact of reclassification.',
      critical_gap: 'Presents only the bull case to maximise seller value. Downplays the gig worker risk. Fails to recognise that VDD creates legal liability for the firm if it misleads buyers.',
      non_obvious_signal: 'VDD is prepared for the seller but read by buyers. Any information asymmetry that misleads buyers creates legal liability for the advisory firm. The ethical dimension is as important as the financial analysis.',
    },
  },
  {
    code: 'B4-003',
    role: 'Big 4 Advisory',
    difficulty: 'Intermediate',
    title: 'Working Capital Optimisation',
    situation: 'A manufacturing client has engaged your firm to identify and unlock ₹50 Cr of trapped working capital within 6 months.',
    company_overview: 'Durga Chemicals Ltd is a specialty chemicals manufacturer supplying pharma, agro, and textile companies. Revenue FY24: ₹520 Cr. EBITDA: ₹78 Cr. Current working capital: ₹168 Cr (32.3% of revenue vs industry benchmark 18-22%).',
    financials: {
      headers: ['', 'Current', 'Industry Benchmark', 'Gap'],
      rows: [
        { label: 'Raw Material Inventory (₹ Cr / Days)', values: ['42 / 29', '— / 28', 'Minimal'] },
        { label: 'WIP Inventory (₹ Cr / Days)', values: ['18 / 12', '— / 10', 'Minimal'] },
        { label: 'Finished Goods Inventory (₹ Cr / Days)', values: ['64 / 45', '— / 22', '₹33 Cr excess'] },
        { label: 'Slow-Moving FG (₹ Cr)', values: ['22', '—', 'Write-off risk'] },
        { label: 'Accounts Receivable (₹ Cr / Days)', values: ['88 / 62', '— / 45', '₹24 Cr excess'] },
        { label: 'Accounts Payable (₹ Cr / Days)', values: ['44 / 31', '— / 45', '₹20 Cr undertapped'] },
        { label: 'Total Working Capital (₹ Cr)', values: ['168', '~104', '₹64 Cr gap'] },
        { label: 'WC as % of Revenue', values: ['32.3%', '18-22%', '10-14% excess'] },
      ],
    },
    market_context: 'Specialty chemicals is a relationship-driven industry. Top 3 customers (48% of revenue) receive 90-day credit terms contractually — changing these terms risks customer attrition. Suppliers are open to longer payment terms if volume commitments are provided.\n\nSlow-moving inventory (₹22 Cr) resulted from a product line launched in FY23 that underperformed expectations. This inventory cannot be sold through normal channels.',
    task: '1. Calculate the working capital gap versus industry benchmark.\n\n2. Identify specific initiatives to release ₹50 Cr within 6 months.\n\n3. Quantify the impact of each initiative.\n\n4. Flag the risks of aggressive working capital extraction on customer and supplier relationships.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Separates structural improvements (AR reduction, AP extension) from one-time actions (₹22 Cr inventory liquidation at markdown). Sequences recommendations — structural fixes first for sustainable improvement, inventory liquidation as a one-time release with P&L impact disclosure.',
      critical_gap: 'Proposes "reduce AR by 17 days" without acknowledging the top-3-customer contractual constraint. Treats all working capital levers as equally actionable.',
      non_obvious_signal: 'The ₹22 Cr slow-moving FG inventory cannot be unlocked through process improvement — it requires markdown/write-off or alternate buyers. Separate structural improvements from one-time actions in the recommendation.',
    },
  },
  {
    code: 'B4-004',
    role: 'Big 4 Advisory',
    difficulty: 'Advanced',
    title: 'Business Valuation — Dispute',
    situation: 'Your firm has been engaged as an independent expert in a shareholder dispute. Two promoter-directors hold equal stakes and are splitting. You must value the company for the buyout.',
    company_overview: 'Aditya Precision Engineering Pvt Ltd manufactures precision components for aerospace and defence. Chennai-based. Founded 2008. Order book (firm): ₹340 Cr including a non-transferable DRDO contract of ₹140 Cr.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['72', '84', '94'] },
        { label: 'EBITDA (₹ Cr)', values: ['16', '18', '21'] },
        { label: 'PAT (₹ Cr)', values: ['10', '12', '14'] },
        { label: 'Net Worth (₹ Cr)', values: ['62', '74', '86'] },
        { label: 'Order Book — DRDO (₹ Cr)', values: ['—', '—', '140 (non-transferable)'] },
        { label: 'Order Book — HAL (₹ Cr)', values: ['—', '—', '92 (transferable w/ approval)'] },
        { label: 'Order Book — Private OEMs (₹ Cr)', values: ['—', '—', '108'] },
        { label: 'Total Order Book (₹ Cr)', values: ['—', '—', '340 (3.6x revenue)'] },
      ],
    },
    market_context: 'Indian aerospace and defence manufacturing growing 22% CAGR driven by Make in India and defence offset requirements. Small-scale precision manufacturers are rare — barriers to entry are high (certifications, security clearances).\n\nDRDO contracts are personal to the company but require government approval for change of control. In shareholder disputes, the standard of value is typically "fair market value" — assuming a hypothetical willing buyer and willing seller.',
    task: '1. Build a fair market valuation using three methodologies: DCF, comparable company multiples, and asset-based.\n\n2. Specifically address the DRDO contract treatment in each methodology.\n\n3. Reconcile the three values into a final range.\n\n4. Recommend a valuation for the expert report.\n\nState all assumptions and define the standard of value you are applying.',
    admin_only: {
      strong_response: 'Defines the standard of value (fair market value) before beginning calculations. Values the DRDO contract at probability-weighted transfer value, not face value. Recognises that "fair market value" assumes a hypothetical buyer who would discount non-transferable contracts.',
      critical_gap: 'Includes the DRDO contract at face value in the DCF without adjusting for transferability risk. Fails to define the standard of value, making the valuation framework unclear.',
      non_obvious_signal: 'The standard of value must be defined first — "fair market value" means the DRDO contract is valued at its probability-weighted transfer value, not face value. This is a legal and valuation methodology question, not just a financial exercise.',
    },
  },
  {
    code: 'B4-005',
    role: 'Big 4 Advisory',
    difficulty: 'Advanced',
    title: 'IPO Readiness Assessment',
    situation: 'A consumer goods company plans to file its DRHP within 9 months and has engaged your firm to identify gaps in IPO readiness.',
    company_overview: 'Himalaya Wellness Products Ltd is an Ayurvedic personal care and wellness company. Revenue FY24: ₹890 Cr. EBITDA: ₹134 Cr (15% margin). 3-year revenue CAGR: 24%. CFO role vacant for 7 months.',
    financials: {
      headers: ['', 'Current State', 'SEBI Requirement', 'Gap'],
      rows: [
        { label: 'Accounting Standard', values: ['Indian GAAP', 'Ind AS', 'Transition required'] },
        { label: 'Related Party Txns (₹ Cr)', values: ['42', 'Arm\'s length docs required', 'High risk'] },
        { label: 'Pending Tax Dispute (₹ Cr)', values: ['11', 'Disclosure required', 'Medium risk'] },
        { label: 'CFO Role', values: ['Vacant 7 months', 'Must be filled', 'Critical gap'] },
        { label: 'Independent Directors', values: ['3 of 8 (37.5%)', '50% minimum', 'Need 1-2 more'] },
        { label: 'Revenue (₹ Cr)', values: ['890', '—', '—'] },
        { label: 'PAT (₹ Cr)', values: ['89', '—', '—'] },
        { label: 'Subsidiary Revenue (₹ Cr)', values: ['18', '—', 'Tax dispute linked'] },
      ],
    },
    market_context: 'SEBI IPO regulations require Ind AS financials, minimum 50% independent directors, related party transaction disclosure, and a qualified management team. DRHP review typically takes 3-4 months after filing.\n\nRelated party transactions are the most scrutinised area in SEBI IPO reviews. ₹42 Cr of RPTs with promoter entities will require either rationalisation or shareholder approval with arm\'s length documentation.',
    task: '1. Identify all IPO readiness gaps across financial, governance, and legal dimensions.\n\n2. Prioritise by severity and time to remediate.\n\n3. Build a 9-month remediation roadmap.\n\n4. Identify the 2 issues that could delay or derail the IPO if not resolved.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Prioritises RPT rationalisation above Ind AS transition because RPTs are the highest regulatory risk — SEBI can reject or delay the DRHP based on RPT concerns. Also flags CFO vacancy as a deal-breaker for institutional investor confidence.',
      critical_gap: 'Lists all gaps without prioritising by severity. Treats Ind AS transition as the most important issue without recognising that RPTs and governance gaps are more likely to derail the IPO.',
      non_obvious_signal: 'Related party transactions (₹42 Cr) are the most dangerous issue — SEBI scrutinises RPTs intensely. If these are promoter-entity transactions, they need arm\'s length documentation before filing. This is higher priority than Ind AS transition.',
    },
  },
  {
    code: 'B4-006',
    role: 'Big 4 Advisory',
    difficulty: 'Advanced',
    title: 'Restructuring Advisory',
    situation: 'A retail chain is facing imminent insolvency. Your firm must advise on a pre-packaged IBC restructuring before lenders initiate formal proceedings.',
    company_overview: 'Trendline Fashion Pvt Ltd is a 350-store fast fashion retail chain. Founded 2012. Revenue peak ₹1,100 Cr (FY22). 180 stores are profitable, 170 are loss-making. Online channel: ₹92 Cr (+34% YoY). Cash available: ₹8 Cr (11 days runway).',
    financials: {
      headers: ['', 'FY22 (Peak)', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['1,100', '820', '640'] },
        { label: 'EBITDA (₹ Cr)', values: ['88', '12', '-38'] },
        { label: 'Total Debt (₹ Cr)', values: ['280', '380', '480'] },
        { label: 'Trade Creditors Overdue 90+ days (₹ Cr)', values: ['—', '80', '180'] },
        { label: 'Employees', values: ['4,800', '4,500', '4,200'] },
        { label: 'Profitable Stores', values: ['280', '220', '180'] },
        { label: 'Loss-Making Stores', values: ['70', '130', '170'] },
        { label: 'Online Revenue (₹ Cr)', values: ['42', '68', '92'] },
        { label: 'Cash Available (₹ Cr)', values: ['48', '22', '8'] },
      ],
    },
    market_context: 'Indian fast fashion retail facing structural shift to online. Physical retail requires high footfall to cover rental costs. Store-level EBITDA breakeven typically requires ₹1.8 Cr annual revenue per store.\n\nPre-packaged IBC allows companies to negotiate restructuring terms before entering formal insolvency. Anchor lender (48% of debt) has indicated willingness to convert ₹120 Cr to equity if other lenders follow. Promoter has personal guarantees on store leases.',
    task: '1. Design a restructuring plan that keeps the viable 180 stores operating.\n\n2. Calculate minimum debt reduction required for viability.\n\n3. Model 3 scenarios: liquidation, restructuring with lender support, restructuring with strategic investor.\n\n4. Recommend the path maximising recovery for all stakeholders.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies the promoter personal guarantee on store leases as an alignment problem — the promoter will resist closing stores because each closure crystallises a personal liability. Recommends addressing lease guarantees as part of the restructuring deal.',
      critical_gap: 'Proposes closing 170 loss-making stores without considering the promoter\'s personal guarantee liability. Ignores the incentive misalignment between promoter and lenders.',
      non_obvious_signal: 'Promoter personal guarantees on store leases create an incentive misalignment — the promoter will resist any restructuring that closes stores because each closure triggers a personal liability. The restructuring plan must address this to get promoter cooperation.',
    },
  },
  {
    code: 'B4-007',
    role: 'Big 4 Advisory',
    difficulty: 'Advanced',
    title: 'Forensic Accounting Review',
    situation: 'A listed company\'s audit committee has engaged your firm to investigate irregularities flagged by a whistleblower. The board needs preliminary findings within 14 days.',
    company_overview: 'Suraksha Infrastructure Ltd (listed on BSE). Revenue FY24: ₹1,240 Cr. Three whistleblower allegations: (1) Revenue recognition irregularity on 3 projects (₹180 Cr), (2) Related party subcontracting at 28% above market rates (₹42 Cr), (3) ₹18 Cr advances to a 2-employee supplier.',
    financials: {
      headers: ['', 'Allegation', 'Amount (₹ Cr)', 'Revenue %'],
      rows: [
        { label: 'Revenue Recognition Issue', values: ['3 projects: 34% physical progress, 70% revenue recognised', '180', '14.5%'] },
        { label: 'Related Party Overpricing', values: ['Promoter entity subcontract at 28% above market', '42', '3.4%'] },
        { label: 'Suspicious Supplier Advance', values: ['2-employee supplier, unclear business justification', '18', '1.5%'] },
        { label: 'Total Revenue (₹ Cr)', values: ['—', '1,240', '100%'] },
        { label: 'Materiality Threshold (5%)', values: ['—', '62', '—'] },
      ],
    },
    market_context: 'SEBI regulations require prompt disclosure of material information to the stock exchange. If the revenue recognition issue (₹180 Cr = 14.5% of revenue) is confirmed as material, the company may have a disclosure obligation before the investigation concludes.\n\nPercentage of completion (POC) revenue recognition is the most common area of accounting fraud in construction companies. The gap between physical progress (34%) and revenue recognised (70%) is a significant red flag.',
    task: '1. Design a preliminary investigation framework.\n\n2. Identify the 5 data sources and documents to examine first.\n\n3. Determine which allegation is most likely to constitute a material misstatement.\n\n4. Recommend whether the board should make an immediate stock exchange disclosure while investigation is ongoing.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Addresses the stock exchange disclosure question first — SEBI requires prompt disclosure of material information. The ₹180 Cr revenue issue exceeds the 5% materiality threshold (₹62 Cr). Recommends the board disclose the investigation before completing it.',
      critical_gap: 'Focuses on investigation methodology without addressing the disclosure timing question. Treats all three allegations as equally important without calculating materiality.',
      non_obvious_signal: 'The stock exchange disclosure decision is the most urgent question. If the revenue recognition issue (14.5% of revenue) is potentially material, SEBI may require disclosure before the investigation concludes. Address timing before methodology.',
    },
  },

  /* ═══════════════════════════════════════════════
     EXPERT CASES — B4-008 through B4-015
     ═══════════════════════════════════════════════ */

  {
    code: 'B4-008',
    role: 'Big 4 Advisory',
    difficulty: 'Expert',
    title: 'Fraud Investigation — Related Party Round-Tripping at Vanguard Infra',
    situation: 'Your forensic practice has been engaged by the audit committee of Vanguard Infrastructure Ltd (listed BSE/NSE) to investigate a whistleblower complaint alleging revenue round-tripping through related party entities. The statutory auditors have issued a qualified opinion pending investigation. You have 45 minutes to design the investigation framework.',
    company_overview: 'Vanguard Infrastructure Ltd — Listed EPC contractor. Revenue FY24: ₹3,200 Cr. PAT: ₹192 Cr. The whistleblower alleges that 3 promoter-linked subcontractors were used to inflate project revenues. The scheme: Vanguard awards subcontracts to promoter entities at above-market rates, the subcontractors then award sub-sub-contracts to the actual workers at market rates, and the difference (₹84 Cr over 3 years) flows back to the promoter through a complex chain involving 4 layered entities incorporated in Dubai and Mauritius.',
    financials: {
      headers: ['', 'Alleged Round-Trip', 'Legitimate Business', 'Investigation Challenge'],
      rows: [
        { label: 'Total Subcontract Value (₹ Cr)', values: ['₹340', '₹256', 'Difference: ₹84 Cr'] },
        { label: 'Subcontractor A (Promoter Wife)', values: ['₹148', 'Market rate: ₹112', '₹36 Cr excess'] },
        { label: 'Subcontractor B (Promoter Brother)', values: ['₹108', 'Market rate: ₹82', '₹26 Cr excess'] },
        { label: 'Subcontractor C (Trust)', values: ['₹84', 'Market rate: ₹62', '₹22 Cr excess'] },
        { label: 'Offshore Entity Layer', values: ['Dubai SPV → Mauritius → India', '—', 'Fund flow tracing'] },
        { label: 'Materiality (5% of Revenue)', values: ['₹160 Cr', '—', '₹84 Cr is below'] },
        { label: 'Materiality (5% of PAT)', values: ['₹9.6 Cr', '—', '₹84 Cr is ABOVE'] },
      ],
    },
    market_context: 'Related party round-tripping is the most common fraud in Indian construction/EPC companies. The typical pattern: overpriced subcontracts → promoter entities → offshore layering → funds return to promoter. Key evidence: bank statements showing circular fund flows, beneficial ownership of offshore entities, and comparison of subcontract rates to market benchmarks.\n\nThe ₹84 Cr is below the 5% of revenue materiality threshold (₹160 Cr) but significantly above 5% of PAT (₹9.6 Cr). The materiality determination — revenue base or PAT base — will determine whether the statutory auditors must qualify or disclaim their opinion.',
    task: '1. Design the forensic investigation framework: prioritise the three investigative workstreams in order of evidence value. What documents and data sources do you examine first?\n\n2. The ₹84 Cr alleged round-trip is below 5% of revenue (₹160 Cr) but above 5% of PAT (₹9.6 Cr). Should the materiality assessment use revenue or PAT as the base? Why does this determination matter for the statutory audit opinion?\n\n3. The offshore entity chain (Dubai → Mauritius → India) creates jurisdictional complexity. What powers does the Indian forensic investigator have to access offshore banking records? What alternative evidence can you obtain domestically?\n\n4. Draft the preliminary findings section of your report. Address: (a) whether round-tripping has occurred (b) the quantum of financial impact (c) whether the statutory auditors should qualify or disclaim their opinion (d) whether SEBI disclosure is required.',
    admin_only: {
      strong_response: 'Identifies the materiality determination as the critical decision: ₹84 Cr is 43.8% of PAT but only 2.6% of revenue. In a fraud context, PAT-based materiality is the correct standard because the alleged round-tripping directly inflates profits. This means the impact IS material and triggers both audit qualification and SEBI disclosure. Recommends bank statement analysis as the first investigative step because it provides direct evidence of circular fund flows.',
      critical_gap: 'Uses revenue-based materiality (₹160 Cr threshold) and concludes the ₹84 Cr is not material. This is incorrect for a fraud investigation — PAT-based materiality is the appropriate measure when the alleged fraud directly inflates profits. Focuses on market rate comparison without tracing actual fund flows.',
      non_obvious_signal: 'The materiality determination — revenue vs PAT base — is the pivotal decision. Using revenue: ₹84 Cr is immaterial (2.6%). Using PAT: ₹84 Cr is 43.8% of profits — massively material. In a fraud investigation where the scheme inflates reported profits, the PAT base is the correct standard.',
    },
  },
  {
    code: 'B4-009',
    role: 'Big 4 Advisory',
    difficulty: 'Expert',
    title: 'Ind AS 116 Lease Impact — How a New Accounting Standard Triggers Covenant Breach',
    situation: 'Your advisory team has been engaged by Oasis Retail Ltd to assess the financial reporting impact of adopting Ind AS 116 (Leases). The company has 320 store leases. The CFO suspects the transition will breach the company\'s debt covenant. You have 45 minutes to confirm or deny this and recommend a course of action.',
    company_overview: 'Oasis Retail Ltd — Fashion retail chain. 320 stores (all leased). Revenue FY24: ₹1,840 Cr. EBITDA (pre-Ind AS 116): ₹184 Cr (10% margin). Net debt (pre-transition): ₹460 Cr. Debt covenant: Net Debt/EBITDA must stay below 3.0x. Current ratio: 460/184 = 2.5x (compliant). Store leases: Average annual rent ₹42 Cr across all stores. Average remaining lease term: 6.2 years. Weighted average incremental borrowing rate: 9.5%.',
    financials: {
      headers: ['', 'Pre-Ind AS 116', 'Post-Ind AS 116', 'Change'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['1,840', '1,840', 'No change'] },
        { label: 'EBITDA (₹ Cr)', values: ['184', '226 (+₹42)', '+₹42 Cr (rent reclassified)'] },
        { label: 'Depreciation (ROU Assets)', values: ['—', '₹38 Cr', 'New charge'] },
        { label: 'Interest on Lease Liability', values: ['—', '₹22 Cr', 'New charge'] },
        { label: 'PAT Impact', values: ['—', '-₹18 Cr', 'Negative (front-loaded interest)'] },
        { label: 'Right-of-Use Asset', values: ['—', '₹232 Cr', 'New asset'] },
        { label: 'Lease Liability', values: ['—', '₹248 Cr', 'New liability'] },
        { label: 'Net Debt (including lease liability)', values: ['460', '708', '+₹248 Cr'] },
        { label: 'Net Debt/EBITDA', values: ['2.5x', '3.1x', 'COVENANT BREACH'] },
      ],
    },
    market_context: 'Ind AS 116 replaces operating leases with right-of-use assets and lease liabilities on the balance sheet. For lease-heavy businesses (retail, airlines, hospitality), this can dramatically increase reported debt and change financial ratios. The covenant definition of "debt" is critical: if the loan agreement defines debt as "all financial liabilities per Ind AS," the lease liability automatically counts.\n\nMost loan agreements signed before Ind AS 116 adoption do not explicitly exclude lease liabilities from the debt definition. This creates a situation where an accounting standard change — with zero economic impact — triggers a covenant breach.',
    task: '1. Calculate the full Ind AS 116 transition impact: right-of-use asset, lease liability, EBITDA adjustment, depreciation, interest expense, and PAT impact. Show all calculations using the data provided.\n\n2. Calculate the post-transition Net Debt/EBITDA ratio. Does the covenant breach? If the covenant uses the post-Ind AS 116 EBITDA in the denominator, does that change the result?\n\n3. The lender can either waive the covenant or demand a cure. What is your recommended approach to the lender? Should the company request a covenant redefinition or a waiver? What arguments can you make?\n\n4. Beyond the covenant issue, how does Ind AS 116 affect the company\'s acquisition attractiveness? If a PE fund is evaluating Oasis Retail for a buyout, how should they think about the lease liability in their LBO model?',
    admin_only: {
      strong_response: 'Identifies the critical nuance: Ind AS 116 increases EBITDA by ₹42 Cr (rent no longer an operating expense) while adding ₹248 Cr to debt. The ratio deteriorates because the debt increase (₹248 Cr) is proportionally larger than the EBITDA increase (₹42 Cr). Recommends a covenant redefinition (not just a waiver) because this is a permanent change — a one-time waiver will need to be renewed annually.',
      critical_gap: 'Calculates the lease liability correctly but misses the EBITDA adjustment (rent removal). This leads to an even worse ratio calculation. Alternatively, focuses only on EBITDA improvement without recognising the debt increase. Recommends a simple waiver without recognising this is a permanent structural change requiring a covenant redefinition.',
      non_obvious_signal: 'Ind AS 116 creates an accounting change with zero economic impact but real covenant consequences. The key insight is that EBITDA improves by ₹42 Cr while debt increases by ₹248 Cr — the ratio deteriorates because the scale difference is 6:1 (₹248 Cr vs ₹42 Cr). A waiver is insufficient — the company needs a permanent covenant redefinition.',
    },
  },
  {
    code: 'B4-010',
    role: 'Big 4 Advisory',
    difficulty: 'Expert',
    title: 'Transfer Pricing Dispute — MNC\'s India Subsidiary vs Tax Authority',
    situation: 'Your transfer pricing team has been engaged by Apex Technologies India (a subsidiary of Apex Technologies Inc, USA) to defend against a ₹380 Cr transfer pricing adjustment proposed by the Indian tax authority. The dispute centres on the subsidiary\'s characterisation as a "limited risk distributor" vs the tax authority\'s assertion that it is a "full-fledged distributor."',
    company_overview: 'Apex Technologies India Pvt Ltd — Indian subsidiary of Apex Technologies Inc (NASDAQ listed). Revenue FY24: ₹2,800 Cr. Reported operating margin: 3.2% (₹89.6 Cr). Indian tax authority\'s position: The subsidiary performs significant marketing, customer acquisition, and brand-building functions that create intangible value in India. It should be compensated at 8-10% operating margin, not 3.2%.',
    financials: {
      headers: ['', 'Company Position', 'Tax Authority Position', 'Dispute Range'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['2,800', '2,800', 'Agreed'] },
        { label: 'Reported Operating Margin', values: ['3.2% (₹89.6 Cr)', '8-10% (₹224-280 Cr)', '₹134-190 Cr gap'] },
        { label: 'Entity Characterisation', values: ['Limited Risk Distributor', 'Full-Fledged Distributor', 'Key dispute'] },
        { label: 'Marketing Spend (₹ Cr)', values: ['₹340 Cr', '₹340 Cr', 'Agreed amount'] },
        { label: 'Marketing as % of Revenue', values: ['12.1%', '12.1%', 'Abnormally high for LRD'] },
        { label: 'AMP Expense Benchmark', values: ['—', '—', '3-5% for LRD'] },
        { label: 'TP Adjustment Proposed', values: ['—', '₹380 Cr', '30% tax rate = ₹114 Cr'] },
        { label: 'Penalty (if upheld)', values: ['—', '100-300% of adjustment', '₹114-342 Cr'] },
      ],
    },
    market_context: 'Transfer pricing disputes between MNC subsidiaries and Indian tax authorities have intensified. The "marketing intangible" argument is India\'s version of the global DEMPE (Development, Enhancement, Maintenance, Protection, Exploitation) framework under OECD guidelines.\n\nThe key evidence: Apex India spends 12.1% of revenue on marketing — far above the 3-5% benchmark for a limited risk distributor. This AMP (Advertising, Marketing, and Promotion) expenditure suggests the Indian entity is creating marketing intangibles for the parent, which should be compensated through a higher transfer price or a separate AMP reimbursement.',
    task: '1. Evaluate both positions: Is Apex India a limited risk distributor or a full-fledged distributor? What specific functions, assets, and risks (FAR analysis) determine the characterisation? Support your conclusion with specific evidence from the case.\n\n2. The marketing spend of 12.1% vs the 3-5% LRD benchmark is the tax authority\'s strongest evidence. How would you defend the company\'s position that this does not create Indian marketing intangibles?\n\n3. Calculate the tax exposure under three scenarios: (a) full adjustment upheld (₹380 Cr) (b) partial adjustment (margin increase to 6%) (c) company prevails entirely. Include penalties.\n\n4. Recommend a resolution strategy: Litigation? Advance Pricing Agreement? Mutual Agreement Procedure? What is the optimal path considering time, cost, and probability of success?',
    admin_only: {
      strong_response: 'Identifies that the AMP expenditure of 12.1% vs 3-5% LRD benchmark is strong evidence FOR the tax authority. Rather than defending the LRD characterisation (which is likely to fail), recommends accepting a middle-ground characterisation but negotiating the arm\'s length margin. Proposes an APA for prospective years to prevent future disputes.',
      critical_gap: 'Defends the LRD characterisation aggressively despite the 12.1% AMP spend being clearly inconsistent with limited risk. Focuses on comparable company analysis without addressing the AMP issue directly. Recommends litigation without calculating the NPV of a settlement vs. litigation cost.',
      non_obvious_signal: 'The AMP spend of 12.1% vs 3-5% benchmark makes the LRD characterisation indefensible. The strategic move is NOT to fight the characterisation but to accept a middle ground (limited-risk with marketing support services) and negotiate the arm\'s length margin downward from the tax authority\'s 8-10% demand. Fighting a losing characterisation wastes resources and increases penalty risk.',
    },
  },
  {
    code: 'B4-011',
    role: 'Big 4 Advisory',
    difficulty: 'Expert',
    title: 'Pre-Pack IBC Advisory — Advising Lenders on Creditor Priority in Apex Textiles',
    situation: 'Your firm is advising the lead lender consortium (₹1,200 Cr exposure across 6 banks) on a pre-packaged insolvency resolution for Apex Textiles. The company has submitted a base resolution plan. Three classes of creditors have competing claims. You have 45 minutes.',
    company_overview: 'Apex Textiles Ltd — Vertically integrated textile manufacturer. Revenue FY24: ₹680 Cr (down from ₹920 Cr peak). EBITDA: -₹48 Cr (loss-making). Total admitted claims: ₹1,680 Cr. Asset liquidation value: ₹520 Cr. Going-concern value (independent valuation): ₹840 Cr.',
    financials: {
      headers: ['', 'Secured Lenders', 'Unsecured Creditors', 'Operational Creditors'],
      rows: [
        { label: 'Total Claims', values: ['₹1,200 Cr', '₹180 Cr', '₹300 Cr'] },
        { label: 'Security Coverage', values: ['₹480 Cr (plant/land)', 'None', 'None'] },
        { label: 'IBC Waterfall Priority', values: ['1st (CIRP costs)', '3rd', '2nd (operational)'] },
        { label: 'Liquidation Recovery', values: ['40% (₹480 Cr)', '0%', '~₹40 Cr (₹520-480)'] },
        { label: 'Resolution Recovery', values: ['?', '?', '?'] },
        { label: 'Proposed Resolution Value', values: ['₹840 Cr', '—', '—'] },
        { label: 'Going Concern Premium', values: ['₹320 Cr vs liquidation', '—', '—'] },
        { label: 'Employee Claims (priority)', values: ['₹24 Cr (24 months)', '—', '—'] },
      ],
    },
    market_context: 'Under IBC Section 53, the waterfall is: (1) CIRP costs and workmen dues (2) Secured creditors and employee dues (3) Unsecured financial creditors (4) Government dues and operational creditors (5) Remaining debts. However, the Supreme Court has ruled that CoC can deviate from strict waterfall in resolution plans if the plan is fair and equitable.\n\nThe going-concern value of ₹840 Cr exceeds liquidation value of ₹520 Cr by ₹320 Cr. The key question: how should this ₹320 Cr "resolution premium" be distributed? The secured lenders argue they should receive the entire premium. Operational creditors argue they are entitled to at least liquidation value.',
    task: '1. Calculate recovery rates for each creditor class under liquidation. Then calculate the minimum each class must receive under the resolution plan to meet the "not less than liquidation value" test under IBC Section 30(2)(b).\n\n2. The resolution plan offers ₹840 Cr total. Distribute this across the three creditor classes. Show at least two allocation models: (a) strict waterfall (b) equitable distribution. Identify which model the CoC would likely approve and why.\n\n3. Employee claims of ₹24 Cr have super-priority under IBC. How do these interact with the waterfall? If CIRP costs are ₹18 Cr, show the cascading impact on other creditor recoveries.\n\n4. The promoter has submitted a rival resolution plan offering ₹780 Cr but with a 3-year deferred payment structure. Calculate the NPV at 12% discount rate and compare to the ₹840 Cr upfront plan. Recommend which plan the CoC should approve.',
    admin_only: {
      strong_response: 'Correctly applies the IBC Section 30(2)(b) "liquidation value floor" test FIRST, then distributes the resolution premium. Calculates that operational creditors must receive at least ₹40 Cr (their liquidation recovery) before secured lenders can claim the premium. Shows that the ₹320 Cr premium distribution is the real negotiation — not the total amount.',
      critical_gap: 'Distributes the ₹840 Cr using only the waterfall without applying the liquidation value floor test. This results in operational creditors receiving zero when they are entitled to their liquidation value. Alternatively, gives operational creditors their full ₹300 Cr claim before secured lenders are made whole, which is also incorrect.',
      non_obvious_signal: 'IBC Section 30(2)(b) creates a floor: each creditor class must receive at least their liquidation recovery in any resolution plan. The ₹320 Cr premium above liquidation is the negotiable portion. The waterfall applies to the premium, not the entire ₹840 Cr. This distinction is what separates good IBC advisory from standard restructuring.',
    },
  },
  {
    code: 'B4-012',
    role: 'Big 4 Advisory',
    difficulty: 'Expert',
    title: 'IT Systems Due Diligence — Carve-Out of Pinnacle Corp\'s Healthcare Division',
    situation: 'Your technology advisory practice has been engaged to assess IT separation complexity for the carve-out of Pinnacle Corporation\'s healthcare division into a standalone entity. The buyer (a PE fund) wants to understand the true cost of IT separation before closing.',
    company_overview: 'Pinnacle Corporation — ₹12,000 Cr diversified conglomerate. Healthcare Division: ₹2,800 Cr revenue, 2,400 employees. Current IT infrastructure: Single SAP S/4HANA instance across all divisions. One Active Directory domain. Shared data centres. Healthcare Division uses 340 of 2,100 total SAP modules/transactions. 38 custom integrations with division-specific clinical systems.',
    financials: {
      headers: ['', 'Seller Estimate', 'Buyer Estimate', 'Your Assessment'],
      rows: [
        { label: 'IT Separation Cost', values: ['₹28 Cr', '₹85 Cr', '?'] },
        { label: 'TSA Duration Needed', values: ['6 months', '18 months', '?'] },
        { label: 'SAP License Cost (Standalone)', values: ['₹4.2 Cr/yr', '₹8.5 Cr/yr', '?'] },
        { label: 'Data Migration Risk', values: ['Low', 'High', '?'] },
        { label: 'Custom Integration Rebuild', values: ['12 integrations', '38 integrations', '?'] },
        { label: 'Shared Master Data Cleanup', values: ['Minimal', 'Significant', '?'] },
        { label: 'Cybersecurity Separation', values: ['Not included', '₹12 Cr', '?'] },
        { label: 'Business Disruption Risk', values: ['Negligible', 'Medium-High', '?'] },
      ],
    },
    market_context: 'IT separation is consistently the most underestimated cost in carve-outs. Industry benchmarks: IT separation typically costs 2-5% of the carve-out entity\'s revenue for shared ERP environments. For Pinnacle Healthcare (₹2,800 Cr revenue), this implies ₹56-140 Cr — substantially higher than the seller\'s ₹28 Cr estimate.\n\nThe single SAP instance is the primary complexity driver. Separating a division from a shared SAP system requires either: (a) cloning the instance and removing non-healthcare data (6-12 months, ₹40-60 Cr) or (b) implementing a new SAP instance with data migration (12-18 months, ₹80-120 Cr). Neither option is the seller\'s estimated ₹28 Cr.',
    task: '1. Build an independent IT separation cost estimate. Use the industry benchmark (2-5% of revenue) as a sanity check against your bottom-up estimate.\n\n2. The seller estimates ₹28 Cr and the buyer estimates ₹85 Cr. Identify the specific assumptions that explain this ₹57 Cr gap. Who is closer to reality?\n\n3. Design a TSA (Transitional Services Agreement) structure: what services should the parent provide, at what cost, for how long? Include step-down provisions and exit penalties. What happens if the TSA runs over?\n\n4. The PE fund is modelling the carve-out acquisition at 10x EBITDA. If IT separation costs ₹85-120 Cr (your estimate), how does this change the effective acquisition multiple? Should the buyer negotiate a purchase price reduction?',
    admin_only: {
      strong_response: 'Identifies that the seller\'s ₹28 Cr estimate excludes SAP re-licensing, cybersecurity separation, custom integration rebuild, and master data cleanup. The bottom-up estimate should be ₹85-120 Cr. Recommends the buyer negotiate a purchase price reduction or an escrow for IT separation costs. Calculates the effective multiple impact: ₹85-120 Cr adds 0.3-0.4x to the effective EV/EBITDA.',
      critical_gap: 'Accepts either the seller or buyer estimate without independent assessment. Treats IT separation as a one-time cost without modelling the ongoing SAP license differential (standalone licensing costs significantly more per user than a shared enterprise license). Ignores the TSA dependency risk.',
      non_obvious_signal: 'The seller\'s ₹28 Cr estimate is almost certainly too low — it excludes SAP re-licensing, cybersecurity, and custom integration costs. But the real insight is the ongoing cost differential: SAP licensing as a standalone entity costs ₹8.5 Cr/yr vs ₹4.2 Cr/yr allocated under the parent. This ₹4.3 Cr/yr recurring cost increase permanently reduces EBITDA and should be modelled into the acquisition price.',
    },
  },
  {
    code: 'B4-013',
    role: 'Big 4 Advisory',
    difficulty: 'Expert',
    title: 'ESG Audit and Greenwashing Detection — Is Verdant Energy\'s Net-Zero Claim Credible?',
    situation: 'Your sustainability advisory practice has been engaged by an institutional investor to independently verify Verdant Energy Ltd\'s net-zero claim before a ₹400 Cr investment. The company claims to be "carbon neutral since FY23." You have 45 minutes to assess the credibility of this claim.',
    company_overview: 'Verdant Energy Ltd — Solar panel manufacturer and developer. Revenue FY24: ₹1,200 Cr. Claims: "Carbon neutral since FY23. Net-zero by FY27." Scope 1 emissions: 4,200 tCO2e (manufacturing). Scope 2 emissions: 18,400 tCO2e (grid electricity). Scope 3 emissions: Not reported. Carbon offset credits purchased: 24,000 tCO2e (from a forestry project in Indonesia). Total offsets exceed Scope 1 + Scope 2 = "carbon neutral."',
    financials: {
      headers: ['', 'Reported', 'Benchmark', 'Red Flags'],
      rows: [
        { label: 'Scope 1 (Direct)', values: ['4,200 tCO2e', 'Reasonable for mfg', 'None'] },
        { label: 'Scope 2 (Electricity)', values: ['18,400 tCO2e', 'High — grid-dependent', 'No renewable transition'] },
        { label: 'Scope 3 (Supply Chain)', values: ['Not reported', 'Typically 60-80% of total', 'MAJOR omission'] },
        { label: 'Total Reported', values: ['22,600 tCO2e', '—', '—'] },
        { label: 'Offsets Purchased', values: ['24,000 tCO2e', '—', 'Exceeds reported emissions'] },
        { label: 'Offset Source', values: ['Indonesian forestry', '—', 'Verification pending'] },
        { label: 'Offset Cost', values: ['₹1.8 Cr ($4/tCO2e)', 'Market: $8-15/tCO2e', 'Below market rate'] },
        { label: 'Estimated Scope 3', values: ['~55,000-75,000 tCO2e', '—', 'If included: NOT neutral'] },
      ],
    },
    market_context: 'Carbon neutrality claims under scrutiny globally. The Science-Based Targets initiative (SBTi) no longer allows carbon offsets to count toward net-zero targets. EU CSRD and proposed Indian BRSR Core requirements will mandate Scope 3 reporting starting FY26.\n\nForestry-based carbon offsets from Southeast Asia have a high reversal risk (deforestation, fire). Credits at $4/tCO2e vs market average of $8-15 suggest potentially low-quality or unverified credits. Verra (the major registry) has flagged several Indonesian forestry projects for over-crediting.',
    task: '1. Assess the credibility of Verdant\'s "carbon neutral since FY23" claim. Specifically examine: (a) completeness of emissions boundary (b) quality and additionality of offsets (c) Scope 3 omission impact.\n\n2. Estimate Verdant\'s Scope 3 emissions using industry benchmarks. If Scope 3 represents 60-80% of total emissions for a solar panel manufacturer, what is the true total emissions figure? Is the company carbon neutral when Scope 3 is included?\n\n3. The offsets were purchased at $4/tCO2e — significantly below the $8-15/tCO2e market rate. What does this pricing tell you about offset quality? What specific verification would you require?\n\n4. Advise the institutional investor: should they rely on this net-zero claim for their ESG investment thesis? If not, what specific improvements must Verdant make for the claim to be credible? Draft three conditions for the investment agreement.',
    admin_only: {
      strong_response: 'Immediately identifies the Scope 3 omission as fatal to the carbon neutrality claim. Solar panel manufacturing has significant Scope 3 emissions (polysilicon production, logistics, end-of-life). Including Scope 3, total emissions are likely 78,000-98,000 tCO2e — far exceeding the 24,000 tCO2e of offsets purchased. The claim collapses when the full emissions boundary is applied.',
      critical_gap: 'Accepts the Scope 1+2 boundary as complete and validates the carbon neutrality claim because offsets exceed reported emissions. Treats the Scope 3 omission as a "future improvement" rather than a fundamental flaw in the current claim. Does not question offset quality despite below-market pricing.',
      non_obvious_signal: 'The Scope 3 omission is not a minor gap — it transforms the assessment from "carbon neutral" to "reporting less than 30% of total emissions." Solar panel manufacturing has heavy Scope 3 (polysilicon from China, logistics, installation). The company has cherry-picked the emissions boundary to make the claim work.',
    },
  },
  {
    code: 'B4-014',
    role: 'Big 4 Advisory',
    difficulty: 'Expert',
    title: 'Purchase Price Allocation — Ind AS 103 Intangible Valuation Post-Acquisition',
    situation: 'Your valuation practice has been engaged to perform purchase price allocation (PPA) under Ind AS 103 for a completed acquisition. The acquirer paid ₹1,200 Cr for a specialty pharma company. Tangible net assets are ₹320 Cr. You must allocate the remaining ₹880 Cr to identifiable intangibles and goodwill.',
    company_overview: 'Acquirer: Bharat Pharma Ltd (listed). Target: NovaCure Therapeutics Pvt Ltd — specialty pharma. Purchase price: ₹1,200 Cr. Tangible net assets (FMV): ₹320 Cr. Excess over tangible assets: ₹880 Cr. Identifiable intangibles to value: (1) Drug development pipeline (3 molecules in Phase II/III), (2) Existing product portfolio (8 marketed drugs), (3) Customer relationships (top 5 hospital chains), (4) Trade name/brand "NovaCure", (5) Assembled workforce (180 R&D scientists).',
    financials: {
      headers: ['', 'Pipeline Molecule A', 'Pipeline Molecule B', 'Pipeline Molecule C'],
      rows: [
        { label: 'Development Stage', values: ['Phase III', 'Phase II', 'Phase II'] },
        { label: 'Probability of Approval', values: ['65%', '35%', '25%'] },
        { label: 'Peak Revenue Estimate', values: ['₹280 Cr/yr', '₹180 Cr/yr', '₹420 Cr/yr'] },
        { label: 'Remaining Dev Cost', values: ['₹38 Cr', '₹62 Cr', '₹84 Cr'] },
        { label: 'Years to Market', values: ['2', '4', '5'] },
        { label: 'Patent Life Remaining', values: ['12 years', '15 years', '14 years'] },
        { label: 'Existing Product Revenue', values: ['—', '—', '₹340 Cr/yr total'] },
        { label: 'Customer Relationship Value', values: ['—', '—', '₹45-60 Cr est.'] },
      ],
    },
    market_context: 'Under Ind AS 103, the acquirer must identify and fair-value all identifiable intangible assets separately from goodwill. The allocation impacts future P&L through amortisation charges. Maximising goodwill (which is not amortised under Ind AS but tested annually for impairment) vs. maximising identifiable intangibles (which are amortised) has material earnings impact.\n\nThe drug pipeline valuation uses the Risk-Adjusted NPV (rNPV) methodology: probability-weight cash flows at each development stage. The existing product portfolio uses the Multi-Period Excess Earnings Method (MPEEM). Assembled workforce is not a separately identifiable intangible under Ind AS 103 — it should be included in goodwill.',
    task: '1. Calculate the rNPV (risk-adjusted NPV) for each pipeline molecule. Use the stage-specific probabilities and a 14% WACC for pharma. Show the total pipeline intangible value.\n\n2. Value the existing product portfolio using MPEEM. Assume: existing product revenue declines 8% annually post-patent expiry, cost of capital 12%, contributory asset charges of 4% of revenue.\n\n3. Allocate the full ₹880 Cr excess to: (a) pipeline intangibles (b) existing product portfolio (c) customer relationships (d) trade name (e) residual goodwill. The assembled workforce cannot be separately identified — where does it go?\n\n4. The acquirer\'s CFO wants to maximise goodwill allocation to minimise P&L amortisation charges. How do you respond? What are the audit and regulatory risks of aggressive goodwill allocation?',
    admin_only: {
      strong_response: 'Identifies that assembled workforce is not a separately identifiable intangible under Ind AS 103 and must be included in goodwill — not listed as a separate intangible. Correctly applies rNPV for pipeline, MPEEM for existing products, and With-and-Without for customer relationships. Addresses the CFO\'s request to maximise goodwill by explaining that inflating goodwill creates future impairment risk — goodwill must pass annual impairment tests, and if the acquisition underperforms, a large goodwill write-down hits P&L in one quarter.',
      critical_gap: 'Values all intangibles using a single DCF methodology rather than applying the correct methodology per intangible type. Lists assembled workforce as a separate intangible. Agrees to maximise goodwill allocation without flagging impairment risk.',
      non_obvious_signal: 'The CFO wants to maximise goodwill to avoid amortisation charges. But goodwill is tested annually for impairment — if the acquisition underperforms expectations, a large goodwill balance creates a massive write-down risk that hits P&L in a single quarter. The "save amortisation now, risk impairment later" trade-off is the key advisory judgment.',
    },
  },
  {
    code: 'B4-015',
    role: 'Big 4 Advisory',
    difficulty: 'Expert',
    title: 'Post-Merger Integration PMO — 90-Day Synergy Capture at Atlas-Meridian',
    situation: 'Your firm has been appointed as the post-merger integration (PMI) project management office for Atlas Corp\'s ₹2,400 Cr acquisition of Meridian Systems. The deal closed 10 days ago. The Board has mandated ₹180 Cr of synergies within 24 months. You have 45 minutes to present your 90-day integration plan.',
    company_overview: 'Acquirer: Atlas Corporation — IT services. Revenue ₹8,200 Cr. 42,000 employees. Target: Meridian Systems — niche cybersecurity. Revenue ₹1,400 Cr. 6,800 employees. Deal rationale: Cross-sell cybersecurity to Atlas\'s existing client base. Synergy target: ₹180 Cr (₹120 Cr revenue synergies, ₹60 Cr cost synergies). Culture: Atlas is hierarchical/process-driven. Meridian is flat/entrepreneurial. Attrition risk: Top 28 Meridian engineers (critical IP holders) have no retention agreements. Competing offers from 3 companies already received.',
    financials: {
      headers: ['', 'Revenue Synergies', 'Cost Synergies', 'Dis-synergies'],
      rows: [
        { label: 'Cross-Sell to Atlas Clients', values: ['₹80 Cr', '—', '—'] },
        { label: 'Joint Product Development', values: ['₹40 Cr', '—', '—'] },
        { label: 'Procurement Consolidation', values: ['—', '₹22 Cr', '—'] },
        { label: 'IT/Infrastructure Merger', values: ['—', '₹18 Cr', '—'] },
        { label: 'Headcount Rationalisation', values: ['—', '₹20 Cr', '—'] },
        { label: 'Client Conflict Attrition', values: ['—', '—', '-₹35 Cr'] },
        { label: 'Key Employee Departures', values: ['—', '—', '-₹45 Cr (if 10+ leave)'] },
        { label: 'Net Synergy Target', values: ['₹120 Cr', '₹60 Cr', '-₹80 Cr risk'] },
      ],
    },
    market_context: 'IT services M&A has a 60% failure rate in achieving stated synergies. The primary cause is revenue synergy overestimation (average achievement: 40-50% of stated target) and underestimation of dis-synergies (cultural clash, key person departures, client conflicts).\n\nThe 28 critical engineers represent approximately ₹280 Cr of revenue dependency (20% of Meridian\'s revenue runs through their client relationships and technical IP). If 10+ depart, the revenue dis-synergy of ₹45 Cr effectively wipes out most cost synergies.',
    task: '1. Design the 90-day integration plan with specific workstreams, milestones, and accountable owners. Prioritise ruthlessly — what must happen in days 1-30, 31-60, and 61-90?\n\n2. The 28 critical engineers have no retention agreements and competing offers. Design a retention programme that goes beyond cash (which they can always get more of). What non-monetary retention levers are available?\n\n3. Client conflict dis-synergy of ₹35 Cr is material. Identify how client conflicts arise in IT services mergers and what specific steps prevent them.\n\n4. The Board has set ₹180 Cr gross synergies. But dis-synergies could be ₹80 Cr. Should you report gross or net synergies? If net synergies are ₹100 Cr (₹180 Cr - ₹80 Cr), is the deal still value-accretive at ₹2,400 Cr acquisition price?',
    admin_only: {
      strong_response: 'Prioritises talent retention as Day 1-30 priority over cost synergy capture. Recognises that the 28 engineers represent a ₹280 Cr revenue dependency and that losing 10+ creates a dis-synergy cascade that destroys the deal economics. Designs non-monetary retention (autonomy, title, reporting line to CEO, equity in cybersecurity P&L) rather than just cash retention bonuses.',
      critical_gap: 'Starts with cost synergies (headcount reduction, procurement) and treats talent retention as a "Phase 2" activity. By the time retention is addressed in Month 3-4, the critical engineers have already accepted competing offers. Ignores dis-synergies entirely in the 90-day plan.',
      non_obvious_signal: 'The deal economics depend on retaining the 28 engineers, not on achieving ₹22 Cr of procurement savings. If 10+ engineers leave, the ₹45 Cr revenue dis-synergy plus lost cross-sell potential effectively turns the deal from value-accretive to value-destructive. Day 1-30 must be about people, not processes.',
    },
  },
];

