import type { DealCase } from './types';

export const B4_CASES: DealCase[] = [
  {
    code: 'B4-001',
    role: 'Big 4 Advisory',
    difficulty: 'Intermediate',
    title: 'Financial Due Diligence — Buy Side',
    situation: 'Your firm is engaged by a PE fund to conduct buy-side financial due diligence on a target company before a ₹240 Cr acquisition.',
    company_overview: 'MedEquip Distributors Pvt Ltd distributes 14 international medical device brands across 8 Indian states. Top 3 distributors account for 44% of revenue. One key brand (38% of revenue) has a contract expiring in 14 months.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['198', '241', '284'] },
        { label: 'Reported EBITDA (₹ Cr)', values: ['24', '30', '38'] },
        { label: 'EBITDA Margin', values: ['12.1%', '12.4%', '13.4%'] },
        { label: 'One-time Govt Tender Revenue (₹ Cr)', values: ['—', '—', '12'] },
        { label: 'Q4 Revenue Timing Issue (₹ Cr)', values: ['—', '—', '8'] },
        { label: 'Working Capital (₹ Cr)', values: ['48', '62', '74'] },
        { label: 'Debtor Days', values: ['72', '82', '94'] },
        { label: 'Industry Norm Debtor Days', values: ['60', '60', '60'] },
        { label: 'Key Brand Revenue Share', values: ['42%', '40%', '38%'] },
      ],
    },
    market_context: 'Indian medical device distribution growing 18% CAGR driven by hospital expansion and insurance penetration. However, the sector is consolidating — large global OEMs are bringing distribution in-house, reducing reliance on third-party distributors.\n\nGovernment tenders are one-time in nature and do not represent recurring revenue. Timing differences in Q4 revenue recognition are a common area of FDD scrutiny.',
    task: '1. Identify key quality of earnings adjustments.\n\n2. Calculate adjusted EBITDA after removing non-recurring items.\n\n3. Assess normalised working capital.\n\n4. Flag the top 3 due diligence risks requiring further investigation.\n\n5. Present your view: is the reported ₹38 Cr EBITDA sustainable?\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Calculates a bear case combining brand contract non-renewal (38% revenue at risk) with stripping the one-time government tender (₹12 Cr) and Q4 timing issue (₹8 Cr). Shows adjusted sustainable EBITDA could be ₹18-22 Cr — roughly half of reported.',
      critical_gap: 'Accepts reported EBITDA at face value or makes minor adjustments without combining the risks. Fails to connect the expiring brand contract with the revenue sustainability question.',
      non_obvious_signal: 'The expiring brand contract (38% of revenue) plus non-recurring government tender (₹12 Cr) means sustainable EBITDA could be materially lower than reported. The two risks compound when considered together.',
    },
  },
  {
    code: 'B4-002',
    role: 'Big 4 Advisory',
    difficulty: 'Intermediate',
    title: 'Vendor Due Diligence',
    situation: 'Your firm is engaged by the seller (promoter) of a logistics company to prepare a vendor due diligence report for potential buyers.',
    company_overview: 'SwiftMove Logistics Pvt Ltd is a last-mile delivery company serving B2B and B2C e-commerce. 5,200 delivery partners (gig workers). Operational in 34 cities. Top 2 customers (both large e-commerce platforms) = 71% of revenue.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['248', '284', '318'] },
        { label: 'EBITDA (₹ Cr)', values: ['24', '26', '28'] },
        { label: 'EBITDA Margin', values: ['9.7%', '9.2%', '8.8%'] },
        { label: 'Revenue per Delivery (₹)', values: ['54', '50', '47'] },
        { label: 'Cost per Delivery (₹)', values: ['42', '43', '43'] },
        { label: 'Gig Worker Churn (annual)', values: ['28%', '31%', '34%'] },
        { label: 'On-Time Delivery Rate', values: ['95.1%', '94.8%', '94.2%'] },
        { label: 'Customer Concentration (top 2)', values: ['64%', '68%', '71%'] },
        { label: 'Total Deliveries (Cr)', values: ['4.6', '5.7', '6.8'] },
      ],
    },
    market_context: 'Indian last-mile delivery market growing 24% but commoditising rapidly. Revenue per delivery declining as e-commerce platforms push pricing pressure. Gig worker classification is a regulatory overhang — India is expected to introduce formal gig worker protections within 2-3 years.\n\nIf gig workers are reclassified as employees, cost per delivery could increase 30-40% due to ESI, PF, and minimum wage compliance.',
    task: '1. As VDD lead, prepare an honest assessment of margin sustainability.\n\n2. Model 3 scenarios for next 3 years: base, downside (gig worker reclassification), upside (automation investment).\n\n3. Recommend how the seller should present this business to maximise transaction value while maintaining factual accuracy.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies the ethical tension in VDD — prepared for the seller but read by buyers. Recommends transparent disclosure of gig worker regulatory risk rather than minimising it. Calculates the P&L impact of reclassification.',
      critical_gap: 'Presents only the bull case to maximise seller value. Downplays the gig worker risk. Fails to recognise that VDD creates legal liability for the firm if it misleads buyers.',
      non_obvious_signal: 'VDD is prepared for the seller but read by buyers. Any information asymmetry that misleads buyers creates legal liability for the advisory firm. The ethical dimension is as important as the financial analysis.',
    },
  },
  {
    code: 'B4-003',
    role: 'Big 4 Advisory',
    difficulty: 'Intermediate',
    title: 'Working Capital Optimisation',
    situation: 'A manufacturing client has engaged your firm to identify and unlock ₹50 Cr of trapped working capital within 6 months.',
    company_overview: 'Durga Chemicals Ltd is a specialty chemicals manufacturer supplying pharma, agro, and textile companies. Revenue FY24: ₹520 Cr. EBITDA: ₹78 Cr. Current working capital: ₹168 Cr (32.3% of revenue vs industry benchmark 18-22%).',
    financials: {
      headers: ['', 'Current', 'Industry Benchmark', 'Gap'],
      rows: [
        { label: 'Raw Material Inventory (₹ Cr / Days)', values: ['42 / 29', '— / 28', 'Minimal'] },
        { label: 'WIP Inventory (₹ Cr / Days)', values: ['18 / 12', '— / 10', 'Minimal'] },
        { label: 'Finished Goods Inventory (₹ Cr / Days)', values: ['64 / 45', '— / 22', '₹33 Cr excess'] },
        { label: 'Slow-Moving FG (₹ Cr)', values: ['22', '—', 'Write-off risk'] },
        { label: 'Accounts Receivable (₹ Cr / Days)', values: ['88 / 62', '— / 45', '₹24 Cr excess'] },
        { label: 'Accounts Payable (₹ Cr / Days)', values: ['44 / 31', '— / 45', '₹20 Cr undertapped'] },
        { label: 'Total Working Capital (₹ Cr)', values: ['168', '~104', '₹64 Cr gap'] },
        { label: 'WC as % of Revenue', values: ['32.3%', '18-22%', '10-14% excess'] },
      ],
    },
    market_context: 'Specialty chemicals is a relationship-driven industry. Top 3 customers (48% of revenue) receive 90-day credit terms contractually — changing these terms risks customer attrition. Suppliers are open to longer payment terms if volume commitments are provided.\n\nSlow-moving inventory (₹22 Cr) resulted from a product line launched in FY23 that underperformed expectations. This inventory cannot be sold through normal channels.',
    task: '1. Calculate the working capital gap versus industry benchmark.\n\n2. Identify specific initiatives to release ₹50 Cr within 6 months.\n\n3. Quantify the impact of each initiative.\n\n4. Flag the risks of aggressive working capital extraction on customer and supplier relationships.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Separates structural improvements (AR reduction, AP extension) from one-time actions (₹22 Cr inventory liquidation at markdown). Sequences recommendations — structural fixes first for sustainable improvement, inventory liquidation as a one-time release with P&L impact disclosure.',
      critical_gap: 'Proposes "reduce AR by 17 days" without acknowledging the top-3-customer contractual constraint. Treats all working capital levers as equally actionable.',
      non_obvious_signal: 'The ₹22 Cr slow-moving FG inventory cannot be unlocked through process improvement — it requires markdown/write-off or alternate buyers. Separate structural improvements from one-time actions in the recommendation.',
    },
  },
  {
    code: 'B4-004',
    role: 'Big 4 Advisory',
    difficulty: 'Advanced',
    title: 'Business Valuation — Dispute',
    situation: 'Your firm has been engaged as an independent expert in a shareholder dispute. Two promoter-directors hold equal stakes and are splitting. You must value the company for the buyout.',
    company_overview: 'Aditya Precision Engineering Pvt Ltd manufactures precision components for aerospace and defence. Chennai-based. Founded 2008. Order book (firm): ₹340 Cr including a non-transferable DRDO contract of ₹140 Cr.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['72', '84', '94'] },
        { label: 'EBITDA (₹ Cr)', values: ['16', '18', '21'] },
        { label: 'PAT (₹ Cr)', values: ['10', '12', '14'] },
        { label: 'Net Worth (₹ Cr)', values: ['62', '74', '86'] },
        { label: 'Order Book — DRDO (₹ Cr)', values: ['—', '—', '140 (non-transferable)'] },
        { label: 'Order Book — HAL (₹ Cr)', values: ['—', '—', '92 (transferable w/ approval)'] },
        { label: 'Order Book — Private OEMs (₹ Cr)', values: ['—', '—', '108'] },
        { label: 'Total Order Book (₹ Cr)', values: ['—', '—', '340 (3.6x revenue)'] },
      ],
    },
    market_context: 'Indian aerospace and defence manufacturing growing 22% CAGR driven by Make in India and defence offset requirements. Small-scale precision manufacturers are rare — barriers to entry are high (certifications, security clearances).\n\nDRDO contracts are personal to the company but require government approval for change of control. In shareholder disputes, the standard of value is typically "fair market value" — assuming a hypothetical willing buyer and willing seller.',
    task: '1. Build a fair market valuation using three methodologies: DCF, comparable company multiples, and asset-based.\n\n2. Specifically address the DRDO contract treatment in each methodology.\n\n3. Reconcile the three values into a final range.\n\n4. Recommend a valuation for the expert report.\n\nState all assumptions and define the standard of value you are applying.',
    admin_only: {
      strong_response: 'Defines the standard of value (fair market value) before beginning calculations. Values the DRDO contract at probability-weighted transfer value, not face value. Recognises that "fair market value" assumes a hypothetical buyer who would discount non-transferable contracts.',
      critical_gap: 'Includes the DRDO contract at face value in the DCF without adjusting for transferability risk. Fails to define the standard of value, making the valuation framework unclear.',
      non_obvious_signal: 'The standard of value must be defined first — "fair market value" means the DRDO contract is valued at its probability-weighted transfer value, not face value. This is a legal and valuation methodology question, not just a financial exercise.',
    },
  },
  {
    code: 'B4-005',
    role: 'Big 4 Advisory',
    difficulty: 'Advanced',
    title: 'IPO Readiness Assessment',
    situation: 'A consumer goods company plans to file its DRHP within 9 months and has engaged your firm to identify gaps in IPO readiness.',
    company_overview: 'Himalaya Wellness Products Ltd is an Ayurvedic personal care and wellness company. Revenue FY24: ₹890 Cr. EBITDA: ₹134 Cr (15% margin). 3-year revenue CAGR: 24%. CFO role vacant for 7 months.',
    financials: {
      headers: ['', 'Current State', 'SEBI Requirement', 'Gap'],
      rows: [
        { label: 'Accounting Standard', values: ['Indian GAAP', 'Ind AS', 'Transition required'] },
        { label: 'Related Party Txns (₹ Cr)', values: ['42', 'Arm\'s length docs required', 'High risk'] },
        { label: 'Pending Tax Dispute (₹ Cr)', values: ['11', 'Disclosure required', 'Medium risk'] },
        { label: 'CFO Role', values: ['Vacant 7 months', 'Must be filled', 'Critical gap'] },
        { label: 'Independent Directors', values: ['3 of 8 (37.5%)', '50% minimum', 'Need 1-2 more'] },
        { label: 'Revenue (₹ Cr)', values: ['890', '—', '—'] },
        { label: 'PAT (₹ Cr)', values: ['89', '—', '—'] },
        { label: 'Subsidiary Revenue (₹ Cr)', values: ['18', '—', 'Tax dispute linked'] },
      ],
    },
    market_context: 'SEBI IPO regulations require Ind AS financials, minimum 50% independent directors, related party transaction disclosure, and a qualified management team. DRHP review typically takes 3-4 months after filing.\n\nRelated party transactions are the most scrutinised area in SEBI IPO reviews. ₹42 Cr of RPTs with promoter entities will require either rationalisation or shareholder approval with arm\'s length documentation.',
    task: '1. Identify all IPO readiness gaps across financial, governance, and legal dimensions.\n\n2. Prioritise by severity and time to remediate.\n\n3. Build a 9-month remediation roadmap.\n\n4. Identify the 2 issues that could delay or derail the IPO if not resolved.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Prioritises RPT rationalisation above Ind AS transition because RPTs are the highest regulatory risk — SEBI can reject or delay the DRHP based on RPT concerns. Also flags CFO vacancy as a deal-breaker for institutional investor confidence.',
      critical_gap: 'Lists all gaps without prioritising by severity. Treats Ind AS transition as the most important issue without recognising that RPTs and governance gaps are more likely to derail the IPO.',
      non_obvious_signal: 'Related party transactions (₹42 Cr) are the most dangerous issue — SEBI scrutinises RPTs intensely. If these are promoter-entity transactions, they need arm\'s length documentation before filing. This is higher priority than Ind AS transition.',
    },
  },
  {
    code: 'B4-006',
    role: 'Big 4 Advisory',
    difficulty: 'Advanced',
    title: 'Restructuring Advisory',
    situation: 'A retail chain is facing imminent insolvency. Your firm must advise on a pre-packaged IBC restructuring before lenders initiate formal proceedings.',
    company_overview: 'Trendline Fashion Pvt Ltd is a 350-store fast fashion retail chain. Founded 2012. Revenue peak ₹1,100 Cr (FY22). 180 stores are profitable, 170 are loss-making. Online channel: ₹92 Cr (+34% YoY). Cash available: ₹8 Cr (11 days runway).',
    financials: {
      headers: ['', 'FY22 (Peak)', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['1,100', '820', '640'] },
        { label: 'EBITDA (₹ Cr)', values: ['88', '12', '-38'] },
        { label: 'Total Debt (₹ Cr)', values: ['280', '380', '480'] },
        { label: 'Trade Creditors Overdue 90+ days (₹ Cr)', values: ['—', '80', '180'] },
        { label: 'Employees', values: ['4,800', '4,500', '4,200'] },
        { label: 'Profitable Stores', values: ['280', '220', '180'] },
        { label: 'Loss-Making Stores', values: ['70', '130', '170'] },
        { label: 'Online Revenue (₹ Cr)', values: ['42', '68', '92'] },
        { label: 'Cash Available (₹ Cr)', values: ['48', '22', '8'] },
      ],
    },
    market_context: 'Indian fast fashion retail facing structural shift to online. Physical retail requires high footfall to cover rental costs. Store-level EBITDA breakeven typically requires ₹1.8 Cr annual revenue per store.\n\nPre-packaged IBC allows companies to negotiate restructuring terms before entering formal insolvency. Anchor lender (48% of debt) has indicated willingness to convert ₹120 Cr to equity if other lenders follow. Promoter has personal guarantees on store leases.',
    task: '1. Design a restructuring plan that keeps the viable 180 stores operating.\n\n2. Calculate minimum debt reduction required for viability.\n\n3. Model 3 scenarios: liquidation, restructuring with lender support, restructuring with strategic investor.\n\n4. Recommend the path maximising recovery for all stakeholders.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies the promoter personal guarantee on store leases as an alignment problem — the promoter will resist closing stores because each closure crystallises a personal liability. Recommends addressing lease guarantees as part of the restructuring deal.',
      critical_gap: 'Proposes closing 170 loss-making stores without considering the promoter\'s personal guarantee liability. Ignores the incentive misalignment between promoter and lenders.',
      non_obvious_signal: 'Promoter personal guarantees on store leases create an incentive misalignment — the promoter will resist any restructuring that closes stores because each closure triggers a personal liability. The restructuring plan must address this to get promoter cooperation.',
    },
  },
  {
    code: 'B4-007',
    role: 'Big 4 Advisory',
    difficulty: 'Advanced',
    title: 'Forensic Accounting Review',
    situation: 'A listed company\'s audit committee has engaged your firm to investigate irregularities flagged by a whistleblower. The board needs preliminary findings within 14 days.',
    company_overview: 'Suraksha Infrastructure Ltd (listed on BSE). Revenue FY24: ₹1,240 Cr. Three whistleblower allegations: (1) Revenue recognition irregularity on 3 projects (₹180 Cr), (2) Related party subcontracting at 28% above market rates (₹42 Cr), (3) ₹18 Cr advances to a 2-employee supplier.',
    financials: {
      headers: ['', 'Allegation', 'Amount (₹ Cr)', 'Revenue %'],
      rows: [
        { label: 'Revenue Recognition Issue', values: ['3 projects: 34% physical progress, 70% revenue recognised', '180', '14.5%'] },
        { label: 'Related Party Overpricing', values: ['Promoter entity subcontract at 28% above market', '42', '3.4%'] },
        { label: 'Suspicious Supplier Advance', values: ['2-employee supplier, unclear business justification', '18', '1.5%'] },
        { label: 'Total Revenue (₹ Cr)', values: ['—', '1,240', '100%'] },
        { label: 'Materiality Threshold (5%)', values: ['—', '62', '—'] },
      ],
    },
    market_context: 'SEBI regulations require prompt disclosure of material information to the stock exchange. If the revenue recognition issue (₹180 Cr = 14.5% of revenue) is confirmed as material, the company may have a disclosure obligation before the investigation concludes.\n\nPercentage of completion (POC) revenue recognition is the most common area of accounting fraud in construction companies. The gap between physical progress (34%) and revenue recognised (70%) is a significant red flag.',
    task: '1. Design a preliminary investigation framework.\n\n2. Identify the 5 data sources and documents to examine first.\n\n3. Determine which allegation is most likely to constitute a material misstatement.\n\n4. Recommend whether the board should make an immediate stock exchange disclosure while investigation is ongoing.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Addresses the stock exchange disclosure question first — SEBI requires prompt disclosure of material information. The ₹180 Cr revenue issue exceeds the 5% materiality threshold (₹62 Cr). Recommends the board disclose the investigation before completing it.',
      critical_gap: 'Focuses on investigation methodology without addressing the disclosure timing question. Treats all three allegations as equally important without calculating materiality.',
      non_obvious_signal: 'The stock exchange disclosure decision is the most urgent question. If the revenue recognition issue (14.5% of revenue) is potentially material, SEBI may require disclosure before the investigation concludes. Address timing before methodology.',
    },
  },
];
