import type { DealCase } from './types';

export const CF_CASES: DealCase[] = [
  {
    code: 'CF-001',
    role: 'Corporate Finance',
    difficulty: 'Intermediate',
    title: 'Capital Structure Optimisation',
    situation: 'The CFO of a mid-market IT services company has asked you to recommend the optimal capital structure to fund a ₹200 Cr expansion while maintaining investment-grade credit metrics.',
    company_overview: 'CloudForce IT Services Ltd. Revenue FY24: ₹680 Cr. EBITDA: ₹122 Cr (18%). Net debt-free currently. 4,200 employees across 3 delivery centres. Plans to open 2 new centres and expand into BFSI vertical.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['510', '590', '680'] },
        { label: 'EBITDA (₹ Cr)', values: ['87', '104', '122'] },
        { label: 'EBITDA Margin', values: ['17.1%', '17.6%', '18.0%'] },
        { label: 'PAT (₹ Cr)', values: ['62', '74', '88'] },
        { label: 'Cash on Balance Sheet (₹ Cr)', values: ['48', '62', '78'] },
        { label: 'Total Debt (₹ Cr)', values: ['0', '0', '0'] },
        { label: 'ROCE', values: ['22%', '24%', '26%'] },
        { label: 'Current P/E (listed)', values: ['—', '—', '24x'] },
        { label: 'Market Cap (₹ Cr)', values: ['—', '—', '2,112'] },
      ],
    },
    market_context: 'Indian IT services companies typically maintain conservative capital structures. Debt financing available at 9-10% for investment-grade IT companies. Equity dilution at current valuations (24x P/E) is expensive.\n\nRating agencies expect Net Debt/EBITDA < 2.0x for investment-grade in IT services. Tax shield benefit of debt at 25.17% corporate tax rate.',
    task: '1. Compare three funding options: all-debt, all-equity, and optimal mix.\n\n2. Calculate WACC under each scenario.\n\n3. Model the impact on EPS, ROCE, and credit metrics post-expansion.\n\n4. Recommend the optimal capital structure with quantified reasoning.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Calculates the EPS accretion/dilution breakpoint. Shows that at 26% ROCE and 9% cost of debt, debt creates significant EPS accretion vs equity dilution. Recommends 70:30 debt-equity mix that maximises WACC reduction while staying under 2.0x leverage.',
      critical_gap: 'Recommends all-equity because "IT companies should be debt-free" without modelling the cost of equity dilution at 24x P/E.',
      non_obvious_signal: 'At 26% ROCE and 9% cost of debt, the company is destroying value by being debt-free. The tax shield alone justifies moderate leverage. The CFO needs to understand the cost of its current equity-only capital structure.',
    },
  },
  {
    code: 'CF-002',
    role: 'Corporate Finance',
    difficulty: 'Intermediate',
    title: 'Working Capital Financing',
    situation: 'A fast-growing D2C consumer brand is facing a working capital crisis despite strong revenue growth. The CFO needs a financing solution within 30 days.',
    company_overview: 'NaturBlend Foods Pvt Ltd makes healthy snacks sold online and through modern trade. Revenue tripled in 2 years. Currently out of stock on 6 of 14 SKUs due to inability to fund raw material procurement.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['18', '38', '54'] },
        { label: 'Gross Margin', values: ['52%', '50%', '48%'] },
        { label: 'EBITDA (₹ Cr)', values: ['-2.4', '1.2', '4.3'] },
        { label: 'Cash Conversion Cycle (days)', values: ['88', '102', '118'] },
        { label: 'Inventory Days', values: ['42', '58', '72'] },
        { label: 'Receivable Days (Retail/Online)', values: ['38', '44', '52'] },
        { label: 'Payable Days', values: ['-8', '0', '6'] },
        { label: 'Monthly Cash Burn (₹ Cr)', values: ['0.8', '0.4', '0.2'] },
        { label: 'Bank Balance (₹ Cr)', values: ['4.2', '2.8', '1.1'] },
      ],
    },
    market_context: 'Indian healthy snacks market growing 28% CAGR. D2C brands face working capital challenges because: (1) modern trade retailers pay on 45-60 day terms, (2) quick-commerce platforms require inventory pre-positioning, (3) raw material suppliers demand advance payment from small buyers.\n\nRevenue-based financing options (e.g., Velocity, GetVantage) available at 15-18% effective cost. Bank working capital lines available at 12% but require property collateral.',
    task: '1. Diagnose the root cause of the working capital crisis.\n\n2. Calculate the minimum working capital financing required to support ₹80 Cr revenue target.\n\n3. Compare financing options: bank WC line, revenue-based financing, inventory financing, factoring.\n\n4. Recommend the optimal mix of financing and operational improvements.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies that the working capital problem is structural, not temporary — each rupee of revenue growth requires ₹0.32 of working capital (118 CCC days). Revenue growth actually makes the crisis worse without financing.',
      critical_gap: 'Recommends only a financing solution without addressing the operational causes. The 118-day CCC needs structural reduction alongside financing.',
      non_obvious_signal: 'Growth is making the crisis worse, not better. Each rupee of additional revenue requires ₹0.32 of working capital funding. Without both financing AND operational CCC reduction, the company will always be cash-starved.',
    },
  },
  {
    code: 'CF-003',
    role: 'Corporate Finance',
    difficulty: 'Advanced',
    title: 'Transfer Pricing Optimisation',
    situation: 'A multinational\'s India subsidiary is being investigated by transfer pricing authorities. ₹28 Cr of adjustments have been proposed. You must defend the current pricing or recommend restructuring.',
    company_overview: 'GlobalTech India Pvt Ltd is the India subsidiary of a US-listed tech company. Provides software development services to the parent company under a cost-plus arrangement. 2,800 employees in Hyderabad.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue from Parent (₹ Cr)', values: ['340', '380', '420'] },
        { label: 'Cost Base (₹ Cr)', values: ['298', '336', '372'] },
        { label: 'Markup Applied', values: ['14%', '13%', '13%'] },
        { label: 'PBT (₹ Cr)', values: ['42', '44', '48'] },
        { label: 'Proposed TP Adjustment (₹ Cr)', values: ['—', '—', '28'] },
        { label: 'Comparable Companies Markup Range', values: ['14-18%', '15-19%', '16-22%'] },
        { label: 'Tax Authority Proposed Markup', values: ['—', '—', '20%'] },
        { label: 'Employee Cost as % of Total Cost', values: ['74%', '76%', '78%'] },
        { label: 'Parent Company EBITDA Margin', values: ['32%', '31%', '30%'] },
      ],
    },
    market_context: 'Indian transfer pricing regulations follow the arm\'s length principle. The TNMM (Transactional Net Margin Method) is the most common method for IT services companies.\n\nComparable company analysis shows that independent IT services companies earn 16-22% operating margins. The India subsidiary\'s 13% markup falls below the lower quartile, which triggers TP scrutiny.',
    task: '1. Evaluate the TP authority\'s proposed adjustment of ₹28 Cr.\n\n2. Identify the best defence strategies for the current 13% markup.\n\n3. If the current markup is indefensible, recommend a revised transfer pricing policy.\n\n4. Calculate the tax impact of full adjustment vs negotiated settlement.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies that the declining markup (14%→13%) while comparable ranges are increasing (14-18% to 16-22%) creates a pattern that TP authorities will use as evidence of profit shifting. Recommends proactive markup adjustment to 16% to settle within the arm\'s length range.',
      critical_gap: 'Defends the 13% markup without addressing the comparable company analysis showing 16-22% range. Uses aggressive arguments without risk-weighting the litigation outcome.',
      non_obvious_signal: 'The trend is the problem — markup declined from 14% to 13% while the comparable range moved from 14-18% to 16-22%. The widening gap creates a pattern that TP authorities will use as evidence of deliberate profit shifting.',
    },
  },
  {
    code: 'CF-004',
    role: 'Corporate Finance',
    difficulty: 'Advanced',
    title: 'Treasury Risk Management',
    situation: 'The CFO of an export-oriented company has asked you to design a hedging strategy for USD receivables. The company lost ₹14 Cr to FX movements in FY24.',
    company_overview: 'Prism Exports Ltd is a garment exporter. Revenue FY24: ₹480 Cr (72% exports, all USD-denominated). Typical order-to-payment cycle: 90-120 days. No hedging policy currently in place.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['380', '420', '480'] },
        { label: 'Export Revenue (₹ Cr)', values: ['266', '302', '346'] },
        { label: 'EBITDA (₹ Cr)', values: ['42', '46', '43'] },
        { label: 'EBITDA Margin', values: ['11.1%', '11.0%', '9.0%'] },
        { label: 'FX Gain/(Loss) (₹ Cr)', values: ['+4', '-2', '-14'] },
        { label: 'EBITDA ex-FX', values: ['38', '48', '57'] },
        { label: 'Average USD/INR Rate', values: ['74.5', '82.3', '83.1'] },
        { label: 'USD/INR Volatility (annualised)', values: ['4.2%', '6.8%', '3.1%'] },
        { label: 'Forward Premium (3-month annualised)', values: ['3.8%', '4.1%', '3.5%'] },
      ],
    },
    market_context: 'INR/USD has been on a depreciating trend but with increasing volatility. Forward premiums (3-4% annualised) represent the cost of hedging. Options provide downside protection but at higher upfront premium cost.\n\nRBI allows corporates to hedge up to 100% of expected receivables. Natural hedging (matching USD costs with USD revenues) is the most cost-effective strategy but requires structural changes.',
    task: '1. Quantify the FX risk exposure — how much can the company lose in a 5% adverse move?\n\n2. Design a hedging strategy using forwards, options, or a combination.\n\n3. Model the cost of hedging vs the cost of remaining unhedged.\n\n4. Recommend a hedging policy (% of receivables, instruments, tenor).\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Separates the EBITDA impact — underlying EBITDA improved (₹38→57 Cr) but FX losses masked it. Shows that FX is a material risk (₹14 Cr = 24% of EBITDA). Recommends layered hedging: 80% forwards for 0-3 months, 50% options for 3-6 months.',
      critical_gap: 'Recommends 100% forward hedging without calculating the cost (3.5% annualised premium). Or recommends no hedging because "INR is depreciating long-term." Both extremes ignore the risk-reward calculation.',
      non_obvious_signal: 'The company\'s underlying business is actually improving (ex-FX EBITDA grew from ₹38 to ₹57 Cr). FX losses are masking operational improvement. This reframes the problem — the hedging strategy should protect operational gains, not speculate on currency direction.',
    },
  },
  {
    code: 'CF-005',
    role: 'Corporate Finance',
    difficulty: 'Advanced',
    title: 'Dividend Policy Design',
    situation: 'A listed family-owned conglomerate is under investor pressure to formalise its dividend policy. The promoter family wants to maintain control while satisfying institutional investors.',
    company_overview: 'Swaraj Group Ltd (listed, market cap ₹8,400 Cr). Diversified: auto components (48% revenue), textiles (32%), real estate (20%). Promoter holding: 63%. Cash on balance sheet: ₹820 Cr. No dividend paid in last 3 years.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['2,420', '2,680', '2,940'] },
        { label: 'EBITDA (₹ Cr)', values: ['340', '388', '426'] },
        { label: 'PAT (₹ Cr)', values: ['188', '218', '248'] },
        { label: 'Cash on BS (₹ Cr)', values: ['520', '680', '820'] },
        { label: 'Capex (₹ Cr)', values: ['120', '140', '160'] },
        { label: 'Free Cash Flow (₹ Cr)', values: ['148', '168', '188'] },
        { label: 'Dividend Paid', values: ['₹0', '₹0', '₹0'] },
        { label: 'Institutional Investor Holding', values: ['18%', '20%', '22%'] },
        { label: 'Promoter Personal Tax Rate', values: ['—', '—', '35.88%'] },
      ],
    },
    market_context: 'SEBI has recommended that listed companies formalise dividend policies. Institutional investors increasingly voting against boards that hoard cash without clear deployment plans.\n\nPromoter family uses the company\'s cash reserves for diversification — real estate division (20% of revenue) has subpar ROCE (8% vs group average 18%). Institutional investors suspect cross-subsidisation.',
    task: '1. Design a dividend policy that balances promoter control, investor expectations, and growth capital needs.\n\n2. Compare: fixed payout ratio, progressive dividend, residual dividend model.\n\n3. Model the tax impact for different stakeholder groups.\n\n4. Address the institutional investor concern about cash hoarding and real estate cross-subsidisation.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Frames the dividend policy as a governance issue, not just a financial decision. The ₹820 Cr cash pile and the subpar real estate division suggest the promoter is using listed company capital for non-core investments. Recommends linking dividend policy to segment ROCE thresholds.',
      critical_gap: 'Designs a dividend policy purely on financial metrics without addressing the governance concern. Ignores the real estate cross-subsidisation signal.',
      non_obvious_signal: 'The real governance issue is the real estate division — 20% of revenue with 8% ROCE vs 18% group average. Institutional investors suspect the promoter is using listed company cash for personal real estate interests. The dividend policy must address this indirectly.',
    },
  },
  {
    code: 'CF-006',
    role: 'Corporate Finance',
    difficulty: 'Advanced',
    title: 'Debt Refinancing Strategy',
    situation: 'A real estate developer\'s ₹450 Cr debt is coming due in 8 months. Current projects are 60% sold but construction is 40% complete. The CFO needs a refinancing plan.',
    company_overview: 'Pinnacle Realty Developers Ltd. 3 active projects across Pune and Mumbai. Total saleable area: 2.4M sq ft. Sold 60% (1.44M sq ft). Collections received: ₹380 Cr of ₹720 Cr total expected. Construction cost remaining: ₹280 Cr.',
    financials: {
      headers: ['', 'Project Alpha', 'Project Beta', 'Project Gamma'],
      rows: [
        { label: 'Location', values: ['Mumbai Suburbs', 'Pune East', 'Pune West'] },
        { label: 'Total Saleable Area (sq ft)', values: ['800,000', '900,000', '700,000'] },
        { label: 'Sold %', values: ['72%', '58%', '48%'] },
        { label: 'Construction Progress', values: ['55%', '35%', '28%'] },
        { label: 'Expected Revenue (₹ Cr)', values: ['320', '240', '160'] },
        { label: 'Collections Received (₹ Cr)', values: ['180', '120', '80'] },
        { label: 'Remaining Construction Cost (₹ Cr)', values: ['80', '110', '90'] },
        { label: 'Current Debt (₹ Cr)', values: ['180', '160', '110'] },
        { label: 'Debt Maturity', values: ['6 months', '8 months', '10 months'] },
      ],
    },
    market_context: 'Indian real estate debt refinancing market is tight — NBFC liquidity has contracted since the IL&FS crisis. Banks reluctant to lend to developers with delayed projects.\n\nRERA regulations require all customer collections to be deposited in escrow accounts — developer cannot use Project Alpha collections to fund Project Beta construction. This creates project-level funding silos.',
    task: '1. Assess which project(s) can self-fund completion from customer collections.\n\n2. Calculate the net funding gap after accounting for RERA escrow constraints.\n\n3. Compare refinancing options: bank refinance, NBFC construction finance, AIF (Alternative Investment Fund).\n\n4. Recommend a refinancing structure that clears ₹450 Cr of maturing debt.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Models each project\'s cash flow independently due to RERA escrow constraints. Shows that Project Alpha can self-fund but Beta and Gamma cannot — cross-subsidy is not allowed. The funding gap is larger than it appears when RERA constraints are applied.',
      critical_gap: 'Pools all three projects\' cash flows together without considering RERA escrow constraints. Shows a smaller funding gap that is fictitious because the developer cannot actually move cash between projects.',
      non_obvious_signal: 'RERA escrow constraints mean each project must be evaluated independently for cash flow sufficiency. Pooling cash flows across projects is illegal. The funding gap is project-specific, not aggregate — Project Alpha is fine, but Beta and Gamma need external capital.',
    },
  },
  {
    code: 'CF-007',
    role: 'Corporate Finance',
    difficulty: 'Advanced',
    title: 'M&A Integration Planning',
    situation: 'Your company (Monarch Industries, ₹1,200 Cr revenue) just acquired a competitor (VectorTech, ₹480 Cr revenue) for ₹380 Cr. Day 1 of integration begins tomorrow. You are the integration PMO lead.',
    company_overview: 'Acquirer: Monarch Industries Ltd — industrial automation components. Target: VectorTech Pvt Ltd — similar products but serving different OEM customers. 40% customer overlap. 22% product overlap. Two ERP systems (SAP vs Oracle).',
    financials: {
      headers: ['', 'Monarch (Acquirer)', 'VectorTech (Target)', 'Claimed Synergies'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['1,200', '480', '+₹48 Cr (cross-sell)'] },
        { label: 'EBITDA (₹ Cr)', values: ['204', '67', '+₹28 Cr (cost synergies)'] },
        { label: 'Employees', values: ['2,800', '1,100', '-180 (duplicate roles)'] },
        { label: 'Plants', values: ['3', '2', '-1 (consolidation)'] },
        { label: 'ERP System', values: ['SAP S/4HANA', 'Oracle NetSuite', 'SAP migration: ₹12 Cr'] },
        { label: 'Key Customer Overlap', values: ['40%', '40%', 'Revenue risk'] },
        { label: 'Product Overlap', values: ['22%', '22%', 'SKU rationalisation'] },
        { label: 'Management Retention', values: ['—', '3 key leaders identified', 'Retention bonus: ₹4.8 Cr'] },
      ],
    },
    market_context: 'McKinsey research shows 70% of M&A integrations fail to capture planned synergies. The first 100 days determine integration success or failure.\n\nCustomer overlap (40%) creates a revenue dissynergy risk — if the combined entity raises prices or changes account management, customers may shift to competitors. Plant consolidation saves ₹18 Cr annually but takes 18 months and costs ₹8 Cr in one-time expenses.',
    task: '1. Build a 100-day integration plan with specific milestones.\n\n2. Identify which synergies are achievable in Year 1 vs Year 2+.\n\n3. Quantify integration risks — customer attrition, employee turnover, execution delays.\n\n4. Recommend the 3 actions to take in the first 30 days.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Prioritises revenue protection over cost synergy extraction. Identifies customer overlap (40%) as the primary Day-1 risk — competitors will target confused accounts during integration. Recommends customer retention programme before any cost-cutting.',
      critical_gap: 'Leads with cost synergies (headcount reduction, plant consolidation) without first protecting the revenue base. Plans layoffs in Month 1 without considering knowledge transfer or customer relationship continuity.',
      non_obvious_signal: 'Revenue dissynergy risk — the 40% customer overlap means competitors will actively target these accounts during integration disruption. Protecting revenue is more valuable than extracting cost synergies in Year 1.',
    },
  },

  /* ═══════════════════════════════════════════════
     EXPERT CASES — CF-008 through CF-015
     ═══════════════════════════════════════════════ */

  {
    code: 'CF-008',
    role: 'Corporate Finance',
    difficulty: 'Expert',
    title: 'Convertible Bond Structuring — How Anti-Dilution Provisions Destroy Founder Value',
    situation: 'Your firm is advising the promoter-family of Orchid Healthcare Ltd on a ₹300 Cr fundraise. A large PE fund has proposed a Compulsorily Convertible Debenture (CCD) with full-ratchet anti-dilution protection. The promoter thinks this is "standard." You have 45 minutes to show them the true cost.',
    company_overview: 'Orchid Healthcare Ltd — Hospital chain, 4 hospitals, 1,200 beds. Revenue FY24: ₹640 Cr. EBITDA: ₹128 Cr (20%). Promoter holding: 72%. The PE fund is investing ₹300 Cr via CCDs at a pre-money valuation of ₹1,200 Cr (₹1,500 Cr post-money). Conversion price: ₹600/share. Full-ratchet anti-dilution clause means: if the company raises future capital at ANY lower price, the PE fund\'s conversion price resets to that lower price — retroactively.',
    financials: {
      headers: ['', 'Current', 'Post-PE Investment', 'If Down Round at ₹400/share'],
      rows: [
        { label: 'Pre-Money Valuation (₹ Cr)', values: ['—', '₹1,200', '—'] },
        { label: 'PE Investment', values: ['—', '₹300 Cr at ₹600/share', '—'] },
        { label: 'Shares to PE (CCD)', values: ['—', '5,00,000 shares', '7,50,000 shares (ratcheted)'] },
        { label: 'PE Ownership', values: ['0%', '20%', '27.3% (full ratchet)'] },
        { label: 'Promoter Dilution', values: ['72%', '57.6%', '52.4% → below 50%'] },
        { label: 'Effective Valuation to PE', values: ['—', '₹1,200 Cr', '₹800 Cr (33% discount)'] },
        { label: 'Promoter Value Destruction', values: ['—', '—', '₹144 Cr transferred to PE'] },
        { label: 'Weighted-Average Alternative', values: ['—', '—', '₹120 Cr impact (17% less)'] },
      ],
    },
    market_context: 'Full-ratchet anti-dilution is the most aggressive form of investor protection. It retroactively reprices all PE shares to the lowest future round price, regardless of the size of the down round. Weighted-average anti-dilution is the market standard — it adjusts proportionally based on the dilutive round size.\n\nIn India, promoters often sign full-ratchet clauses without understanding the exponential impact. A single down round can transfer 15-25% of equity value from promoter to PE. This is especially dangerous in healthcare, where expansion requires multiple fundraising rounds.',
    task: '1. Model the full impact of the full-ratchet anti-dilution clause. If the company raises a Series B at ₹400/share (33% below Series A), how many additional shares does the PE fund receive? What is the promoter\'s final holding?\n\n2. Compare full-ratchet vs weighted-average anti-dilution using the same down-round scenario. Quantify the difference in promoter dilution.\n\n3. The PE fund argues that full-ratchet "protects their downside." What is the counter-argument? What alternative protections can you offer that protect the PE\'s economics without the ratchet?\n\n4. Advise the promoter: should they accept the CCD with full-ratchet? If not, what specific modifications should they negotiate? Draft 3 counter-terms.',
    admin_only: {
      strong_response: 'Models the cascading dilution: at ₹400/share, PE\'s conversion price resets from ₹600 to ₹400. This increases PE\'s share count by 50% (from 5L to 7.5L shares). Promoter holding drops from 57.6% to 52.4% — dangerously close to losing majority control. More critically, shows that a SECOND down round would push promoter below 50%. Recommends weighted-average anti-dilution with a pay-to-play provision instead.',
      critical_gap: 'Calculates the ratchet impact on PE shares but fails to trace through to promoter ownership percentage. Does not model the second-round cascading effect. Accepts the PE\'s argument that full-ratchet is "standard market practice" without showing industry data.',
      non_obvious_signal: 'The real danger is not the first down round — it\'s the second. Full-ratchet compounds: if Series B is at ₹400 and Series C is at ₹350, the ratchet applies AGAIN. Two consecutive down rounds can push the promoter below 50%, triggering change-of-control clauses in lending agreements. The clause creates a cascading risk chain.',
    },
  },
  {
    code: 'CF-009',
    role: 'Corporate Finance',
    difficulty: 'Expert',
    title: 'Hybrid Capital Classification — Is This Instrument Debt or Equity Under Ind AS 32?',
    situation: 'A listed infrastructure company has raised ₹500 Cr through a "Perpetual Non-Cumulative Preference Share" (PNCPS) instrument. The CFO has classified it as equity. The statutory auditors disagree. You have been engaged to provide an independent opinion under Ind AS 32.',
    company_overview: 'Meridian Infrastructure Ltd (listed BSE/NSE). Revenue FY24: ₹4,200 Cr. Net debt: ₹2,800 Cr. Debt/Equity: 2.1x. The PNCPS instrument terms: (1) ₹500 Cr face value, (2) Coupon: 9% non-cumulative (dividend payable at board\'s discretion), (3) No maturity date (perpetual), (4) Step-up clause: if not called after Year 10, coupon increases to 14%, (5) Put option: investor can demand redemption at par + 2% after Year 15.',
    financials: {
      headers: ['', 'If Classified as Equity', 'If Classified as Debt', 'Impact'],
      rows: [
        { label: 'Total Equity (₹ Cr)', values: ['₹1,833 (incl ₹500)', '₹1,333', '₹500 Cr swing'] },
        { label: 'Total Debt (₹ Cr)', values: ['₹2,800', '₹3,300 (incl ₹500)', '₹500 Cr swing'] },
        { label: 'Debt/Equity Ratio', values: ['1.53x', '2.48x', 'Covenant breach at 2.5x'] },
        { label: 'Annual Coupon (₹ Cr)', values: ['₹45 (dividend — no P&L)', '₹45 (interest — hits P&L)', '₹45 Cr EPS impact'] },
        { label: 'Tax Treatment', values: ['No tax deduction', 'Tax deductible interest', '₹11.3 Cr tax saving'] },
        { label: 'Covenant: Max D/E', values: ['2.5x — compliant', '2.5x — BREACH at 2.48x', 'Marginal'] },
        { label: 'Rating Agency View', values: ['Hybrid equity credit (50%)', '100% debt', 'Varies by methodology'] },
        { label: 'EPS Impact', values: ['No EPS dilution', '₹45 Cr interest reduces PAT', 'Material'] },
      ],
    },
    market_context: 'Ind AS 32 classifies instruments based on substance, not form. The key test: does the issuer have an unconditional right to avoid delivering cash? If yes → equity. If the issuer can be forced to pay → debt.\n\nThe PNCPS has three features that challenge equity classification: (1) The step-up clause creates "economic compulsion" to call at Year 10 — this suggests a fixed maturity (not truly perpetual), (2) The investor put option at Year 15 creates a contractual obligation to deliver cash, (3) Non-cumulative dividends are at the board\'s discretion (equity feature) but the step-up makes it economically irrational NOT to pay.',
    task: '1. Apply the Ind AS 32 classification framework to each feature of the PNCPS. Which features support equity classification? Which support debt classification? What is the dominant feature?\n\n2. The step-up clause (9% to 14% after Year 10) creates "economic compulsion." Under Ind AS 32, does economic compulsion = contractual obligation? What does the standard actually say? What does practice show?\n\n3. The investor put option at Year 15 seems to settle the debate — it creates a contractual cash obligation. But the CFO argues that Year 15 is so far away that it can be classified as equity for the first 14 years. Is this argument valid under Ind AS 32?\n\n4. Provide your classification recommendation with a reasoned opinion. If the instrument is reclassified as debt, calculate the impact on: (a) Debt/Equity ratio (b) Covenant compliance (c) EPS (d) Tax position.',
    admin_only: {
      strong_response: 'Identifies the Year 15 put option as the decisive feature: Ind AS 32 requires classification at inception based on contractual terms, not based on when the obligation crystallises. The put option creates a contractual obligation to deliver cash — this overrides all other equity-like features. The instrument is debt from Day 1, regardless of the 15-year timeline.',
      critical_gap: 'Applies a "balance of features" test — counting equity features vs debt features — rather than the Ind AS 32 principle that ANY contractual obligation to deliver cash makes the instrument (or component) a financial liability. Accepts the CFO\'s argument that the Year 15 put can be ignored because it\'s far away.',
      non_obvious_signal: 'Ind AS 32 does not use a "balance of features" approach. A single contractual obligation to deliver cash makes the instrument a liability (or requires bifurcation). The Year 15 put option is that obligation — its timing is irrelevant. Classification is determined at inception based on contractual terms. The instrument should be classified as a compound instrument with a liability component from Day 1.',
    },
  },
  {
    code: 'CF-010',
    role: 'Corporate Finance',
    difficulty: 'Expert',
    title: 'Cross-Border Acquisition Financing — How Forex and Tax Leakage Destroy Deal Returns',
    situation: 'Your firm is advising Zenith Pharma Ltd on financing the $120M (₹1,000 Cr) acquisition of a European generic pharma company. The CFO wants to minimise the blended cost of financing. You have 45 minutes to design the optimal cross-border financing structure.',
    company_overview: 'Zenith Pharma Ltd (listed, India). Revenue FY24: ₹3,200 Cr. EBITDA: ₹640 Cr (20%). Net debt: ₹480 Cr. Pre-deal D/E: 0.36x. Target: GeneriChem GmbH (Germany). Revenue: €140M. EBITDA: €28M (20%). Acquisition price: $120M (₹1,000 Cr). Funding options being considered: Indian rupee term loan, ECB (External Commercial Borrowing), offshore USD/EUR facility, equity dilution.',
    financials: {
      headers: ['', 'INR Loan', 'ECB (USD)', 'Offshore EUR Loan', 'Equity'],
      rows: [
        { label: 'Interest Rate', values: ['10.5%', '6.5% (USD)', '5.0% (EUR)', 'CoE: 14%'] },
        { label: 'Forex Risk', values: ['High (₹→$ conversion)', 'High (USD repayment)', 'Natural hedge (EUR revenue)', 'None'] },
        { label: 'Tax Deductibility', values: ['India — yes', 'India — yes (with limits)', 'Germany — yes', 'Not applicable'] },
        { label: 'Withholding Tax', values: ['0%', '0% (if compliant)', '5-10% on interest', '0%'] },
        { label: 'RBI Approval Required', values: ['No', 'Yes (ECB route)', 'No (offshore entity)', 'SEBI approval'] },
        { label: 'Thin Capitalisation Risk', values: ['None', 'Sec 94B limit: 30% EBITDA', 'German limit: 30% EBITDA', 'None'] },
        { label: 'All-In Cost (post-tax, post-fx)', values: ['~8.5%', '~7.8%', '~5.8%', '14%'] },
        { label: 'EPS Accretion/(Dilution)', values: ['Accretive', 'Accretive', 'Most accretive', 'Dilutive'] },
      ],
    },
    market_context: 'Cross-border acquisition financing involves three interacting variables: (1) interest rate differential across currencies, (2) forex exposure on debt service, and (3) tax efficiency of the structure (interest deductibility, withholding tax, thin capitalisation). Optimising one variable often worsens another.\n\nThe natural hedge principle: if the target generates EUR revenue, financing in EUR eliminates forex risk on debt service. However, the EUR loan may not be tax-deductible in India if structured incorrectly. India\'s Section 94B limits interest deductions on cross-border debt to 30% of EBITDA.',
    task: '1. Calculate the all-in cost of each financing option including: nominal interest, forex hedging cost (use 3.5% annual forward premium for INR/USD, 2% for INR/EUR), withholding tax, and tax deductibility.\n\n2. The EUR offshore loan appears cheapest at ~5.8% all-in. But identify the tax leakage: if the EUR loan sits at the target entity level, is the interest deductible against Indian profits? If not, where does the tax shield sit? Does this change the effective cost comparison?\n\n3. Design the optimal financing structure using a combination of sources. Consider: Where should each loan sit (India holdco vs offshore SPV vs target entity)? How do thin capitalisation rules in India (Sec 94B) and Germany affect the structure?\n\n4. Model the post-acquisition consolidated financials: Debt/Equity, interest coverage, and EPS accretion/dilution under your recommended structure.',
    admin_only: {
      strong_response: 'Identifies the critical mismatch: the EUR loan is cheapest on paper but the tax shield sits in Germany (where the target entity is), not in India. Zenith\'s Indian profits don\'t benefit from the EUR interest deduction. To capture the tax shield in India, the loan must be structured as an ECB from the Indian parent to an SPV — but this triggers Section 94B thin capitalisation limits. The optimal structure is a blend: 60% offshore EUR (natural hedge) + 40% Indian ECB (tax shield capture), with intercompany pricing set to stay within thin-cap limits.',
      critical_gap: 'Selects the EUR loan purely on all-in cost without considering WHERE the tax deduction is captured. Shows 5.8% all-in cost but this assumes the Indian entity benefits from the interest deduction — which it doesn\'t if the loan is at the target entity level. The actual cost to the Indian consolidated group is higher.',
      non_obvious_signal: 'The location of the tax shield matters more than the nominal interest rate. A 5.0% EUR loan with a German tax shield is LESS valuable to Zenith (India) than a 6.5% ECB with an Indian tax shield, because India\'s tax rate (25.17%) is lower than the apparent saving. But the real insight is that the intercompany loan structure determines whether the group captures the shield at all.',
    },
  },
  {
    code: 'CF-011',
    role: 'Corporate Finance',
    difficulty: 'Expert',
    title: 'Securitisation of Future Receivables — ₹400 Cr ABS Structure for Digital Lender',
    situation: 'Your firm is structuring a ₹400 Cr asset-backed securitisation (ABS) for NeoFin Digital Lending, an NBFC. The company wants to securitise its personal loan portfolio to free up capital for growth. This is their first securitisation transaction. You have 45 minutes.',
    company_overview: 'NeoFin Digital Lending Pvt Ltd — NBFC (RBI registered). AUM: ₹1,800 Cr. Loan portfolio: 2.8 lakh personal loans, average ticket ₹64,000, average tenor 24 months. Portfolio yield: 22%. 90+ DPD delinquency: 4.8%. Net NPA: 2.1%. The proposed pool: ₹520 Cr of seasoned loans (6+ months) to be securitised at a ₹400 Cr rated issuance.',
    financials: {
      headers: ['', 'Pool Characteristics', 'Benchmark', 'Risk Assessment'],
      rows: [
        { label: 'Pool Size (₹ Cr)', values: ['₹520', '—', '—'] },
        { label: 'Issuance Amount (₹ Cr)', values: ['₹400', '—', '77% advance rate'] },
        { label: 'Number of Loans', values: ['2,80,000', '—', 'Granular pool (good)'] },
        { label: 'Average Ticket Size', values: ['₹64,000', '—', 'Small ticket (good)'] },
        { label: 'Weighted Avg Seasoning', values: ['8 months', 'Min 6 months', 'Compliant'] },
        { label: 'Portfolio Yield', values: ['22%', '—', 'High — subprime?'] },
        { label: '90+ DPD Delinquency', values: ['4.8%', '3-5% norm', 'At upper end'] },
        { label: 'Credit Enhancement Required', values: ['?', '—', 'To be calculated'] },
        { label: 'Expected Investor Coupon', values: ['9.5-10.5%', '—', 'AAA tranche'] },
      ],
    },
    market_context: 'RBI securitisation guidelines (2021) require: minimum holding period (MHP), minimum retention requirement (MRR), and true sale. For personal loans with original tenor up to 24 months, MHP = 6 months. MRR = 10% of the pool or 5% of each tranche (whichever is higher).\n\nCredit enhancement in Indian ABS typically uses a subordination waterfall: Senior tranche (AAA-rated, 80-85% of pool), Mezzanine tranche (A/BBB, 8-12%), First Loss Piece (FLP, held by originator, 5-8%). The FLP absorbs initial losses — its sizing determines the senior tranche rating.',
    task: '1. Design the tranche structure for the ₹400 Cr issuance. Size the Senior (AAA), Mezzanine, and First Loss Piece tranches. Calculate the credit enhancement percentage for the AAA tranche.\n\n2. The portfolio yield is 22% but the AAA investor coupon is ~10%. Where does the ~12% excess spread go? Model the excess spread waterfall: servicing fee, credit enhancement build-up, originator profit.\n\n3. RBI\'s MRR requires NeoFin to retain 10% of the pool. This means ₹52 Cr remains on NeoFin\'s books. The CFO asks: "If I\'m retaining ₹52 Cr + the First Loss Piece, haven\'t I retained most of the risk? What capital relief did I actually achieve?"\n\n4. Stress test the pool: if 90+ DPD delinquency doubles to 9.6%, what is the loss severity for each tranche? Does the AAA tranche remain protected? At what delinquency level does the AAA tranche start taking losses?',
    admin_only: {
      strong_response: 'Addresses the CFO\'s critical question: after MRR (₹52 Cr) + FLP (~₹30-40 Cr), NeoFin retains ₹82-92 Cr of risk on a ₹520 Cr pool — that\'s 16-18% retained. The capital relief is real but smaller than the headline ₹400 Cr suggests. More importantly, identifies that the excess spread (12% yield gap) is the primary credit enhancement — if delinquency spikes but excess spread covers losses, the FLP is never touched. Models the break-even delinquency rate where excess spread = losses.',
      critical_gap: 'Sizes the tranches mechanically without modelling the excess spread as credit enhancement. Treats credit enhancement as only the FLP, ignoring that the 12% excess spread provides ongoing loss absorption that is significantly larger than the structural subordination. Tells the CFO that ₹400 Cr of capital is freed up without calculating the actual retention.',
      non_obvious_signal: 'The excess spread (22% yield - 10% coupon - 1% servicing = ~11%) is the most powerful credit enhancement in the structure — more than the FLP. On a ₹520 Cr pool, 11% excess spread generates ~₹57 Cr of annual loss absorption. The FLP only needs to absorb losses that exceed the excess spread capacity. This fundamentally changes the tranche sizing calculation.',
    },
  },
  {
    code: 'CF-012',
    role: 'Corporate Finance',
    difficulty: 'Expert',
    title: 'Inter-Corporate Deposit Risk — When a Group Treasury Becomes a Shadow Bank',
    situation: 'You are the newly appointed CFO of Sapphire Group. The previous CFO set up an inter-corporate deposit (ICD) programme where group companies lend surplus cash to each other. The total ICD outstanding is ₹340 Cr across 14 entities. The board wants you to assess the risk.',
    company_overview: 'Sapphire Group — Family-owned conglomerate. 14 entities across textiles (₹800 Cr), real estate (₹400 Cr), hospitality (₹200 Cr), and renewable energy (₹150 Cr). Total group revenue: ₹1,550 Cr. The ICD programme: Profitable textile entities lend surplus cash to cash-burning real estate and hospitality entities. No formal credit assessment. No security. Interest rate: 12% (above bank FD rates). Total ICD outstanding: ₹340 Cr.',
    financials: {
      headers: ['', 'Lender Entities', 'Borrower Entities', 'Risk'],
      rows: [
        { label: 'Textile Co A (lender)', values: ['₹120 Cr lent', '—', 'Concentration risk'] },
        { label: 'Textile Co B (lender)', values: ['₹80 Cr lent', '—', 'No diversification'] },
        { label: 'Trading Co (lender)', values: ['₹60 Cr lent', '—', 'Working capital strain'] },
        { label: 'Other lenders (4 entities)', values: ['₹80 Cr lent', '—', 'Various'] },
        { label: 'Real Estate Co (borrower)', values: ['—', '₹180 Cr borrowed', 'Delayed projects'] },
        { label: 'Hospitality Co (borrower)', values: ['—', '₹110 Cr borrowed', 'Post-COVID recovery'] },
        { label: 'Renewable Energy (borrower)', values: ['—', '₹50 Cr borrowed', 'Pre-revenue'] },
        { label: 'Interest Income to Lenders', values: ['₹40.8 Cr/yr', '—', 'Accrued, not cash-received'] },
      ],
    },
    market_context: 'Inter-corporate deposits are not regulated by RBI (unlike NBFC lending). There is no minimum capital adequacy, no provisioning requirement, and no NPA recognition standard. If a borrower entity defaults on ICDs, the lender entity writes off the amount against P&L.\n\nThe legal risk: if the textile entity\'s banks discover that ₹120 Cr of "cash and bank balances" is actually deployed as unsecured ICDs to group real estate companies, they may call their working capital facilities. Most bank sanction letters prohibit diversion of working capital funds to inter-corporate lending.',
    task: '1. Map the ICD exposure across all 14 entities. Calculate concentration risk — what percentage of each lender entity\'s net worth is exposed as ICDs? Flag any entity where ICD exposure exceeds 50% of net worth.\n\n2. The interest income of ₹40.8 Cr is "accrued" on the lender entities\' books. But is it actually being collected in cash? If the real estate and hospitality entities are cash-burning, where is the cash to pay interest? Is this a Ponzi-like accrual where interest is capitalised rather than paid?\n\n3. If Textile Co A\'s bankers discover the ₹120 Cr ICD exposure, what specific actions can they take? Review the typical bank sanction letter clauses regarding diversion of funds.\n\n4. Recommend a wind-down plan for the ICD programme. How do you unwind ₹340 Cr of inter-corporate exposure without triggering a liquidity crisis in the borrower entities?',
    admin_only: {
      strong_response: 'Identifies the accrual vs cash question as the critical risk: if ₹40.8 Cr of interest is accrued but not received in cash, the lender entities are overstating their profits by ₹40.8 Cr. The real estate entity\'s inability to pay interest in cash suggests the ICDs may be unrecoverable — the interest is being capitalised (added to the ICD balance), creating a Ponzi-like growth in exposure. Recommends immediate cash-basis recognition of ICD interest.',
      critical_gap: 'Treats the ICD programme as a straightforward treasury management exercise. Accepts the accrued interest income without verifying cash collection. Does not check bank sanction letters for diversion clauses. Proposes a gradual wind-down without assessing whether the borrower entities can actually repay.',
      non_obvious_signal: 'The ₹40.8 Cr interest income is likely not being collected in cash — it\'s being capitalised (added to the ICD balance). This means the ICD exposure is growing automatically at 12%/year. After 3 years of capitalised interest, the original ₹340 Cr has silently become ₹475 Cr. The textile entities\' profits are overstated by the uncollected accrued interest.',
    },
  },
  {
    code: 'CF-013',
    role: 'Corporate Finance',
    difficulty: 'Expert',
    title: 'Leveraged Recapitalisation vs Buyback — How to Return ₹400 Cr to Shareholders',
    situation: 'Apex Chemicals Ltd has accumulated ₹820 Cr of cash on its balance sheet. Institutional investors are demanding capital return. The board is considering three options: (1) Special dividend (2) Buyback via tender offer (3) Leveraged recapitalisation (take debt, return cash). You have 45 minutes to recommend.',
    company_overview: 'Apex Chemicals Ltd (listed, market cap ₹6,200 Cr). Revenue FY24: ₹2,400 Cr. EBITDA: ₹480 Cr (20%). PAT: ₹312 Cr. Cash: ₹820 Cr. Zero debt. Promoter holding: 62%. Capital return target: ₹400 Cr. Post-return, company wants to maintain investment-grade rating (requires D/E < 1.5x).',
    financials: {
      headers: ['', 'Special Dividend', 'Buyback (Tender)', 'Leveraged Recap'],
      rows: [
        { label: 'Amount Returned', values: ['₹400 Cr', '₹400 Cr', '₹400 Cr (₹200 cash + ₹200 debt)'] },
        { label: 'Tax on Distribution', values: ['0% (post-DDT abolition)', 'Buyback tax: 23.296%', 'No distribution tax'] },
        { label: 'Tax Cost to Company', values: ['₹0', '₹93 Cr', '₹0'] },
        { label: 'Shareholder Tax', values: ['Dividend income taxed at slab', '₹0 (post-tax already)', 'Capital gains on price'] },
        { label: 'Promoter Impact', values: ['Receives ₹248 Cr → tax at 35.88%', 'Sells shares → dilutes holding', 'No dilution, debt shield'] },
        { label: 'Promoter Tax Liability', values: ['₹89 Cr', '₹0 (if doesn\'t tender)', '₹0 immediate'] },
        { label: 'EPS Impact', values: ['None (same share count)', '+8-12% (fewer shares)', '+15-18% (debt + fewer shares)'] },
        { label: 'Post-Transaction D/E', values: ['0', '0', '~0.4x'] },
      ],
    },
    market_context: 'Post-2020, India abolished Dividend Distribution Tax and shifted to taxing dividends in the hands of recipients. For high-income promoters (35.88% slab), dividends are now very tax-inefficient. Buybacks attract 23.296% buyback tax at the company level.\n\nLeveraged recapitalisation is uncommon in India but standard in the US. The concept: the company borrows ₹200 Cr, adds to ₹200 Cr of cash, and returns ₹400 Cr via buyback or special dividend. The debt creates a tax shield (interest is deductible), and the EPS accretion is amplified because the capital base shrinks while the interest tax shield reduces effective cost.',
    task: '1. Compare all three options on: (a) total tax leakage (company + shareholder combined) (b) EPS impact (c) promoter ownership impact (d) credit rating impact.\n\n2. The buyback appears tax-efficient for shareholders but costs ₹93 Cr in buyback tax. The dividend avoids company-level tax but costs the promoter ₹89 Cr in personal tax. Which option minimises total tax leakage for the promoter-family?\n\n3. Model the leveraged recapitalisation: the company borrows ₹200 Cr at 9%, adds ₹200 Cr of cash, and repurchases shares. Calculate the net EPS accretion including the interest expense and tax shield.\n\n4. The board is risk-averse about taking on debt. Calculate the "break-even interest rate" — at what borrowing cost does the leveraged recap stop being EPS-accretive? Should the board\'s risk aversion change the recommendation?',
    admin_only: {
      strong_response: 'Identifies that the promoter\'s personal tax position drives the decision, not just the company-level analysis. For a promoter at 35.88% marginal rate, dividends cost ₹89 Cr in personal tax. Buyback costs ₹93 Cr at the company level but ₹0 to the promoter (if they don\'t tender). The leveraged recap via buyback is optimal: ₹0 promoter tax + ₹93 Cr buyback tax + interest tax shield of ~₹12.6 Cr/yr. Net cost is lower than dividend, and EPS accretion is highest.',
      critical_gap: 'Analyses only the company-level tax impact without considering the promoter\'s personal tax position. Recommends the dividend because it has "zero company-level tax" without recognising the ₹89 Cr promoter tax liability. Ignores the leveraged recap entirely because "Indian companies shouldn\'t take debt."',
      non_obvious_signal: 'The analysis must be done on a combined basis (company + promoter family). The dividend has ₹0 company tax but ₹89 Cr promoter tax. The buyback has ₹93 Cr company tax but ₹0 promoter tax. The leveraged recap via buyback is the most efficient because the interest tax shield (₹12.6 Cr/yr × multiple years) offsets the buyback tax over time.',
    },
  },
  {
    code: 'CF-014',
    role: 'Corporate Finance',
    difficulty: 'Expert',
    title: 'Distressed Debt Negotiation — When the Promoter\'s Incentives Conflict with Creditor Recovery',
    situation: 'You are advising a consortium of 4 banks (total exposure: ₹680 Cr) on restructuring the debt of Omega Steel Ltd. The company has been in default for 9 months. The promoter is proposing a resolution plan. Your job is to evaluate the plan and identify hidden risks.',
    company_overview: 'Omega Steel Ltd — Integrated steel plant. Revenue FY24: ₹420 Cr (down from ₹780 Cr peak). EBITDA: -₹38 Cr. Total bank debt: ₹680 Cr. Liquidation value of plant: ₹310 Cr. Going-concern value (per independent valuation): ₹520 Cr. Promoter\'s resolution plan: convert ₹200 Cr of debt to equity (at ₹10/share vs current market price ₹4/share), reschedule remaining ₹480 Cr over 10 years at 8% interest, inject ₹30 Cr promoter equity.',
    financials: {
      headers: ['', 'Promoter\'s Plan', 'Bank\'s Counter', 'Your Assessment'],
      rows: [
        { label: 'Debt Write-Off', values: ['₹0 (convert to equity)', '₹200 Cr haircut', '?'] },
        { label: 'Equity Conversion', values: ['₹200 Cr at ₹10/share', 'Not acceptable', '?'] },
        { label: 'Conversion Price vs Market', values: ['₹10 vs ₹4 market', '—', '2.5x premium — why?'] },
        { label: 'Rescheduled Debt', values: ['₹480 Cr / 10 years / 8%', '₹480 Cr / 7 years / 10%', '?'] },
        { label: 'Promoter Equity Infusion', values: ['₹30 Cr', '₹80 Cr minimum', '?'] },
        { label: 'Promoter Post-Restructuring Stake', values: ['68% (maintains control)', '40% (diluted)', '?'] },
        { label: 'NPV of Recoveries (at 12%)', values: ['?', '?', '?'] },
        { label: 'Liquidation Recovery', values: ['₹310 Cr / 45.6%', '₹310 Cr / 45.6%', 'Floor'] },
      ],
    },
    market_context: 'In Indian debt restructuring, the promoter has informational advantage — they know the true condition of the plant, the real order pipeline, and the actual cost of restarting operations. Banks rely on the promoter\'s cooperation for going-concern value but the promoter\'s incentive is to minimise personal contribution and maximise retained equity.\n\nThe conversion price of ₹10/share vs ₹4 market price is suspicious — the promoter benefits because fewer shares are issued to banks for the ₹200 Cr conversion, preserving promoter control. At market price (₹4/share), banks would receive 5 Cr shares (potential majority). At ₹10/share, banks receive only 2 Cr shares (minority).',
    task: '1. Calculate the NPV of bank recoveries under: (a) promoter\'s plan (b) bank\'s counter-proposal (c) liquidation. Use 12% discount rate. Which option maximises bank recovery?\n\n2. The equity conversion at ₹10/share vs ₹4 market price is the key conflict point. Calculate the value transfer: how much value are banks leaving on the table by accepting ₹10 vs ₹4 conversion price? Why does the promoter insist on ₹10?\n\n3. The promoter offers only ₹30 Cr equity infusion on a ₹680 Cr exposure. Banks want ₹80 Cr. The promoter claims they "don\'t have more." How do you verify this claim? What investigation steps would you recommend?\n\n4. Design a restructuring term sheet that aligns promoter and bank incentives. Include: conversion price mechanism, performance milestones with equity dilution triggers, and an exit option if the plan fails.',
    admin_only: {
      strong_response: 'Identifies the conversion price as the most important economic term in the restructuring. At ₹10/share, banks receive 2 Cr shares (minority position). At ₹4/share, banks would receive 5 Cr shares (potentially majority). The ₹6/share difference on ₹200 Cr = ₹120 Cr of value transferred from banks to the promoter. Recommends a "market price or lower" conversion with a ratchet: if the company performs well, the promoter earns back equity through performance milestones.',
      critical_gap: 'Focuses on the interest rate and tenure negotiation (8% vs 10%, 10 years vs 7 years) while missing the conversion price as the dominant economic variable. The interest rate difference is ₹9.6 Cr/year — material but far less than the ₹120 Cr transferred through the conversion price differential. Accepts the ₹10/share conversion without questioning it.',
      non_obvious_signal: 'The conversion price determines who controls the company post-restructuring. At ₹10/share, the promoter retains 68% control. At ₹4/share, banks get majority and can replace management. The promoter\'s insistence on ₹10/share is not about valuation — it\'s about control. The restructuring negotiation is really a control battle disguised as a debt conversation.',
    },
  },
  {
    code: 'CF-015',
    role: 'Corporate Finance',
    difficulty: 'Expert',
    title: 'ESOP Valuation Under Ind AS 102 — When Stock Options Destroy More Value Than They Create',
    situation: 'A listed SaaS company has granted ESOPs to 340 employees. The board wants to understand the full financial impact: P&L charge, dilution, and whether the ESOP programme is actually aligned with shareholder value creation. You have 45 minutes.',
    company_overview: 'CloudServe Technologies Ltd (listed, market cap ₹4,800 Cr). Revenue FY24: ₹800 Cr (+32% YoY). EBITDA: ₹120 Cr (15%). PAT: ₹84 Cr. Shares outstanding: 10 Cr. CMP: ₹480/share. ESOP pool: 8% of outstanding shares (80 lakh options). Vesting: 4-year cliff + graded. Exercise price: ₹100/share (79% discount to CMP). Attrition among ESOP holders: 28% annual.',
    financials: {
      headers: ['', 'Current Grant', 'Ind AS 102 Impact', 'Shareholder Impact'],
      rows: [
        { label: 'Options Granted', values: ['80 lakh', '—', '—'] },
        { label: 'Exercise Price', values: ['₹100/share', '—', '79% discount'] },
        { label: 'Fair Value per Option (B-S model)', values: ['₹320', '—', '—'] },
        { label: 'Total ESOP Cost (Ind AS 102)', values: ['—', '₹256 Cr over 4 years', '₹64 Cr/yr'] },
        { label: 'Annual P&L Charge', values: ['—', '₹64 Cr/yr', '43% of EBITDA'] },
        { label: 'PAT After ESOP Charge', values: ['—', '₹84 - ₹64 = ₹20 Cr', '76% reduction'] },
        { label: 'Dilution (if all exercised)', values: ['80 lakh / 10 Cr', '—', '7.4% dilution'] },
        { label: 'Attrition Adjustment', values: ['28% annual', '~38 lakh vest', '3.8% effective dilution'] },
        { label: 'EPS: Reported vs Diluted', values: ['₹8.4 vs ₹7.8', '₹2.0 vs ₹1.9 (post-ESOP)', '76% EPS decline'] },
      ],
    },
    market_context: 'Ind AS 102 requires companies to recognise stock options at fair value as an employee expense over the vesting period. Many Indian SaaS companies show "adjusted EBITDA" that excludes the ESOP charge — this practice is technically compliant but creates a misleading picture of profitability.\n\nThe valuation model inputs matter enormously. The Black-Scholes model is sensitive to: (1) expected volatility (higher → higher option value → higher P&L charge), (2) expected life (longer → higher value), (3) risk-free rate. Companies have an incentive to use lower volatility and shorter expected life to reduce the P&L charge.',
    task: '1. Calculate the total ESOP cost under Ind AS 102 using Black-Scholes. Show the annual P&L charge over the 4-year vesting period. What is the impact on reported PAT and EPS?\n\n2. The company reports "Adjusted EBITDA" of ₹120 Cr which excludes the ₹64 Cr ESOP charge. If you include the ESOP charge, EBITDA drops to ₹56 Cr and the margin drops from 15% to 7%. At the current market cap of ₹4,800 Cr, what is the implied EV/EBITDA on an adjusted vs real basis?\n\n3. With 28% annual attrition among ESOP holders, approximately 38 of 80 lakh options will actually vest. The remaining 42 lakh options will be forfeited. How does this affect the Ind AS 102 charge? Is the ₹256 Cr total cost overstated?\n\n4. The board asks: "Are our ESOPs creating or destroying shareholder value?" Frame the answer using: (a) value created by employee retention vs (b) value destroyed by dilution + P&L charge. At what attrition rate does the ESOP programme become value-destructive?',
    admin_only: {
      strong_response: 'Identifies the core paradox: 28% attrition means most options will be forfeited, reducing dilution. But under Ind AS 102, the P&L charge is STILL recognised upfront based on estimated vesting — forfeitures are reversed later, creating P&L volatility. The company is recognising ₹64 Cr/year of expense for options that largely won\'t vest. Calculates the true economic cost: only ~38 lakh options vest, creating dilution of ~₹180 Cr (38L × ₹480) but costing employees ₹38 Cr (38L × ₹100). Net value transfer: ₹142 Cr. This must be justified by retention value of the 72% who DON\'T leave.',
      critical_gap: 'Accepts the "Adjusted EBITDA" metric that excludes ESOPs, calling it "standard SaaS practice." Does not calculate the real EV/EBITDA with ESOP costs included (which would show the stock is 2x more expensive than reported). Treats dilution and P&L charge as separate issues rather than connecting them.',
      non_obvious_signal: 'The ESOP programme has a 28% attrition rate — meaning 72% of the value transfer goes to employees who would have stayed anyway. Only the marginal retention effect (employees who would have left WITHOUT ESOPs but stayed BECAUSE of ESOPs) represents value creation. If that marginal effect is less than 15-20% of the pool, the programme destroys shareholder value. The board needs to measure marginal retention, not total retention.',
    },
  },
];

