import type { DealCase } from './types';

export const CF_CASES: DealCase[] = [
  {
    code: 'CF-001',
    role: 'Corporate Finance',
    difficulty: 'Intermediate',
    title: 'Capital Structure Optimisation',
    situation: 'The CFO of a mid-market IT services company has asked you to recommend the optimal capital structure to fund a ₹200 Cr expansion while maintaining investment-grade credit metrics.',
    company_overview: 'CloudForce IT Services Ltd. Revenue FY24: ₹680 Cr. EBITDA: ₹122 Cr (18%). Net debt-free currently. 4,200 employees across 3 delivery centres. Plans to open 2 new centres and expand into BFSI vertical.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['510', '590', '680'] },
        { label: 'EBITDA (₹ Cr)', values: ['87', '104', '122'] },
        { label: 'EBITDA Margin', values: ['17.1%', '17.6%', '18.0%'] },
        { label: 'PAT (₹ Cr)', values: ['62', '74', '88'] },
        { label: 'Cash on Balance Sheet (₹ Cr)', values: ['48', '62', '78'] },
        { label: 'Total Debt (₹ Cr)', values: ['0', '0', '0'] },
        { label: 'ROCE', values: ['22%', '24%', '26%'] },
        { label: 'Current P/E (listed)', values: ['—', '—', '24x'] },
        { label: 'Market Cap (₹ Cr)', values: ['—', '—', '2,112'] },
      ],
    },
    market_context: 'Indian IT services companies typically maintain conservative capital structures. Debt financing available at 9-10% for investment-grade IT companies. Equity dilution at current valuations (24x P/E) is expensive.\n\nRating agencies expect Net Debt/EBITDA < 2.0x for investment-grade in IT services. Tax shield benefit of debt at 25.17% corporate tax rate.',
    task: '1. Compare three funding options: all-debt, all-equity, and optimal mix.\n\n2. Calculate WACC under each scenario.\n\n3. Model the impact on EPS, ROCE, and credit metrics post-expansion.\n\n4. Recommend the optimal capital structure with quantified reasoning.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Calculates the EPS accretion/dilution breakpoint. Shows that at 26% ROCE and 9% cost of debt, debt creates significant EPS accretion vs equity dilution. Recommends 70:30 debt-equity mix that maximises WACC reduction while staying under 2.0x leverage.',
      critical_gap: 'Recommends all-equity because "IT companies should be debt-free" without modelling the cost of equity dilution at 24x P/E.',
      non_obvious_signal: 'At 26% ROCE and 9% cost of debt, the company is destroying value by being debt-free. The tax shield alone justifies moderate leverage. The CFO needs to understand the cost of its current equity-only capital structure.',
    },
  },
  {
    code: 'CF-002',
    role: 'Corporate Finance',
    difficulty: 'Intermediate',
    title: 'Working Capital Financing',
    situation: 'A fast-growing D2C consumer brand is facing a working capital crisis despite strong revenue growth. The CFO needs a financing solution within 30 days.',
    company_overview: 'NaturBlend Foods Pvt Ltd makes healthy snacks sold online and through modern trade. Revenue tripled in 2 years. Currently out of stock on 6 of 14 SKUs due to inability to fund raw material procurement.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['18', '38', '54'] },
        { label: 'Gross Margin', values: ['52%', '50%', '48%'] },
        { label: 'EBITDA (₹ Cr)', values: ['-2.4', '1.2', '4.3'] },
        { label: 'Cash Conversion Cycle (days)', values: ['88', '102', '118'] },
        { label: 'Inventory Days', values: ['42', '58', '72'] },
        { label: 'Receivable Days (Retail/Online)', values: ['38', '44', '52'] },
        { label: 'Payable Days', values: ['-8', '0', '6'] },
        { label: 'Monthly Cash Burn (₹ Cr)', values: ['0.8', '0.4', '0.2'] },
        { label: 'Bank Balance (₹ Cr)', values: ['4.2', '2.8', '1.1'] },
      ],
    },
    market_context: 'Indian healthy snacks market growing 28% CAGR. D2C brands face working capital challenges because: (1) modern trade retailers pay on 45-60 day terms, (2) quick-commerce platforms require inventory pre-positioning, (3) raw material suppliers demand advance payment from small buyers.\n\nRevenue-based financing options (e.g., Velocity, GetVantage) available at 15-18% effective cost. Bank working capital lines available at 12% but require property collateral.',
    task: '1. Diagnose the root cause of the working capital crisis.\n\n2. Calculate the minimum working capital financing required to support ₹80 Cr revenue target.\n\n3. Compare financing options: bank WC line, revenue-based financing, inventory financing, factoring.\n\n4. Recommend the optimal mix of financing and operational improvements.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies that the working capital problem is structural, not temporary — each rupee of revenue growth requires ₹0.32 of working capital (118 CCC days). Revenue growth actually makes the crisis worse without financing.',
      critical_gap: 'Recommends only a financing solution without addressing the operational causes. The 118-day CCC needs structural reduction alongside financing.',
      non_obvious_signal: 'Growth is making the crisis worse, not better. Each rupee of additional revenue requires ₹0.32 of working capital funding. Without both financing AND operational CCC reduction, the company will always be cash-starved.',
    },
  },
  {
    code: 'CF-003',
    role: 'Corporate Finance',
    difficulty: 'Advanced',
    title: 'Transfer Pricing Optimisation',
    situation: 'A multinational\'s India subsidiary is being investigated by transfer pricing authorities. ₹28 Cr of adjustments have been proposed. You must defend the current pricing or recommend restructuring.',
    company_overview: 'GlobalTech India Pvt Ltd is the India subsidiary of a US-listed tech company. Provides software development services to the parent company under a cost-plus arrangement. 2,800 employees in Hyderabad.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue from Parent (₹ Cr)', values: ['340', '380', '420'] },
        { label: 'Cost Base (₹ Cr)', values: ['298', '336', '372'] },
        { label: 'Markup Applied', values: ['14%', '13%', '13%'] },
        { label: 'PBT (₹ Cr)', values: ['42', '44', '48'] },
        { label: 'Proposed TP Adjustment (₹ Cr)', values: ['—', '—', '28'] },
        { label: 'Comparable Companies Markup Range', values: ['14-18%', '15-19%', '16-22%'] },
        { label: 'Tax Authority Proposed Markup', values: ['—', '—', '20%'] },
        { label: 'Employee Cost as % of Total Cost', values: ['74%', '76%', '78%'] },
        { label: 'Parent Company EBITDA Margin', values: ['32%', '31%', '30%'] },
      ],
    },
    market_context: 'Indian transfer pricing regulations follow the arm\'s length principle. The TNMM (Transactional Net Margin Method) is the most common method for IT services companies.\n\nComparable company analysis shows that independent IT services companies earn 16-22% operating margins. The India subsidiary\'s 13% markup falls below the lower quartile, which triggers TP scrutiny.',
    task: '1. Evaluate the TP authority\'s proposed adjustment of ₹28 Cr.\n\n2. Identify the best defence strategies for the current 13% markup.\n\n3. If the current markup is indefensible, recommend a revised transfer pricing policy.\n\n4. Calculate the tax impact of full adjustment vs negotiated settlement.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies that the declining markup (14%→13%) while comparable ranges are increasing (14-18% to 16-22%) creates a pattern that TP authorities will use as evidence of profit shifting. Recommends proactive markup adjustment to 16% to settle within the arm\'s length range.',
      critical_gap: 'Defends the 13% markup without addressing the comparable company analysis showing 16-22% range. Uses aggressive arguments without risk-weighting the litigation outcome.',
      non_obvious_signal: 'The trend is the problem — markup declined from 14% to 13% while the comparable range moved from 14-18% to 16-22%. The widening gap creates a pattern that TP authorities will use as evidence of deliberate profit shifting.',
    },
  },
  {
    code: 'CF-004',
    role: 'Corporate Finance',
    difficulty: 'Advanced',
    title: 'Treasury Risk Management',
    situation: 'The CFO of an export-oriented company has asked you to design a hedging strategy for USD receivables. The company lost ₹14 Cr to FX movements in FY24.',
    company_overview: 'Prism Exports Ltd is a garment exporter. Revenue FY24: ₹480 Cr (72% exports, all USD-denominated). Typical order-to-payment cycle: 90-120 days. No hedging policy currently in place.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['380', '420', '480'] },
        { label: 'Export Revenue (₹ Cr)', values: ['266', '302', '346'] },
        { label: 'EBITDA (₹ Cr)', values: ['42', '46', '43'] },
        { label: 'EBITDA Margin', values: ['11.1%', '11.0%', '9.0%'] },
        { label: 'FX Gain/(Loss) (₹ Cr)', values: ['+4', '-2', '-14'] },
        { label: 'EBITDA ex-FX', values: ['38', '48', '57'] },
        { label: 'Average USD/INR Rate', values: ['74.5', '82.3', '83.1'] },
        { label: 'USD/INR Volatility (annualised)', values: ['4.2%', '6.8%', '3.1%'] },
        { label: 'Forward Premium (3-month annualised)', values: ['3.8%', '4.1%', '3.5%'] },
      ],
    },
    market_context: 'INR/USD has been on a depreciating trend but with increasing volatility. Forward premiums (3-4% annualised) represent the cost of hedging. Options provide downside protection but at higher upfront premium cost.\n\nRBI allows corporates to hedge up to 100% of expected receivables. Natural hedging (matching USD costs with USD revenues) is the most cost-effective strategy but requires structural changes.',
    task: '1. Quantify the FX risk exposure — how much can the company lose in a 5% adverse move?\n\n2. Design a hedging strategy using forwards, options, or a combination.\n\n3. Model the cost of hedging vs the cost of remaining unhedged.\n\n4. Recommend a hedging policy (% of receivables, instruments, tenor).\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Separates the EBITDA impact — underlying EBITDA improved (₹38→57 Cr) but FX losses masked it. Shows that FX is a material risk (₹14 Cr = 24% of EBITDA). Recommends layered hedging: 80% forwards for 0-3 months, 50% options for 3-6 months.',
      critical_gap: 'Recommends 100% forward hedging without calculating the cost (3.5% annualised premium). Or recommends no hedging because "INR is depreciating long-term." Both extremes ignore the risk-reward calculation.',
      non_obvious_signal: 'The company\'s underlying business is actually improving (ex-FX EBITDA grew from ₹38 to ₹57 Cr). FX losses are masking operational improvement. This reframes the problem — the hedging strategy should protect operational gains, not speculate on currency direction.',
    },
  },
  {
    code: 'CF-005',
    role: 'Corporate Finance',
    difficulty: 'Advanced',
    title: 'Dividend Policy Design',
    situation: 'A listed family-owned conglomerate is under investor pressure to formalise its dividend policy. The promoter family wants to maintain control while satisfying institutional investors.',
    company_overview: 'Swaraj Group Ltd (listed, market cap ₹8,400 Cr). Diversified: auto components (48% revenue), textiles (32%), real estate (20%). Promoter holding: 63%. Cash on balance sheet: ₹820 Cr. No dividend paid in last 3 years.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['2,420', '2,680', '2,940'] },
        { label: 'EBITDA (₹ Cr)', values: ['340', '388', '426'] },
        { label: 'PAT (₹ Cr)', values: ['188', '218', '248'] },
        { label: 'Cash on BS (₹ Cr)', values: ['520', '680', '820'] },
        { label: 'Capex (₹ Cr)', values: ['120', '140', '160'] },
        { label: 'Free Cash Flow (₹ Cr)', values: ['148', '168', '188'] },
        { label: 'Dividend Paid', values: ['₹0', '₹0', '₹0'] },
        { label: 'Institutional Investor Holding', values: ['18%', '20%', '22%'] },
        { label: 'Promoter Personal Tax Rate', values: ['—', '—', '35.88%'] },
      ],
    },
    market_context: 'SEBI has recommended that listed companies formalise dividend policies. Institutional investors increasingly voting against boards that hoard cash without clear deployment plans.\n\nPromoter family uses the company\'s cash reserves for diversification — real estate division (20% of revenue) has subpar ROCE (8% vs group average 18%). Institutional investors suspect cross-subsidisation.',
    task: '1. Design a dividend policy that balances promoter control, investor expectations, and growth capital needs.\n\n2. Compare: fixed payout ratio, progressive dividend, residual dividend model.\n\n3. Model the tax impact for different stakeholder groups.\n\n4. Address the institutional investor concern about cash hoarding and real estate cross-subsidisation.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Frames the dividend policy as a governance issue, not just a financial decision. The ₹820 Cr cash pile and the subpar real estate division suggest the promoter is using listed company capital for non-core investments. Recommends linking dividend policy to segment ROCE thresholds.',
      critical_gap: 'Designs a dividend policy purely on financial metrics without addressing the governance concern. Ignores the real estate cross-subsidisation signal.',
      non_obvious_signal: 'The real governance issue is the real estate division — 20% of revenue with 8% ROCE vs 18% group average. Institutional investors suspect the promoter is using listed company cash for personal real estate interests. The dividend policy must address this indirectly.',
    },
  },
  {
    code: 'CF-006',
    role: 'Corporate Finance',
    difficulty: 'Advanced',
    title: 'Debt Refinancing Strategy',
    situation: 'A real estate developer\'s ₹450 Cr debt is coming due in 8 months. Current projects are 60% sold but construction is 40% complete. The CFO needs a refinancing plan.',
    company_overview: 'Pinnacle Realty Developers Ltd. 3 active projects across Pune and Mumbai. Total saleable area: 2.4M sq ft. Sold 60% (1.44M sq ft). Collections received: ₹380 Cr of ₹720 Cr total expected. Construction cost remaining: ₹280 Cr.',
    financials: {
      headers: ['', 'Project Alpha', 'Project Beta', 'Project Gamma'],
      rows: [
        { label: 'Location', values: ['Mumbai Suburbs', 'Pune East', 'Pune West'] },
        { label: 'Total Saleable Area (sq ft)', values: ['800,000', '900,000', '700,000'] },
        { label: 'Sold %', values: ['72%', '58%', '48%'] },
        { label: 'Construction Progress', values: ['55%', '35%', '28%'] },
        { label: 'Expected Revenue (₹ Cr)', values: ['320', '240', '160'] },
        { label: 'Collections Received (₹ Cr)', values: ['180', '120', '80'] },
        { label: 'Remaining Construction Cost (₹ Cr)', values: ['80', '110', '90'] },
        { label: 'Current Debt (₹ Cr)', values: ['180', '160', '110'] },
        { label: 'Debt Maturity', values: ['6 months', '8 months', '10 months'] },
      ],
    },
    market_context: 'Indian real estate debt refinancing market is tight — NBFC liquidity has contracted since the IL&FS crisis. Banks reluctant to lend to developers with delayed projects.\n\nRERA regulations require all customer collections to be deposited in escrow accounts — developer cannot use Project Alpha collections to fund Project Beta construction. This creates project-level funding silos.',
    task: '1. Assess which project(s) can self-fund completion from customer collections.\n\n2. Calculate the net funding gap after accounting for RERA escrow constraints.\n\n3. Compare refinancing options: bank refinance, NBFC construction finance, AIF (Alternative Investment Fund).\n\n4. Recommend a refinancing structure that clears ₹450 Cr of maturing debt.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Models each project\'s cash flow independently due to RERA escrow constraints. Shows that Project Alpha can self-fund but Beta and Gamma cannot — cross-subsidy is not allowed. The funding gap is larger than it appears when RERA constraints are applied.',
      critical_gap: 'Pools all three projects\' cash flows together without considering RERA escrow constraints. Shows a smaller funding gap that is fictitious because the developer cannot actually move cash between projects.',
      non_obvious_signal: 'RERA escrow constraints mean each project must be evaluated independently for cash flow sufficiency. Pooling cash flows across projects is illegal. The funding gap is project-specific, not aggregate — Project Alpha is fine, but Beta and Gamma need external capital.',
    },
  },
  {
    code: 'CF-007',
    role: 'Corporate Finance',
    difficulty: 'Advanced',
    title: 'M&A Integration Planning',
    situation: 'Your company (Monarch Industries, ₹1,200 Cr revenue) just acquired a competitor (VectorTech, ₹480 Cr revenue) for ₹380 Cr. Day 1 of integration begins tomorrow. You are the integration PMO lead.',
    company_overview: 'Acquirer: Monarch Industries Ltd — industrial automation components. Target: VectorTech Pvt Ltd — similar products but serving different OEM customers. 40% customer overlap. 22% product overlap. Two ERP systems (SAP vs Oracle).',
    financials: {
      headers: ['', 'Monarch (Acquirer)', 'VectorTech (Target)', 'Claimed Synergies'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['1,200', '480', '+₹48 Cr (cross-sell)'] },
        { label: 'EBITDA (₹ Cr)', values: ['204', '67', '+₹28 Cr (cost synergies)'] },
        { label: 'Employees', values: ['2,800', '1,100', '-180 (duplicate roles)'] },
        { label: 'Plants', values: ['3', '2', '-1 (consolidation)'] },
        { label: 'ERP System', values: ['SAP S/4HANA', 'Oracle NetSuite', 'SAP migration: ₹12 Cr'] },
        { label: 'Key Customer Overlap', values: ['40%', '40%', 'Revenue risk'] },
        { label: 'Product Overlap', values: ['22%', '22%', 'SKU rationalisation'] },
        { label: 'Management Retention', values: ['—', '3 key leaders identified', 'Retention bonus: ₹4.8 Cr'] },
      ],
    },
    market_context: 'McKinsey research shows 70% of M&A integrations fail to capture planned synergies. The first 100 days determine integration success or failure.\n\nCustomer overlap (40%) creates a revenue dissynergy risk — if the combined entity raises prices or changes account management, customers may shift to competitors. Plant consolidation saves ₹18 Cr annually but takes 18 months and costs ₹8 Cr in one-time expenses.',
    task: '1. Build a 100-day integration plan with specific milestones.\n\n2. Identify which synergies are achievable in Year 1 vs Year 2+.\n\n3. Quantify integration risks — customer attrition, employee turnover, execution delays.\n\n4. Recommend the 3 actions to take in the first 30 days.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Prioritises revenue protection over cost synergy extraction. Identifies customer overlap (40%) as the primary Day-1 risk — competitors will target confused accounts during integration. Recommends customer retention programme before any cost-cutting.',
      critical_gap: 'Leads with cost synergies (headcount reduction, plant consolidation) without first protecting the revenue base. Plans layoffs in Month 1 without considering knowledge transfer or customer relationship continuity.',
      non_obvious_signal: 'Revenue dissynergy risk — the 40% customer overlap means competitors will actively target these accounts during integration disruption. Protecting revenue is more valuable than extracting cost synergies in Year 1.',
    },
  },
];
