import type { DealCase } from './types';

export const ER_CASES: DealCase[] = [
  {
    code: 'ER-001',
    role: 'Equity Research',
    difficulty: 'Intermediate',
    title: 'Initiation of Coverage',
    situation: 'Your research desk has asked you to write an initiation note on a listed FMCG company. Your note must include a price target and a BUY/HOLD/SELL recommendation.',
    company_overview: 'FreshFields Consumer Products Ltd (listed NSE, CMP: ₹842, Market Cap: ₹6,200 Cr). Products: packaged spices, ready-to-cook mixes, organic staples. Distribution: 180,000 retail touch points. Brand NPS: 68.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['620', '724', '838'] },
        { label: 'EBITDA (₹ Cr)', values: ['87', '101', '118'] },
        { label: 'EBITDA Margin', values: ['14.0%', '13.9%', '14.1%'] },
        { label: 'PAT (₹ Cr)', values: ['58', '68', '82'] },
        { label: 'EPS (₹)', values: ['28.4', '33.1', '39.8'] },
        { label: 'P/E (at CMP ₹842)', values: ['—', '—', '21.2x'] },
        { label: 'ROE', values: ['18%', '19%', '20%'] },
        { label: 'Dividend Payout', values: ['22%', '24%', '25%'] },
        { label: 'Ad Spend as % of Revenue', values: ['8.2%', '7.4%', '6.8%'] },
      ],
    },
    market_context: 'Indian packaged foods market growing 18% CAGR. Premium/organic segment growing 32% CAGR. Listed FMCG comparables trade at 35-55x P/E — FreshFields at 21x appears undervalued.\n\nKey risk: declining ad spend (8.2%→6.8% of revenue) may be artificially boosting margins. Competitors are increasing ad spend to capture market share in the fast-growing organic segment.',
    task: '1. Build a DCF valuation with explicit growth and margin assumptions.\n\n2. Cross-verify with comparable company analysis (use 3-5 FMCG peers).\n\n3. Set a 12-month price target and recommend BUY / HOLD / SELL.\n\n4. Identify the 3 key risks to your target price.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies that declining ad spend (8.2%→6.8%) is propping up EBITDA margins. Adjusts future margins assuming normalised ad spend of 8%+ and shows that the apparent margin stability is fragile.',
      critical_gap: 'Values the company at face-value margins without questioning why ad spend is declining while the organic segment is booming. Treats 14.1% EBITDA margin as sustainable without stress-testing.',
      non_obvious_signal: 'Declining ad spend in a growth category is a red flag, not efficiency. Competitors are investing more. If FreshFields needs to increase ad spend to defend share, margins will compress 100-150bps, changing the valuation materially.',
    },
  },
  {
    code: 'ER-002',
    role: 'Equity Research',
    difficulty: 'Intermediate',
    title: 'Quarterly Results Analysis',
    situation: 'A listed bank reported Q3FY25 results last night. The stock is down 6% pre-market. Your desk needs a flash note by 9 AM with a revised target and recommendation.',
    company_overview: 'Saraswat Urban Bank Ltd (listed NSE, CMP: ₹312, Market Cap: ₹9,400 Cr). Mid-size urban bank. 420 branches. Prior to this quarter: consensus EPS estimate was ₹7.2. Reported: ₹5.8.',
    financials: {
      headers: ['', 'Q3FY24', 'Q2FY25', 'Q3FY25'],
      rows: [
        { label: 'NII (₹ Cr)', values: ['680', '728', '710'] },
        { label: 'NIM', values: ['3.42%', '3.38%', '3.18%'] },
        { label: 'Provision (₹ Cr)', values: ['120', '140', '210'] },
        { label: 'GNPA %', values: ['2.1%', '2.3%', '3.1%'] },
        { label: 'NNPA %', values: ['0.8%', '0.9%', '1.4%'] },
        { label: 'Provision Coverage Ratio', values: ['72%', '68%', '62%'] },
        { label: 'Credit Growth YoY', values: ['18%', '16%', '12%'] },
        { label: 'CASA Ratio', values: ['41%', '39%', '37%'] },
        { label: 'ROA', values: ['1.32%', '1.28%', '1.04%'] },
      ],
    },
    market_context: 'Indian banking sector GNPA cycle has been benign for 2 years. This quarter marks a potential inflection — 4 mid-size banks reported higher slippages, suggesting a systemic credit quality deterioration in MSME and unsecured lending.\n\nConsensus expects the credit cycle to peak in FY26 with sector GNPA rising to 3.5%. Banks with GNPA >3% typically trade at 1.0-1.2x book value vs 1.8-2.2x for clean banks.',
    task: '1. Diagnose what went wrong in Q3 — is the miss temporary or structural?\n\n2. Build a revised earnings model (FY25-FY27).\n\n3. Quantify the impact of rising NPAs on provisioning and earnings.\n\n4. Revise your price target and recommendation. Is the 6% drop an overreaction or insufficient?\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies the GNPA acceleration (2.1%→3.1% in 3 quarters) as the key structural concern. Calculates the provision coverage ratio is declining (72%→62%), meaning the bank is under-provisioning relative to slippages. This creates a double risk.',
      critical_gap: 'Calls the miss "one-time" without analysing the NPA trajectory. Treats the EPS miss as a provisioning timing issue rather than a credit quality deterioration signal.',
      non_obvious_signal: 'GNPA is rising AND provision coverage is falling — the bank is not just seeing more bad loans, it is provisioning less per bad loan. This double deterioration means future earnings will be hit by both higher slippages and catch-up provisioning.',
    },
  },
  {
    code: 'ER-003',
    role: 'Equity Research',
    difficulty: 'Advanced',
    title: 'Sector Thematic Report',
    situation: 'Your research head has asked you to write a sector thematic note on Indian Electric Vehicle (EV) supply chain companies. The note should identify 2 investment ideas.',
    company_overview: 'Sector: Indian EV supply chain. Focus: battery components, motor manufacturers, charging infrastructure. India EV penetration: 6.2% (2-wheelers), 2.1% (4-wheelers). Government target: 30% EV sales by 2030.',
    financials: {
      headers: ['', 'Company A (Battery)', 'Company B (Motors)', 'Company C (Charging)'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['480', '340', '120'] },
        { label: 'Revenue Growth YoY', values: ['42%', '28%', '84%'] },
        { label: 'EBITDA Margin', values: ['8.2%', '14.6%', '-12%'] },
        { label: 'P/E (trailing)', values: ['62x', '34x', 'Loss-making'] },
        { label: 'EV/Sales', values: ['4.2x', '2.8x', '8.4x'] },
        { label: 'Capex as % of Revenue', values: ['18%', '12%', '48%'] },
        { label: 'Import Dependency for Raw Materials', values: ['82%', '34%', '12%'] },
        { label: 'Technology Moat', values: ['Low', 'Medium', 'Low'] },
        { label: 'Customer Concentration', values: ['3 OEMs = 78%', '6 OEMs = 64%', '2 CPOs = 88%'] },
      ],
    },
    market_context: 'Indian EV market growing 49% CAGR. But supply chain companies face margin pressure as OEMs demand cost reductions. Battery chemistry is evolving rapidly — LFP replacing NMC, solid-state 3-5 years away. Companies with high import dependency face FX and supply chain risk.\n\nGovernment subsidies (FAME-II, PLI) are propping up unit economics for many EV supply chain companies. When subsidies expire in FY26, profitability will be tested.',
    task: '1. Build an EV supply chain investment framework.\n\n2. Analyse each company across: growth, margins, technology risk, competitive position.\n\n3. Identify 2 top picks with explicit catalysts and risks.\n\n4. Flag the sector-level risk that could derail all 3 companies.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies subsidy dependency as the sector-level risk that masks true unit economics. Separates companies that are profitable ex-subsidy (Company B at 14.6% margin) from those that depend on subsidies (Company C at -12% margin).',
      critical_gap: 'Picks the highest-growth company (Company C at 84% growth) without noting it is loss-making and has 88% customer concentration. Growth without profitability in a subsidy-dependent sector is a value trap.',
      non_obvious_signal: 'Company B (Motors) is the non-obvious pick — lower growth (28%) but profitable (14.6% margin), moderate technology moat, diversified customers (6 OEMs), and low import dependency (34%). It is the only company that survives a subsidy withdrawal scenario.',
    },
  },
  {
    code: 'ER-004',
    role: 'Equity Research',
    difficulty: 'Advanced',
    title: 'Management Guidance Stress-Test',
    situation: 'A listed real estate developer has given aggressive FY25 guidance. Your fund manager has asked you to stress-test the guidance and determine if the stock is a BUY at current levels.',
    company_overview: 'Prestige Habitat Developers Ltd (listed NSE, CMP: ₹1,180, Market Cap: ₹14,200 Cr). Residential projects across Bengaluru, Mumbai, Chennai. Management has guided ₹8,400 Cr pre-sales for FY25 (vs ₹6,200 Cr achieved in FY24).',
    financials: {
      headers: ['', 'FY23', 'FY24', 'FY25 Guidance'],
      rows: [
        { label: 'Pre-Sales (₹ Cr)', values: ['4,800', '6,200', '8,400'] },
        { label: 'Pre-Sales Growth', values: ['—', '29%', '35% guided'] },
        { label: 'Revenue Recognition (₹ Cr)', values: ['3,200', '3,800', '4,800'] },
        { label: 'EBITDA Margin', values: ['24%', '26%', '28% guided'] },
        { label: 'Net Debt (₹ Cr)', values: ['1,800', '2,400', '3,200 projected'] },
        { label: 'New Launches Planned', values: ['4', '6', '9'] },
        { label: 'Unsold Inventory (₹ Cr)', values: ['2,800', '3,400', '—'] },
        { label: 'Construction WIP (₹ Cr)', values: ['4,200', '5,800', '—'] },
        { label: 'Cash from Operations (₹ Cr)', values: ['1,100', '1,400', '—'] },
      ],
    },
    market_context: 'Indian residential real estate in a strong up-cycle — best pre-sales growth in 10 years. But leading indicators suggest momentum may peak in FY25-26. New project launches require 12-18 months of regulatory approvals (RERA, environment clearances).\n\nHistorically, real estate management teams achieve 60-70% of aggressive guidance. Over-guidance is common in up-cycles to support stock price and upcoming fundraising.',
    task: '1. Stress-test the ₹8,400 Cr pre-sales guidance — is 35% growth achievable?\n\n2. Build 3 scenarios: bull (guidance met), base (70% of guidance), bear (50% of guidance).\n\n3. Model the balance sheet impact — how does rising net debt change the risk profile?\n\n4. Set a price target under each scenario and recommend BUY / HOLD / SELL.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies that achieving 9 new launches requires regulatory approvals that typically take 12-18 months. If even 2-3 launches are delayed, the guidance becomes unachievable. Separately models the rising net debt trajectory (₹1,800→₹3,200 Cr) as a balance sheet risk.',
      critical_gap: 'Takes the management guidance at face value and builds a DCF using ₹8,400 Cr pre-sales. Fails to apply the historical achievement rate (60-70%) or analyse new launch execution risk.',
      non_obvious_signal: 'The 9 planned launches are the weakest point in the guidance. Regulatory delays in even 2-3 launches will cause a significant guidance miss. The base case should assume 6-7 launches, not 9, based on historical execution patterns.',
    },
  },
  {
    code: 'ER-005',
    role: 'Equity Research',
    difficulty: 'Advanced',
    title: 'Activist Investor Thesis',
    situation: 'You are preparing a short thesis on a listed company that you believe is overvalued. Your fund uses this for position sizing in a long-short portfolio.',
    company_overview: 'Dazzle Cosmetics Ltd (listed BSE, CMP: ₹1,420, Market Cap: ₹18,500 Cr). Premium cosmetics brand. Celebrity endorsements. Revenue CAGR 38% over 3 years. P/E: 84x trailing. Category: "growth at any price."',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['312', '428', '594'] },
        { label: 'Revenue Growth', values: ['—', '37%', '39%'] },
        { label: 'Gross Margin', values: ['62%', '63%', '64%'] },
        { label: 'EBITDA (₹ Cr)', values: ['28', '38', '52'] },
        { label: 'EBITDA Margin', values: ['9.0%', '8.9%', '8.8%'] },
        { label: 'PAT (₹ Cr)', values: ['14', '19', '22'] },
        { label: 'Influencer Marketing Spend (₹ Cr)', values: ['48', '72', '108'] },
        { label: 'Influencer Spend as % of Revenue', values: ['15.4%', '16.8%', '18.2%'] },
        { label: 'Repeat Purchase Rate', values: ['34%', '31%', '28%'] },
      ],
    },
    market_context: 'Indian premium cosmetics growing 28% CAGR. D2C brands face increasing CAC as the digital advertising market matures. Influencer-driven growth is effective but creates brand fragility — when influencer spend stops, revenue growth typically declines 40-60% within 2 quarters.\n\nComparable D2C cosmetics brands trade at 40-60x P/E. Dazzle at 84x is the most expensive in the sector.',
    task: '1. Build the short thesis — why is this stock overvalued?\n\n2. Quantify the bear case: what happens when influencer spend normalises?\n\n3. Identify the catalyst that would cause a re-rating downward.\n\n4. Calculate the fair value range and potential downside from CMP.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies the declining repeat purchase rate (34%→28%) as the smoking gun. Revenue is growing because influencer spend is growing, not because the brand is building loyalty. Calculates that stripping influencer spend growth, organic revenue growth is only 8-10%.',
      critical_gap: 'Argues the stock is overvalued based only on P/E multiple comparison without identifying the fundamental weakness in the business model. Generic "it\'s expensive" is not a short thesis.',
      non_obvious_signal: 'Revenue is growing 39% but repeat purchase rate is declining (34%→28%). This means the brand is acquiring customers who don\'t return. Strip out the ₹108 Cr influencer spend growth and organic revenue growth is 8-10%, not 39%. This is a paid-growth business masquerading as an organic brand.',
    },
  },
  {
    code: 'ER-006',
    role: 'Equity Research',
    difficulty: 'Advanced',
    title: 'Conglomerate Sum-of-Parts',
    situation: 'Your PM has asked you to value a listed conglomerate using sum-of-the-parts methodology. The conglomerate trades at a 30% holding company discount — your job is to determine if it is justified.',
    company_overview: 'Vanguard Group Ltd (listed NSE, CMP: ₹2,840, Market Cap: ₹32,000 Cr). Holding company with listed and unlisted subsidiaries across IT services, financial services, and infrastructure.',
    financials: {
      headers: ['', 'Subsidiary', 'Holding %', 'Market Value / Est. Value (₹ Cr)'],
      rows: [
        { label: 'Vanguard IT Services (listed)', values: ['IT Services', '61%', '28,000'] },
        { label: 'Vanguard Financial Services (listed)', values: ['NBFC', '72%', '8,400'] },
        { label: 'Vanguard Infrastructure (unlisted)', values: ['Roads/Ports', '100%', '4,200 (est.)'] },
        { label: 'Vanguard Realty (unlisted)', values: ['Real Estate', '100%', '2,800 (est.)'] },
        { label: 'Cross-Holdings + Cash', values: ['Treasury', '—', '1,200'] },
        { label: 'Holdco Debt', values: ['—', '—', '-1,800'] },
        { label: 'Sum of Parts (GAV)', values: ['—', '—', '44,600'] },
        { label: 'NAV (GAV - HoldCo Debt)', values: ['—', '—', '42,800'] },
        { label: 'Current Market Cap', values: ['—', '—', '32,000'] },
      ],
    },
    market_context: 'Indian conglomerates typically trade at 20-40% holding company discounts. The discount reflects governance concerns, capital allocation opacity, and liquidity preference for direct subsidiary investments.\n\nFII investors avoid holdcos due to double-taxation risk and governance concerns. However, some activist investors see deep holdco discounts as value traps that can be unlocked through demergers or buybacks.',
    task: '1. Calculate the sum-of-the-parts NAV.\n\n2. Determine whether the 30% holdco discount is justified, too deep, or too shallow.\n\n3. Identify catalysts that could narrow the discount.\n\n4. Recommend BUY / HOLD / SELL with a 12-month price target.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Questions whether the unlisted subsidiary valuations (₹4,200 Cr infrastructure, ₹2,800 Cr realty) are credible. These are management-provided estimates, not market-verified values. Applies a deeper discount to unlisted assets and separates listed from unlisted NAV.',
      critical_gap: 'Accepts all subsidiary valuations at face value and concludes "30% discount is too deep, BUY." Fails to separately discount unlisted vs listed assets and ignores governance and capital allocation risks.',
      non_obvious_signal: 'The unlisted subsidiaries (₹7,000 Cr combined) are valued using management estimates, not market prices. If these are overvalued by 30-40%, the true NAV could be ₹38,000-40,000 Cr, making the 30% discount largely justified.',
    },
  },
  {
    code: 'ER-007',
    role: 'Equity Research',
    difficulty: 'Advanced',
    title: 'ESG-Integrated Valuation',
    situation: 'Your research desk is launching ESG-integrated coverage. You must demonstrate how ESG factors can be quantified and incorporated into a traditional DCF valuation.',
    company_overview: 'GreenSteel Industries Ltd (listed NSE, CMP: ₹428, Market Cap: ₹11,200 Cr). Steel manufacturer transitioning to green hydrogen-based production. Current carbon emissions: 2.1 tonnes CO2 per tonne of steel (industry average: 1.8 tonnes). Green capex planned: ₹1,200 Cr over 5 years.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['3,800', '4,200', '4,600'] },
        { label: 'EBITDA (₹ Cr)', values: ['684', '756', '828'] },
        { label: 'EBITDA Margin', values: ['18.0%', '18.0%', '18.0%'] },
        { label: 'CO2 per Tonne (tonnes)', values: ['2.3', '2.2', '2.1'] },
        { label: 'Carbon Tax Risk (est. ₹/tonne CO2)', values: ['—', '—', '₹400-800'] },
        { label: 'Annual CO2 Emissions (M tonnes)', values: ['5.2', '5.4', '5.6'] },
        { label: 'Green Capex Planned (₹ Cr, total)', values: ['—', '—', '1,200'] },
        { label: 'EU CBAM Exposure (% exports)', values: ['22%', '24%', '26%'] },
        { label: 'Steel Production (M tonnes)', values: ['2.5', '2.6', '2.7'] },
      ],
    },
    market_context: 'EU Carbon Border Adjustment Mechanism (CBAM) will impose carbon tariffs on Indian steel exports starting 2026. Indian government likely to introduce domestic carbon pricing by 2027-28.\n\nCompanies with lower carbon intensity will gain competitive advantage as carbon costs rise. Green steel commands a 10-15% price premium in EU markets. However, hydrogen-based steel production costs 30-40% more than blast furnace production currently.',
    task: '1. Quantify the carbon cost risk under 3 scenarios (₹400, ₹600, ₹800 per tonne CO2).\n\n2. Model the CBAM impact on export profitability.\n\n3. Build a DCF that incorporates both carbon cost risk and green premium opportunity.\n\n4. Compare: traditional DCF valuation vs ESG-adjusted DCF. What is the valuation impact?\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Models carbon cost as a real cash cost in the DCF, not just a risk factor. At ₹600/tonne CO2, annual carbon cost = ₹336 Cr (5.6M tonnes × ₹600), which is 41% of current EBITDA. This materially changes the valuation.',
      critical_gap: 'Treats ESG as a qualitative overlay ("company has good ESG practices") without quantifying the financial impact of carbon pricing. Fails to incorporate CBAM as a concrete cash flow adjustment.',
      non_obvious_signal: 'Carbon pricing is not a qualitative ESG factor — it is a real cash cost that will hit the P&L. At ₹600/tonne, the annual carbon cost is ₹336 Cr = 41% of EBITDA. This is not a "nice to have" adjustment — it fundamentally changes the valuation.',
    },
  },
];
