import type { DealCase } from './types';

export const ER_CASES: DealCase[] = [
  {
    code: 'ER-001',
    role: 'Equity Research',
    difficulty: 'Intermediate',
    title: 'Initiation of Coverage',
    situation: 'Your research desk has asked you to write an initiation note on a listed FMCG company. Your note must include a price target and a BUY/HOLD/SELL recommendation.',
    company_overview: 'FreshFields Consumer Products Ltd (listed NSE, CMP: ₹842, Market Cap: ₹6,200 Cr). Products: packaged spices, ready-to-cook mixes, organic staples. Distribution: 180,000 retail touch points. Brand NPS: 68.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['620', '724', '838'] },
        { label: 'EBITDA (₹ Cr)', values: ['87', '101', '118'] },
        { label: 'EBITDA Margin', values: ['14.0%', '13.9%', '14.1%'] },
        { label: 'PAT (₹ Cr)', values: ['58', '68', '82'] },
        { label: 'EPS (₹)', values: ['28.4', '33.1', '39.8'] },
        { label: 'P/E (at CMP ₹842)', values: ['—', '—', '21.2x'] },
        { label: 'ROE', values: ['18%', '19%', '20%'] },
        { label: 'Dividend Payout', values: ['22%', '24%', '25%'] },
        { label: 'Ad Spend as % of Revenue', values: ['8.2%', '7.4%', '6.8%'] },
      ],
    },
    market_context: 'Indian packaged foods market growing 18% CAGR. Premium/organic segment growing 32% CAGR. Listed FMCG comparables trade at 35-55x P/E — FreshFields at 21x appears undervalued.\n\nKey risk: declining ad spend (8.2%→6.8% of revenue) may be artificially boosting margins. Competitors are increasing ad spend to capture market share in the fast-growing organic segment.',
    task: '1. Build a DCF valuation with explicit growth and margin assumptions.\n\n2. Cross-verify with comparable company analysis (use 3-5 FMCG peers).\n\n3. Set a 12-month price target and recommend BUY / HOLD / SELL.\n\n4. Identify the 3 key risks to your target price.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies that declining ad spend (8.2%→6.8%) is propping up EBITDA margins. Adjusts future margins assuming normalised ad spend of 8%+ and shows that the apparent margin stability is fragile.',
      critical_gap: 'Values the company at face-value margins without questioning why ad spend is declining while the organic segment is booming. Treats 14.1% EBITDA margin as sustainable without stress-testing.',
      non_obvious_signal: 'Declining ad spend in a growth category is a red flag, not efficiency. Competitors are investing more. If FreshFields needs to increase ad spend to defend share, margins will compress 100-150bps, changing the valuation materially.',
    },
  },
  {
    code: 'ER-002',
    role: 'Equity Research',
    difficulty: 'Intermediate',
    title: 'Quarterly Results Analysis',
    situation: 'A listed bank reported Q3FY25 results last night. The stock is down 6% pre-market. Your desk needs a flash note by 9 AM with a revised target and recommendation.',
    company_overview: 'Saraswat Urban Bank Ltd (listed NSE, CMP: ₹312, Market Cap: ₹9,400 Cr). Mid-size urban bank. 420 branches. Prior to this quarter: consensus EPS estimate was ₹7.2. Reported: ₹5.8.',
    financials: {
      headers: ['', 'Q3FY24', 'Q2FY25', 'Q3FY25'],
      rows: [
        { label: 'NII (₹ Cr)', values: ['680', '728', '710'] },
        { label: 'NIM', values: ['3.42%', '3.38%', '3.18%'] },
        { label: 'Provision (₹ Cr)', values: ['120', '140', '210'] },
        { label: 'GNPA %', values: ['2.1%', '2.3%', '3.1%'] },
        { label: 'NNPA %', values: ['0.8%', '0.9%', '1.4%'] },
        { label: 'Provision Coverage Ratio', values: ['72%', '68%', '62%'] },
        { label: 'Credit Growth YoY', values: ['18%', '16%', '12%'] },
        { label: 'CASA Ratio', values: ['41%', '39%', '37%'] },
        { label: 'ROA', values: ['1.32%', '1.28%', '1.04%'] },
      ],
    },
    market_context: 'Indian banking sector GNPA cycle has been benign for 2 years. This quarter marks a potential inflection — 4 mid-size banks reported higher slippages, suggesting a systemic credit quality deterioration in MSME and unsecured lending.\n\nConsensus expects the credit cycle to peak in FY26 with sector GNPA rising to 3.5%. Banks with GNPA >3% typically trade at 1.0-1.2x book value vs 1.8-2.2x for clean banks.',
    task: '1. Diagnose what went wrong in Q3 — is the miss temporary or structural?\n\n2. Build a revised earnings model (FY25-FY27).\n\n3. Quantify the impact of rising NPAs on provisioning and earnings.\n\n4. Revise your price target and recommendation. Is the 6% drop an overreaction or insufficient?\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies the GNPA acceleration (2.1%→3.1% in 3 quarters) as the key structural concern. Calculates the provision coverage ratio is declining (72%→62%), meaning the bank is under-provisioning relative to slippages. This creates a double risk.',
      critical_gap: 'Calls the miss "one-time" without analysing the NPA trajectory. Treats the EPS miss as a provisioning timing issue rather than a credit quality deterioration signal.',
      non_obvious_signal: 'GNPA is rising AND provision coverage is falling — the bank is not just seeing more bad loans, it is provisioning less per bad loan. This double deterioration means future earnings will be hit by both higher slippages and catch-up provisioning.',
    },
  },
  {
    code: 'ER-003',
    role: 'Equity Research',
    difficulty: 'Advanced',
    title: 'Sector Thematic Report',
    situation: 'Your research head has asked you to write a sector thematic note on Indian Electric Vehicle (EV) supply chain companies. The note should identify 2 investment ideas.',
    company_overview: 'Sector: Indian EV supply chain. Focus: battery components, motor manufacturers, charging infrastructure. India EV penetration: 6.2% (2-wheelers), 2.1% (4-wheelers). Government target: 30% EV sales by 2030.',
    financials: {
      headers: ['', 'Company A (Battery)', 'Company B (Motors)', 'Company C (Charging)'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['480', '340', '120'] },
        { label: 'Revenue Growth YoY', values: ['42%', '28%', '84%'] },
        { label: 'EBITDA Margin', values: ['8.2%', '14.6%', '-12%'] },
        { label: 'P/E (trailing)', values: ['62x', '34x', 'Loss-making'] },
        { label: 'EV/Sales', values: ['4.2x', '2.8x', '8.4x'] },
        { label: 'Capex as % of Revenue', values: ['18%', '12%', '48%'] },
        { label: 'Import Dependency for Raw Materials', values: ['82%', '34%', '12%'] },
        { label: 'Technology Moat', values: ['Low', 'Medium', 'Low'] },
        { label: 'Customer Concentration', values: ['3 OEMs = 78%', '6 OEMs = 64%', '2 CPOs = 88%'] },
      ],
    },
    market_context: 'Indian EV market growing 49% CAGR. But supply chain companies face margin pressure as OEMs demand cost reductions. Battery chemistry is evolving rapidly — LFP replacing NMC, solid-state 3-5 years away. Companies with high import dependency face FX and supply chain risk.\n\nGovernment subsidies (FAME-II, PLI) are propping up unit economics for many EV supply chain companies. When subsidies expire in FY26, profitability will be tested.',
    task: '1. Build an EV supply chain investment framework.\n\n2. Analyse each company across: growth, margins, technology risk, competitive position.\n\n3. Identify 2 top picks with explicit catalysts and risks.\n\n4. Flag the sector-level risk that could derail all 3 companies.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies subsidy dependency as the sector-level risk that masks true unit economics. Separates companies that are profitable ex-subsidy (Company B at 14.6% margin) from those that depend on subsidies (Company C at -12% margin).',
      critical_gap: 'Picks the highest-growth company (Company C at 84% growth) without noting it is loss-making and has 88% customer concentration. Growth without profitability in a subsidy-dependent sector is a value trap.',
      non_obvious_signal: 'Company B (Motors) is the non-obvious pick — lower growth (28%) but profitable (14.6% margin), moderate technology moat, diversified customers (6 OEMs), and low import dependency (34%). It is the only company that survives a subsidy withdrawal scenario.',
    },
  },
  {
    code: 'ER-004',
    role: 'Equity Research',
    difficulty: 'Advanced',
    title: 'Management Guidance Stress-Test',
    situation: 'A listed real estate developer has given aggressive FY25 guidance. Your fund manager has asked you to stress-test the guidance and determine if the stock is a BUY at current levels.',
    company_overview: 'Prestige Habitat Developers Ltd (listed NSE, CMP: ₹1,180, Market Cap: ₹14,200 Cr). Residential projects across Bengaluru, Mumbai, Chennai. Management has guided ₹8,400 Cr pre-sales for FY25 (vs ₹6,200 Cr achieved in FY24).',
    financials: {
      headers: ['', 'FY23', 'FY24', 'FY25 Guidance'],
      rows: [
        { label: 'Pre-Sales (₹ Cr)', values: ['4,800', '6,200', '8,400'] },
        { label: 'Pre-Sales Growth', values: ['—', '29%', '35% guided'] },
        { label: 'Revenue Recognition (₹ Cr)', values: ['3,200', '3,800', '4,800'] },
        { label: 'EBITDA Margin', values: ['24%', '26%', '28% guided'] },
        { label: 'Net Debt (₹ Cr)', values: ['1,800', '2,400', '3,200 projected'] },
        { label: 'New Launches Planned', values: ['4', '6', '9'] },
        { label: 'Unsold Inventory (₹ Cr)', values: ['2,800', '3,400', '—'] },
        { label: 'Construction WIP (₹ Cr)', values: ['4,200', '5,800', '—'] },
        { label: 'Cash from Operations (₹ Cr)', values: ['1,100', '1,400', '—'] },
      ],
    },
    market_context: 'Indian residential real estate in a strong up-cycle — best pre-sales growth in 10 years. But leading indicators suggest momentum may peak in FY25-26. New project launches require 12-18 months of regulatory approvals (RERA, environment clearances).\n\nHistorically, real estate management teams achieve 60-70% of aggressive guidance. Over-guidance is common in up-cycles to support stock price and upcoming fundraising.',
    task: '1. Stress-test the ₹8,400 Cr pre-sales guidance — is 35% growth achievable?\n\n2. Build 3 scenarios: bull (guidance met), base (70% of guidance), bear (50% of guidance).\n\n3. Model the balance sheet impact — how does rising net debt change the risk profile?\n\n4. Set a price target under each scenario and recommend BUY / HOLD / SELL.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies that achieving 9 new launches requires regulatory approvals that typically take 12-18 months. If even 2-3 launches are delayed, the guidance becomes unachievable. Separately models the rising net debt trajectory (₹1,800→₹3,200 Cr) as a balance sheet risk.',
      critical_gap: 'Takes the management guidance at face value and builds a DCF using ₹8,400 Cr pre-sales. Fails to apply the historical achievement rate (60-70%) or analyse new launch execution risk.',
      non_obvious_signal: 'The 9 planned launches are the weakest point in the guidance. Regulatory delays in even 2-3 launches will cause a significant guidance miss. The base case should assume 6-7 launches, not 9, based on historical execution patterns.',
    },
  },
  {
    code: 'ER-005',
    role: 'Equity Research',
    difficulty: 'Advanced',
    title: 'Activist Investor Thesis',
    situation: 'You are preparing a short thesis on a listed company that you believe is overvalued. Your fund uses this for position sizing in a long-short portfolio.',
    company_overview: 'Dazzle Cosmetics Ltd (listed BSE, CMP: ₹1,420, Market Cap: ₹18,500 Cr). Premium cosmetics brand. Celebrity endorsements. Revenue CAGR 38% over 3 years. P/E: 84x trailing. Category: "growth at any price."',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['312', '428', '594'] },
        { label: 'Revenue Growth', values: ['—', '37%', '39%'] },
        { label: 'Gross Margin', values: ['62%', '63%', '64%'] },
        { label: 'EBITDA (₹ Cr)', values: ['28', '38', '52'] },
        { label: 'EBITDA Margin', values: ['9.0%', '8.9%', '8.8%'] },
        { label: 'PAT (₹ Cr)', values: ['14', '19', '22'] },
        { label: 'Influencer Marketing Spend (₹ Cr)', values: ['48', '72', '108'] },
        { label: 'Influencer Spend as % of Revenue', values: ['15.4%', '16.8%', '18.2%'] },
        { label: 'Repeat Purchase Rate', values: ['34%', '31%', '28%'] },
      ],
    },
    market_context: 'Indian premium cosmetics growing 28% CAGR. D2C brands face increasing CAC as the digital advertising market matures. Influencer-driven growth is effective but creates brand fragility — when influencer spend stops, revenue growth typically declines 40-60% within 2 quarters.\n\nComparable D2C cosmetics brands trade at 40-60x P/E. Dazzle at 84x is the most expensive in the sector.',
    task: '1. Build the short thesis — why is this stock overvalued?\n\n2. Quantify the bear case: what happens when influencer spend normalises?\n\n3. Identify the catalyst that would cause a re-rating downward.\n\n4. Calculate the fair value range and potential downside from CMP.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies the declining repeat purchase rate (34%→28%) as the smoking gun. Revenue is growing because influencer spend is growing, not because the brand is building loyalty. Calculates that stripping influencer spend growth, organic revenue growth is only 8-10%.',
      critical_gap: 'Argues the stock is overvalued based only on P/E multiple comparison without identifying the fundamental weakness in the business model. Generic "it\'s expensive" is not a short thesis.',
      non_obvious_signal: 'Revenue is growing 39% but repeat purchase rate is declining (34%→28%). This means the brand is acquiring customers who don\'t return. Strip out the ₹108 Cr influencer spend growth and organic revenue growth is 8-10%, not 39%. This is a paid-growth business masquerading as an organic brand.',
    },
  },
  {
    code: 'ER-006',
    role: 'Equity Research',
    difficulty: 'Advanced',
    title: 'Conglomerate Sum-of-Parts',
    situation: 'Your PM has asked you to value a listed conglomerate using sum-of-the-parts methodology. The conglomerate trades at a 30% holding company discount — your job is to determine if it is justified.',
    company_overview: 'Vanguard Group Ltd (listed NSE, CMP: ₹2,840, Market Cap: ₹32,000 Cr). Holding company with listed and unlisted subsidiaries across IT services, financial services, and infrastructure.',
    financials: {
      headers: ['', 'Subsidiary', 'Holding %', 'Market Value / Est. Value (₹ Cr)'],
      rows: [
        { label: 'Vanguard IT Services (listed)', values: ['IT Services', '61%', '28,000'] },
        { label: 'Vanguard Financial Services (listed)', values: ['NBFC', '72%', '8,400'] },
        { label: 'Vanguard Infrastructure (unlisted)', values: ['Roads/Ports', '100%', '4,200 (est.)'] },
        { label: 'Vanguard Realty (unlisted)', values: ['Real Estate', '100%', '2,800 (est.)'] },
        { label: 'Cross-Holdings + Cash', values: ['Treasury', '—', '1,200'] },
        { label: 'Holdco Debt', values: ['—', '—', '-1,800'] },
        { label: 'Sum of Parts (GAV)', values: ['—', '—', '44,600'] },
        { label: 'NAV (GAV - HoldCo Debt)', values: ['—', '—', '42,800'] },
        { label: 'Current Market Cap', values: ['—', '—', '32,000'] },
      ],
    },
    market_context: 'Indian conglomerates typically trade at 20-40% holding company discounts. The discount reflects governance concerns, capital allocation opacity, and liquidity preference for direct subsidiary investments.\n\nFII investors avoid holdcos due to double-taxation risk and governance concerns. However, some activist investors see deep holdco discounts as value traps that can be unlocked through demergers or buybacks.',
    task: '1. Calculate the sum-of-the-parts NAV.\n\n2. Determine whether the 30% holdco discount is justified, too deep, or too shallow.\n\n3. Identify catalysts that could narrow the discount.\n\n4. Recommend BUY / HOLD / SELL with a 12-month price target.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Questions whether the unlisted subsidiary valuations (₹4,200 Cr infrastructure, ₹2,800 Cr realty) are credible. These are management-provided estimates, not market-verified values. Applies a deeper discount to unlisted assets and separates listed from unlisted NAV.',
      critical_gap: 'Accepts all subsidiary valuations at face value and concludes "30% discount is too deep, BUY." Fails to separately discount unlisted vs listed assets and ignores governance and capital allocation risks.',
      non_obvious_signal: 'The unlisted subsidiaries (₹7,000 Cr combined) are valued using management estimates, not market prices. If these are overvalued by 30-40%, the true NAV could be ₹38,000-40,000 Cr, making the 30% discount largely justified.',
    },
  },
  {
    code: 'ER-007',
    role: 'Equity Research',
    difficulty: 'Advanced',
    title: 'ESG-Integrated Valuation',
    situation: 'Your research desk is launching ESG-integrated coverage. You must demonstrate how ESG factors can be quantified and incorporated into a traditional DCF valuation.',
    company_overview: 'GreenSteel Industries Ltd (listed NSE, CMP: ₹428, Market Cap: ₹11,200 Cr). Steel manufacturer transitioning to green hydrogen-based production. Current carbon emissions: 2.1 tonnes CO2 per tonne of steel (industry average: 1.8 tonnes). Green capex planned: ₹1,200 Cr over 5 years.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['3,800', '4,200', '4,600'] },
        { label: 'EBITDA (₹ Cr)', values: ['684', '756', '828'] },
        { label: 'EBITDA Margin', values: ['18.0%', '18.0%', '18.0%'] },
        { label: 'CO2 per Tonne (tonnes)', values: ['2.3', '2.2', '2.1'] },
        { label: 'Carbon Tax Risk (est. ₹/tonne CO2)', values: ['—', '—', '₹400-800'] },
        { label: 'Annual CO2 Emissions (M tonnes)', values: ['5.2', '5.4', '5.6'] },
        { label: 'Green Capex Planned (₹ Cr, total)', values: ['—', '—', '1,200'] },
        { label: 'EU CBAM Exposure (% exports)', values: ['22%', '24%', '26%'] },
        { label: 'Steel Production (M tonnes)', values: ['2.5', '2.6', '2.7'] },
      ],
    },
    market_context: 'EU Carbon Border Adjustment Mechanism (CBAM) will impose carbon tariffs on Indian steel exports starting 2026. Indian government likely to introduce domestic carbon pricing by 2027-28.\n\nCompanies with lower carbon intensity will gain competitive advantage as carbon costs rise. Green steel commands a 10-15% price premium in EU markets. However, hydrogen-based steel production costs 30-40% more than blast furnace production currently.',
    task: '1. Quantify the carbon cost risk under 3 scenarios (₹400, ₹600, ₹800 per tonne CO2).\n\n2. Model the CBAM impact on export profitability.\n\n3. Build a DCF that incorporates both carbon cost risk and green premium opportunity.\n\n4. Compare: traditional DCF valuation vs ESG-adjusted DCF. What is the valuation impact?\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Models carbon cost as a real cash cost in the DCF, not just a risk factor. At ₹600/tonne CO2, annual carbon cost = ₹336 Cr (5.6M tonnes × ₹600), which is 41% of current EBITDA. This materially changes the valuation.',
      critical_gap: 'Treats ESG as a qualitative overlay ("company has good ESG practices") without quantifying the financial impact of carbon pricing. Fails to incorporate CBAM as a concrete cash flow adjustment.',
      non_obvious_signal: 'Carbon pricing is not a qualitative ESG factor — it is a real cash cost that will hit the P&L. At ₹600/tonne, the annual carbon cost is ₹336 Cr = 41% of EBITDA. This is not a "nice to have" adjustment — it fundamentally changes the valuation.',
    },
  },

  /* ═══════════════════════════════════════════════
     EXPERT CASES — ER-008 through ER-015
     ═══════════════════════════════════════════════ */

  {
    code: 'ER-008',
    role: 'Equity Research',
    difficulty: 'Expert',
    title: 'Forensic Revenue Verification — Channel Stuffing Detection at Prism Consumer',
    situation: 'Your fund manager suspects that Prism Consumer Products Ltd is "channel stuffing" — pushing excess inventory to distributors to inflate reported sales. You have 45 minutes to build the forensic case using publicly available financial data.',
    company_overview: 'Prism Consumer Products Ltd (listed NSE, CMP: ₹680, Market Cap: ₹8,900 Cr). FMCG company — personal care and home cleaning. 4,200 distributors. Revenue FY24: ₹2,400 Cr (+24% YoY). The stock has re-rated from 28x to 42x P/E over 3 years on the back of "consistent above-sector growth." Consensus: BUY, TP ₹820.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24', 'Red Flag?'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['1,560', '1,940', '2,400', '+24% YoY'] },
        { label: 'Revenue Growth', values: ['—', '24%', '24%', 'Suspiciously consistent'] },
        { label: 'Gross Margin', values: ['52%', '51%', '49%', 'Declining ↓'] },
        { label: 'Trade Receivables (₹ Cr)', values: ['186', '262', '384', 'Growing faster than revenue'] },
        { label: 'Receivable Days', values: ['44', '49', '58', 'Expanding rapidly ↑'] },
        { label: 'Industry Avg Receivable Days', values: ['30-35', '30-35', '30-35', 'Prism: 2x industry'] },
        { label: 'Q4 Revenue as % of Annual', values: ['28%', '30%', '33%', 'Hockey-stick pattern'] },
        { label: 'Channel Inventory (months)', values: ['1.8', '2.4', '3.2', 'Building up'] },
        { label: 'Cash from Operations (₹ Cr)', values: ['188', '172', '148', 'DECLINING despite growth'] },
      ],
    },
    market_context: 'Channel stuffing is the practice of pushing excess inventory to distributors — typically through extended credit terms, volume discounts, or right-of-return arrangements — to inflate reported revenue in the current period. The key forensic indicators: (1) receivable days exceeding industry norms, (2) declining cash from operations despite revenue growth, (3) Q4 revenue concentration (year-end push), (4) channel inventory build-up.\n\nPrism\'s receivable days (58) are nearly 2x the industry average (30-35 days). Cash from operations has DECLINED from ₹188 Cr to ₹148 Cr while revenue grew 54%. This divergence is a classic channel stuffing fingerprint.',
    task: '1. Build the forensic case: Identify and quantify all financial indicators that suggest channel stuffing. Calculate what Prism\'s "true" revenue growth would be if receivable days had remained at the FY22 level (44 days).\n\n2. The declining gross margin (52% → 49%) combined with rising receivable days suggests the company is offering price concessions or extended credit to push volume. Calculate the estimated revenue "pulled forward" from future periods.\n\n3. Q4 revenue as a percentage of annual revenue has risen from 28% to 33%. In a normal consumer business, Q4 should be 24-26%. Calculate the Q4 "over-shipment" and what this implies about Q1 of the following year.\n\n4. If your channel stuffing thesis is correct, what will the stock price be after the inevitable revenue correction? Build a bear-case model where: (a) receivable days normalise to industry average (b) channel inventory destocks over 2 quarters (c) revenue growth drops to organic rate.',
    admin_only: {
      strong_response: 'Identifies the cash flow divergence as the strongest evidence: revenue grew 54% (₹1,560 → ₹2,400) but CFO DECLINED 21% (₹188 → ₹148). In a real consumer business, cash should grow proportionally with revenue. The ₹336 Cr gap (₹384 Cr receivables FY24 - ₹186 Cr FY22 = ₹198 Cr incremental receivables) represents revenue that hasn\'t been collected in cash. Calculates that at normalised receivable days (35 days), ₹152 Cr of the ₹384 Cr receivables would not exist — implying ~6-7% of FY24 revenue is "stuffed."',
      critical_gap: 'Relies only on the P/E multiple to argue overvaluation. Does not perform the receivable-vs-revenue divergence analysis. Accepts the 24% revenue growth as genuine because "the company has consistently delivered." Ignores the declining CFO despite top-line growth.',
      non_obvious_signal: 'The most damning signal is not any single metric but the COMBINATION: (1) revenue growing 24% per year — suspiciously consistent, (2) receivable days expanding from 44 to 58, (3) cash from operations declining despite growth. Any one of these could be explained innocently. Together, they form a channel stuffing pattern. The correction, when it comes, will be sudden — a single quarter of -10% revenue "normalisation."',
    },
  },
  {
    code: 'ER-009',
    role: 'Equity Research',
    difficulty: 'Expert',
    title: 'Hidden Cross-Subsidy in Segment Reporting — When Core Business Masks a Value Destroyer',
    situation: 'Your fund is evaluating a position in Titan Electricals Ltd. On the surface, the company has attractive 18% EBITDA margins and consistent growth. Your task is to decompose the segment profitability and determine if the consolidated numbers hide a structural problem.',
    company_overview: 'Titan Electricals Ltd (listed NSE, CMP: ₹1,240, Market Cap: ₹22,000 Cr). Products: Industrial switchgear (65% of revenue), consumer lighting (20%), EV charging (15%). Overall EBITDA margin: 18%. The company reports only one segment ("Electrical Products") in its statutory filings, but provides divisional breakdowns in investor presentations.',
    financials: {
      headers: ['', 'Switchgear (65%)', 'Lighting (20%)', 'EV Charging (15%)', 'Consolidated'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['1,820', '560', '420', '2,800'] },
        { label: 'Revenue Growth', values: ['12%', '8%', '68%', '18%'] },
        { label: 'Gross Margin', values: ['42%', '28%', '14%', '34%'] },
        { label: 'EBITDA Margin', values: ['26%', '12%', '-18%', '18%'] },
        { label: 'EBITDA (₹ Cr)', values: ['473', '67', '-76', '504 (adjusted: +40 unallocated)'] },
        { label: 'Capital Employed (₹ Cr)', values: ['480', '180', '320', '980'] },
        { label: 'ROCE', values: ['98.5%', '37.2%', '-23.8%', '51.4%'] },
        { label: 'Capex FY25 Plan (₹ Cr)', values: ['80', '20', '280', '380'] },
        { label: 'Cumulative Investment (₹ Cr)', values: ['—', '—', '620', '—'] },
      ],
    },
    market_context: 'Single-segment reporting hides cross-subsidies. The Street values Titan at 44x P/E based on consolidated 18% margins. But the EV charging division (-18% EBITDA margin) is destroying ₹76 Cr of value annually. The ₹620 Cr cumulative investment in EV charging has generated zero returns.\n\nThe EV charging market in India has a long path to profitability — utilisation rates are below 15% (breakeven: 25%+). Competitors are also loss-making. The question: is this a strategic investment with long-term value, or a value destroyer that the profitable switchgear business is subsidising?',
    task: '1. Decompose the consolidated financials to reveal divisional profitability. Calculate the "true" valuation of the switchgear business standalone. If switchgear trades at its appropriate multiple (comparable: 35x P/E for industrial electrical companies), what is its standalone value?\n\n2. Value the EV charging division separately. It has invested ₹620 Cr with -18% EBITDA margin. Using comparable EV infrastructure valuations (EV/Sales of 3-5x for loss-making), what is the division worth? Is the ₹620 Cr investment recoverable?\n\n3. Calculate the "conglomerate tax" — how much value is the EV charging division destroying within the consolidated entity? If the company were to demerge or sell the EV charging division, what would the consolidated stock price be?\n\n4. The management argues EV charging will break even by FY27 and generate ₹120 Cr EBITDA by FY29. Build a probability-weighted scenario analysis: (a) management case — breakeven FY27 (b) delayed — breakeven FY29 (c) failure — division shut down. What is the expected value?',
    admin_only: {
      strong_response: 'Calculates the standalone switchgear value: ₹473 Cr EBITDA × 15x EV/EBITDA = ₹7,095 Cr. Add lighting at 10x: ₹670 Cr. Total productive businesses: ₹7,765 Cr. Current EV: ~₹22,500 Cr. The market is assigning ₹14,735 Cr of value to the EV charging division — a division that has ₹420 Cr revenue, -18% EBITDA margin, and ₹620 Cr cumulative losses. This is wildly optimistic unless EV charging achieves extraordinary scale.',
      critical_gap: 'Values the company on consolidated EBITDA of ₹504 Cr without decomposing by division. Applies a single multiple to the consolidated entity. This implicitly assigns the same valuation premium to the loss-making EV charging division as to the highly profitable switchgear business.',
      non_obvious_signal: 'The consolidated 18% EBITDA margin is misleading — it blends a 26% margin business with a -18% margin business. But the real insight is the CAPITAL ALLOCATION: 74% of FY25 capex (₹280/₹380 Cr) is going to the division generating -18% margins and -23.8% ROCE. The switchgear division is funding a value destroyer. The market is rewarding the company for "EV exposure" without pricing the capital destruction.',
    },
  },
  {
    code: 'ER-010',
    role: 'Equity Research',
    difficulty: 'Expert',
    title: 'Reverse DCF — What Expectations Are Embedded in a ₹48,000 Cr Market Cap?',
    situation: 'Your fund manager is considering a short position in NovaStar Technologies Ltd (listed, CMP: ₹2,400, Market Cap: ₹48,000 Cr). The stock trades at 120x trailing P/E. Rather than building a traditional DCF, you must perform a REVERSE DCF to determine what growth assumptions the market is embedding and whether they are achievable.',
    company_overview: 'NovaStar Technologies Ltd — SaaS platform for enterprise workflow automation. Revenue FY24: ₹1,200 Cr (+44% YoY). EBITDA: ₹120 Cr (10% margin). PAT: ₹40 Cr (3.3% margin). Net cash: ₹400 Cr. Customer count: 2,800 enterprises. Net Revenue Retention (NRR): 128%. Customer Acquisition Cost (CAC): ₹18 lakh. LTV: ₹54 lakh. LTV/CAC: 3.0x.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24', 'Implied FY29 (Reverse DCF)'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['580', '834', '1,200', '₹5,800-6,400'] },
        { label: 'Revenue Growth', values: ['—', '44%', '44%', '~35% CAGR implied'] },
        { label: 'EBITDA Margin', values: ['4%', '7%', '10%', '~28-32% implied'] },
        { label: 'PAT (₹ Cr)', values: ['8', '22', '40', '₹1,200-1,400 implied'] },
        { label: 'P/E (trailing)', values: ['—', '—', '120x', '~35x terminal'] },
        { label: 'Enterprise Value (₹ Cr)', values: ['—', '—', '47,600', '—'] },
        { label: 'EV/Revenue', values: ['—', '—', '39.7x', '~8x terminal'] },
        { label: 'NRR', values: ['138%', '132%', '128%', 'Declining trend'] },
        { label: 'Customer Count', values: ['1,200', '1,800', '2,800', '~12,000 implied'] },
      ],
    },
    market_context: 'Reverse DCF reveals the growth and margin assumptions embedded in the current stock price. For NovaStar at ₹48,000 Cr market cap, the implied assumptions are: (1) Revenue must grow at 35%+ CAGR for 5 years to reach ~₹6,000 Cr, (2) EBITDA margins must expand from 10% to 30%+ (a triple), (3) The company must add ~9,200 enterprise customers (from 2,800 to 12,000).\n\nThe Indian enterprise SaaS market has ~15,000 addressable enterprises above the company\'s average deal size. Reaching 12,000 customers implies 80% market penetration — unrealistic without significant TAM expansion or international growth.',
    task: '1. Perform a reverse DCF: given the current market cap of ₹48,000 Cr, WACC of 13%, and terminal growth of 4%, what revenue, EBITDA margin, and PAT must NovaStar achieve by FY29 to justify the current price?\n\n2. Assess feasibility: (a) Can revenue grow at 35% CAGR for 5 years? Use customer count × ARPU analysis. (b) Can EBITDA margins expand from 10% to 30%? What is the benchmark for Indian SaaS companies at scale? (c) The NRR is declining (138% → 128%) — what does this signal about future growth quality?\n\n3. The declining NRR is the most important metric in this case. If NRR drops below 120%, revenue growth decelerates mechanically even without losing customers. Model the revenue impact of NRR declining to 115% by FY26.\n\n4. Build the short thesis: at what stock price does the risk/reward favour a short? What is the catalyst that could trigger a re-rating? What is the maximum loss risk if the bull case materialises?',
    admin_only: {
      strong_response: 'The reverse DCF reveals impossible embedded expectations: reaching 12,000 enterprise customers in a TAM of 15,000 implies 80% penetration. No enterprise SaaS company globally has achieved this in a single geography. More critically, identifies the declining NRR (138% → 128%) as a leading indicator of growth deceleration. NRR declining below 120% would cut revenue growth from 44% to ~20-25% even with the same customer acquisition rate. At 20% growth, the stock is worth ₹12,000-15,000 Cr — 65-70% downside.',
      critical_gap: 'Performs the reverse DCF mechanically but does not assess the feasibility of the implied assumptions. States that "₹6,000 Cr revenue is needed by FY29" without questioning whether 12,000 enterprise customers are achievable in a 15,000-enterprise TAM. Ignores the declining NRR trend.',
      non_obvious_signal: 'The declining NRR (138% → 128%) is more important than the revenue growth rate. NRR above 130% means existing customers are expanding rapidly — this drives growth without new customer acquisition costs. As NRR drops below 120%, the company must acquire MORE customers just to maintain the same growth rate, increasing CAC and compressing margins. The growth-at-all-costs machine starts breaking down.',
    },
  },
  {
    code: 'ER-011',
    role: 'Equity Research',
    difficulty: 'Expert',
    title: 'Credit Cycle Timing — When to Go Long Banks After an NPA Peak',
    situation: 'Indian banking sector GNPA peaked at 11.2% in FY18 and has been declining for 6 years (current: 2.8%). Four mid-size banks reported rising slippages in Q3FY25. Your research head wants a sector note: "Is the credit cycle turning? When should we go underweight banks?"',
    company_overview: 'Sector analysis across 12 listed Indian banks. You must identify which banks are most vulnerable to a credit cycle upturn and which are positioned to outperform. Focus on the divergence between headline GNPA and leading indicators.',
    financials: {
      headers: ['', 'Clean Banks (Top 5)', 'Vulnerable Banks (Bottom 5)', 'System Average'],
      rows: [
        { label: 'GNPA %', values: ['1.4-2.0%', '3.2-4.8%', '2.8%'] },
        { label: 'NNPA %', values: ['0.3-0.5%', '1.2-2.1%', '0.9%'] },
        { label: 'Provision Coverage', values: ['78-85%', '55-62%', '68%'] },
        { label: 'SMA-1 + SMA-2 %', values: ['1.2-1.8%', '3.4-5.2%', '2.4%'] },
        { label: 'Restructured Book %', values: ['0.8-1.2%', '2.8-4.1%', '1.8%'] },
        { label: 'Unsecured Loan Mix', values: ['12-18%', '22-34%', '20%'] },
        { label: 'Credit Cost (bps)', values: ['40-60', '110-180', '85'] },
        { label: 'P/BV', values: ['2.8-3.5x', '0.8-1.2x', '1.8x'] },
        { label: 'ROA', values: ['1.6-2.0%', '0.8-1.1%', '1.3%'] },
      ],
    },
    market_context: 'Credit cycles in Indian banking follow a predictable pattern: (1) benign period — low NPAs, aggressive lending, loosened underwriting (2) stress emergence — SMA accounts rise, restructuring increases (3) NPA peak — slippages spike, provisioning compresses earnings (4) recovery — write-backs boost earnings, stocks re-rate.\n\nThe key leading indicator is SMA-1 + SMA-2 (Special Mention Accounts) — loans 31-90 days past due. This is the "early warning" that appears 6-12 months before GNPA rises. The vulnerable banks show SMA-1+2 of 3.4-5.2% vs 1.2-1.8% for clean banks. This divergence has historically preceded GNPA inflection by 3-4 quarters.',
    task: '1. Build a credit cycle framework for Indian banks. Where are we in the cycle? Use SMA-1+2 data, restructured book size, and unsecured loan mix as leading indicators.\n\n2. The SMA-1+2 data shows a clear divergence: vulnerable banks at 3.4-5.2% vs clean banks at 1.2-1.8%. If 40-50% of SMA accounts slip to NPA (historical conversion rate), what will GNPA look like in 4 quarters? Model the earnings impact.\n\n3. The vulnerable banks trade at 0.8-1.2x book value. Is this already pricing in the credit cycle turn? Calculate the implied NPA and credit cost assumptions in the current valuations. Are the stocks cheap or still expensive for what\'s coming?\n\n4. Design a long-short banking portfolio: long the 3 cleanest banks, short the 3 most vulnerable. Calculate the expected return spread over 12 months under your credit cycle thesis.',
    admin_only: {
      strong_response: 'Identifies SMA-1+2 as the leading indicator that matters most. At 3.4-5.2% for vulnerable banks, applying a 40-50% slippage rate implies GNPA will rise to 5.0-7.5% over the next 4 quarters. This would require credit costs of 200-300 bps, compressing ROA below 0.5% — which means these banks become value traps despite appearing "cheap" at 0.8-1.2x book. The short thesis works because the bad news hasn\'t fully hit GNPA yet — the market sees 3.2-4.8% GNPA but the SMA pipeline says 5.0-7.5% is coming.',
      critical_gap: 'Focuses only on current GNPA levels without examining SMA pipeline and restructured book. Concludes that vulnerable banks at 0.8-1.2x book are "value buys" because "Indian banking NPAs always cycle back." This ignores that the SMA data signals more pain ahead, and these valuations may not yet reflect the full cycle turn.',
      non_obvious_signal: 'The GNPA number is a LAGGING indicator — it tells you about loans that already went bad 6-12 months ago. The SMA-1+2 is the LEADING indicator — it tells you what GNPA will be 3-4 quarters from now. The divergence between SMA (high and rising for vulnerable banks) and GNPA (still reported at manageable levels) creates a false sense of security in the market.',
    },
  },
  {
    code: 'ER-012',
    role: 'Equity Research',
    difficulty: 'Expert',
    title: 'SOTP with Embedded Options — Valuing a Conglomerate\'s Unlisted Fintech Subsidiary',
    situation: 'Heritage Group Holdings (listed, CMP: ₹1,850, Market Cap: ₹38,000 Cr) owns a fast-growing unlisted fintech subsidiary. The Street is struggling to value this subsidiary. Your note must determine whether the conglomerate discount adequately prices the fintech optionality.',
    company_overview: 'Heritage Group Holdings — Holding company. Listed subsidiaries: Heritage FMCG (62% stake, market cap ₹44,000 Cr), Heritage Chemicals (71% stake, market cap ₹12,000 Cr). Unlisted subsidiary: Heritage Digital Payments (100%, a UPI-based payment platform). Heritage Digital: TPV ₹8.4 lakh Cr/year, 180M monthly active users, Revenue ₹340 Cr, EBITDA: -₹180 Cr (loss-making, investing in growth). Comparable: Paytm (listed at 8-10x revenue when profitable).',
    financials: {
      headers: ['', 'Heritage FMCG', 'Heritage Chemicals', 'Heritage Digital (Unlisted)', 'Total'],
      rows: [
        { label: 'Stake %', values: ['62%', '71%', '100%', '—'] },
        { label: 'Subsidiary Market Cap/Est Value', values: ['₹44,000 Cr', '₹12,000 Cr', '?', '—'] },
        { label: 'Proportionate Value', values: ['₹27,280 Cr', '₹8,520 Cr', '?', '—'] },
        { label: 'Revenue', values: ['₹18,000 Cr', '₹4,200 Cr', '₹340 Cr', '—'] },
        { label: 'EBITDA', values: ['₹3,600 Cr', '₹840 Cr', '-₹180 Cr', '—'] },
        { label: 'Revenue Growth', values: ['14%', '8%', '120%', '—'] },
        { label: 'Holdco Debt', values: ['—', '—', '—', '₹2,400 Cr'] },
        { label: 'Listed Sub Proportionate Value', values: ['—', '—', '—', '₹35,800 Cr'] },
        { label: 'Current Holdco Market Cap', values: ['—', '—', '—', '₹38,000 Cr'] },
      ],
    },
    market_context: 'The holdco market cap is ₹38,000 Cr. Listed subsidiary proportionate value is ₹35,800 Cr. Net of holdco debt (₹2,400 Cr), the listed NAV = ₹33,400 Cr. This means the market is assigning only ₹4,600 Cr to Heritage Digital — implying a valuation of ~13.5x revenue for a company growing at 120% YoY with 180M MAUs.\n\nHowever, fintech valuations are binary: if Heritage Digital achieves profitability and lists, it could be worth ₹15,000-25,000 Cr (comparable to Paytm at 8-10x revenue on ₹340 Cr+ revenue). If it fails to monetise, it\'s worth near-zero. The holdco needs to be valued with embedded optionality.',
    task: '1. Calculate the SOTP NAV of Heritage Group. What is the implied valuation the market assigns to Heritage Digital? Is ₹4,600 Cr (13.5x revenue) fair for a loss-making fintech growing at 120%?\n\n2. Heritage Digital is loss-making today. Value it using three approaches: (a) Revenue multiple from comparable fintechs (b) Option pricing model — treat it as a call option on a profitable fintech (c) Probability-weighted scenario: 60% chance of successful IPO at ₹20,000 Cr in 3 years, 40% chance of shutdown.\n\n3. The typical holdco discount for Indian conglomerates is 25-35%. Heritage currently trades at ~₹38,000 Cr vs listed NAV of ₹33,400 Cr + ₹4,600 Cr fintech = ₹38,000 Cr — effectively zero discount. Is the market pricing Heritage Digital too aggressively or too conservatively?\n\n4. Design an investment thesis: under what conditions is Heritage Group a BUY? What specific milestones at Heritage Digital would cause a re-rating? What is the downside if Heritage Digital fails?',
    admin_only: {
      strong_response: 'Identifies that Heritage is trading at zero holdco discount when it should trade at 25-30%. This means either: (a) Heritage Digital is undervalued (the market should assign MORE than ₹4,600 Cr), or (b) the holdco premium is unjustified and the stock is overvalued. Uses the option pricing framework: Heritage Digital as a call option — the "strike price" is the breakeven investment needed (₹500 Cr more to reach profitability), the "underlying asset" is a profitable fintech worth ₹15,000-25,000 Cr. The option value depends on time to profitability and probability of success.',
      critical_gap: 'Applies a simple revenue multiple (8-10x) to Heritage Digital without adjusting for: (a) the company is loss-making, (b) there is no certainty it will ever be profitable, (c) comparable fintech valuations have compressed 60-70% from peak. Uses 2021 fintech multiples rather than current market conditions.',
      non_obvious_signal: 'The zero holdco discount is the key puzzle. Either Heritage Digital is worth significantly more than ₹4,600 Cr (bull case: the market hasn\'t caught up to the fintech optionality) OR the holdco should trade at a 25-30% discount and the stock is 20-30% overvalued (bear case: the fintech is correctly valued but the holdco premium is wrong). The answer depends entirely on your conviction about Heritage Digital\'s path to profitability.',
    },
  },
  {
    code: 'ER-013',
    role: 'Equity Research',
    difficulty: 'Expert',
    title: 'Promoter Pledge Cascade — When Margin Calls Destroy Equity Value',
    situation: 'A listed company\'s promoter has pledged 48% of their shares to fund personal ventures. The stock has declined 22% in the last 3 months, approaching the lender\'s margin call trigger. You need to assess the downside risk and determine whether this creates a forced selling cascade.',
    company_overview: 'Zenith Industries Ltd (listed BSE/NSE, CMP: ₹320, Market Cap: ₹6,400 Cr). Diversified industrial conglomerate. The business is fundamentally sound: Revenue ₹2,800 Cr, EBITDA ₹504 Cr (18%), zero corporate debt. However, the PROMOTER has personally pledged 48% of their 58% stake (approximately 27.8% of total shares outstanding) to borrow ₹820 Cr for personal real estate investments.',
    financials: {
      headers: ['', 'Current', 'At Margin Call', 'Post-Forced Sale'],
      rows: [
        { label: 'CMP', values: ['₹320', '₹280 (trigger)', '₹180-220 (estimated)'] },
        { label: 'Market Cap (₹ Cr)', values: ['6,400', '5,600', '3,600-4,400'] },
        { label: 'Promoter Holding', values: ['58%', '58%', '40-48% (diluted)'] },
        { label: 'Shares Pledged', values: ['48% of promoter holding', '48%', 'Sold by lender'] },
        { label: 'Pledged Shares as % of Total', values: ['27.8%', '27.8%', 'Market overhang'] },
        { label: 'Pledge Loan Amount', values: ['₹820 Cr', '₹820 Cr', '₹820 Cr'] },
        { label: 'LTV (Loan to Value)', values: ['46% (₹820/₹1,779)', '52% (approaching limit)', '65%+ (breach)'] },
        { label: 'Lender Margin Call Trigger', values: ['LTV > 55%', 'At ₹280/share', '—'] },
        { label: 'Daily Avg Trading Volume (₹ Cr)', values: ['₹12 Cr', '—', 'Cannot absorb ₹820 Cr'] },
      ],
    },
    market_context: 'Promoter share pledging is one of the most dangerous risks in Indian equities. When a pledged stock declines below the lender\'s LTV threshold, the lender issues a margin call. If the promoter cannot provide additional collateral or cash (usually they can\'t — they pledged because they needed cash), the lender sells the shares in the open market.\n\nThe forced sale creates a vicious cycle: selling pressure → stock price decline → lower LTV → more margin calls → more forced selling. In India, this cascade has destroyed 50-80% of market cap in several cases (Zee Entertainment, Future Group, DHFL). The daily trading volume of ₹12 Cr means the market cannot absorb a ₹820 Cr forced sale without catastrophic price impact.',
    task: '1. Calculate the exact stock price at which the lender triggers a margin call. If the LTV limit is 55%, at what share price does the lender act? How much price decline from CMP does this represent?\n\n2. If the margin call is triggered and the lender begins selling: the pledged shares are worth ~₹1,779 Cr at CMP (27.8% of ₹6,400 Cr). Daily trading volume is ₹12 Cr. Calculate how many trading days it would take to liquidate the pledged shares. What price impact would this create?\n\n3. Model the cascade scenario: (a) Stock hits ₹280 → margin call triggered (b) Lender begins selling → stock falls to ₹240 → more selling pressure (c) Other investors panic-sell → stock falls to ₹180-200. Calculate total market cap destruction and recovery timeline.\n\n4. Is there a price at which the stock becomes a BUY despite the pledge risk? Calculate the "margin of safety" price — where the stock\'s fundamental value (based on business DCF) provides enough upside to compensate for the pledge overhang risk.',
    admin_only: {
      strong_response: 'Calculates the margin call trigger precisely: at 55% LTV, the share price trigger is ₹820 Cr / (27.8% × 20 Cr shares × 0.55) = ~₹298/share (only 7% below CMP). The stock is dangerously close to the trigger. More importantly, identifies that the daily trading volume (₹12 Cr) means liquidating ₹1,779 Cr of pledged shares would take 148 trading days if volume remains constant — but volume will spike and price will collapse simultaneously. The realistic forced liquidation scenario suggests the stock could fall to ₹180-220 (a 30-45% decline from CMP).',
      critical_gap: 'Dismisses the pledge risk because "the underlying business is fundamentally sound." The business may be sound but the stock price is governed by the forced sale dynamics, not fundamentals. Fails to calculate the market\'s ability to absorb ₹1,779 Cr of forced selling against ₹12 Cr daily volume.',
      non_obvious_signal: 'The stock is only 7% above the margin call trigger (₹298 vs ₹320 CMP). This means ANY negative catalyst — even unrelated to the company — could trigger the cascade. The risk is not about fundamentals; it\'s about market microstructure. A fundamentally sound company can lose 40-50% of market cap purely because of promoter pledge mechanics. The business DCF is irrelevant until the pledge overhang is resolved.',
    },
  },
  {
    code: 'ER-014',
    role: 'Equity Research',
    difficulty: 'Expert',
    title: 'Working Capital Manipulation — Revenue Is Growing But Cash Is Disappearing',
    situation: 'Your fund holds a ₹400 Cr position in Sterling Engineering Ltd. The stock has doubled in 18 months on the back of 30%+ order inflow growth. But a forensic review of the balance sheet reveals alarming working capital trends. You have 45 minutes to determine if this is a red flag or benign.',
    company_overview: 'Sterling Engineering Ltd (listed NSE, CMP: ₹840, Market Cap: ₹16,800 Cr). EPC contractor — water infrastructure, industrial piping. Order book: ₹12,400 Cr (4.2x trailing revenue). Revenue FY24: ₹2,960 Cr (+32% YoY). EBITDA: ₹340 Cr (11.5%). The concern: working capital has ballooned from ₹380 Cr to ₹920 Cr in 3 years despite revenue growing "only" 80%.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24', 'Trend'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['1,640', '2,240', '2,960', '+80% (3-year)'] },
        { label: 'EBITDA (₹ Cr)', values: ['180', '252', '340', 'Growing'] },
        { label: 'PAT (₹ Cr)', values: ['98', '142', '198', 'Growing'] },
        { label: 'CFO (₹ Cr)', values: ['124', '86', '42', 'COLLAPSING ↓↓'] },
        { label: 'Working Capital (₹ Cr)', values: ['380', '620', '920', '+142% (3-year)'] },
        { label: 'WC as % of Revenue', values: ['23.2%', '27.7%', '31.1%', 'Expanding ↑'] },
        { label: 'Unbilled Revenue (₹ Cr)', values: ['84', '168', '312', '+271% ↑↑'] },
        { label: 'Unbilled as % of Revenue', values: ['5.1%', '7.5%', '10.5%', 'Accelerating'] },
        { label: 'Retention Money (₹ Cr)', values: ['42', '78', '134', 'Growing fast'] },
        { label: 'Vendor Financing (₹ Cr)', values: ['0', '48', '124', 'New line item'] },
      ],
    },
    market_context: 'In EPC companies, working capital quality is as important as earnings quality. Key items to watch: (1) Unbilled revenue — work completed but not yet billed to the client. Rising unbilled revenue can mean the company is recognising revenue before the client has certified the work. (2) Retention money — amounts withheld by clients until project completion. (3) Vendor financing — the company is "financing" subcontractors through its own balance sheet.\n\nSterling\'s unbilled revenue has grown from 5.1% to 10.5% of revenue — meaning an increasing proportion of "revenue" hasn\'t been billed to or acknowledged by the client. This is the single most dangerous line item in an EPC company\'s balance sheet.',
    task: '1. Analyse the working capital deterioration: revenue grew 80% but working capital grew 142%. Decompose the ₹540 Cr increase (₹380 → ₹920 Cr) by component: receivables, unbilled revenue, retention money, inventory, payables, vendor financing.\n\n2. Unbilled revenue grew 271% vs revenue growth of 80%. This is the most alarming metric. Calculate what the company\'s revenue would have been if unbilled revenue as a percentage of revenue had remained at FY22 levels (5.1%). Is the company "manufacturing" revenue through aggressive unbilled recognition?\n\n3. Vendor financing appeared as a new line item in FY23 (₹48 Cr) and grew to ₹124 Cr in FY24. This is when the company finances subcontractors upfront and recognises the revenue. How does vendor financing inflate both revenue and margins? What is the true EBITDA if vendor financing revenue is excluded?\n\n4. CFO has collapsed from ₹124 Cr to ₹42 Cr while PAT doubled. This divergence is the classic warning signal. Calculate free cash flow and determine: is this company actually generating cash or just reporting accounting profits?',
    admin_only: {
      strong_response: 'Identifies the unbilled revenue explosion as the primary red flag: if unbilled as % of revenue had stayed at 5.1% (FY22 level), FY24 unbilled would be ₹151 Cr, not ₹312 Cr. The ₹161 Cr excess unbilled is revenue that exists on the P&L but hasn\'t been confirmed by clients. This means ₹161 Cr of FY24 revenue (5.4%) may not be "real" in the cash sense. Combined with vendor financing of ₹124 Cr, up to ₹285 Cr of revenue and corresponding margins could be inflated. True EBITDA may be ₹255-280 Cr, not ₹340 Cr.',
      critical_gap: 'Accepts the PAT growth at face value and ignores the CFO collapse. States that "working capital intensity is normal for EPC companies" without benchmarking against peers. Does not investigate unbilled revenue or vendor financing separately.',
      non_obvious_signal: 'The vendor financing line item (₹0 → ₹124 Cr in 2 years) is the most suspicious addition. In vendor financing, the company pays subcontractors upfront and bills the client later — this inflates revenue (the company records the full value, not just its margin) and inflates working capital simultaneously. It explains both the revenue growth AND the cash flow deterioration. Remove vendor financing, and revenue growth drops from 32% to ~22% and EBITDA margin drops from 11.5% to ~9.5%.',
    },
  },
  {
    code: 'ER-015',
    role: 'Equity Research',
    difficulty: 'Expert',
    title: 'Relative Valuation Trap — When "Cheap vs Peers" Masks Structural Margin Compression',
    situation: 'An Indian pharma company trades at 14x P/E — significantly below the sector average of 28x. A buy-side analyst at your fund is recommending a large position, arguing "it\'s the cheapest large-cap pharma." Your job is to determine whether this is a genuine value opportunity or a value trap.',
    company_overview: 'AuroMed Pharma Ltd (listed NSE, CMP: ₹540, Market Cap: ₹24,000 Cr). Revenue FY24: ₹8,200 Cr. EBITDA: ₹1,640 Cr (20%). PAT: ₹1,040 Cr. P/E: 14x (sector average: 28x). US formulations: 52% of revenue. India formulations: 30%. API/CRAMS: 18%.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24', 'FY25E (Your Model)'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['7,400', '7,800', '8,200', '?'] },
        { label: 'US Formulations Revenue', values: ['₹4,440 (60%)', '₹4,290 (55%)', '₹4,264 (52%)', 'Declining share'] },
        { label: 'US Gross Margin', values: ['62%', '54%', '48%', 'Compressing ↓↓'] },
        { label: 'US Price Erosion (annual)', values: ['-8%', '-12%', '-18%', 'Accelerating'] },
        { label: 'ANDA Pipeline', values: ['42 pending', '38 pending', '32 pending', 'Depleting'] },
        { label: 'India Formulations Growth', values: ['14%', '12%', '11%', 'Decelerating'] },
        { label: 'Consolidated EBITDA Margin', values: ['24%', '22%', '20%', '16-18%?'] },
        { label: 'R&D Spend (₹ Cr)', values: ['620', '580', '540', 'DECLINING'] },
        { label: 'R&D as % of Revenue', values: ['8.4%', '7.4%', '6.6%', 'Underinvesting'] },
        { label: 'Debt (₹ Cr)', values: ['1,200', '1,400', '1,800', 'Rising ↑'] },
      ],
    },
    market_context: 'Indian generic pharma companies dependent on US formulations face structural headwinds: (1) US FDA price erosion for generics has accelerated to 15-20% annually for commoditised molecules, (2) ANDA (drug approval) pipeline depletion — new approvals are taking longer and targeting smaller markets, (3) biosimilars require 3-5x the investment of traditional generics.\n\nThe "cheap vs peers" argument ignores why the stock is cheap. The pharma sector P/E of 28x applies to companies with growing US pipelines and stable margins. AuroMed\'s US margins are compressing at 600bps/year, and its ANDA pipeline is depleting without adequate R&D reinvestment.',
    task: '1. Is 14x P/E cheap or appropriate? Build a model that explains why the market is assigning a 50% discount to sector average. Identify the 3 structural issues that justify the discount.\n\n2. US formulations gross margin has compressed from 62% to 48% in 3 years (-600bps/year). Model the trajectory: if price erosion continues at 18% annually and no new product launches replace the volume, what does US formulations profitability look like in FY26-FY27?\n\n3. R&D spend has declined from 8.4% to 6.6% of revenue — the company is underinvesting in its future pipeline to maintain current-period earnings. Calculate the long-term impact: if the ANDA pipeline depletes to <20 products without renewal, what is the terminal revenue for the US business?\n\n4. The buy-side analyst argues "mean reversion to sector P/E of 28x would give 100% upside." Disprove this argument by showing that margin compression means earnings will decline EVEN IF the P/E re-rates. Calculate the stock price under: (a) current margins, 28x P/E (b) compressed margins, 14x P/E (c) compressed margins, 28x P/E.',
    admin_only: {
      strong_response: 'Disproves the mean-reversion argument mathematically: even at 28x P/E, if EBITDA margin compresses from 20% to 16% (FY26E), PAT drops to ₹680-720 Cr. At 28x × ₹680 Cr = ₹19,040 Cr market cap = ₹428/share — 20% DOWNSIDE from CMP despite a P/E RE-RATING. The "cheap" P/E is a trap because earnings are declining. Shows that R&D underinvestment (6.6% vs sector 10-12%) means the ANDA pipeline will deplete, making margin compression permanent, not cyclical.',
      critical_gap: 'Uses current earnings (₹1,040 Cr PAT) and applies the sector P/E (28x) to get a ₹29,120 Cr target — a classic beginner mistake. This ignores that earnings are declining, margins are compressing, and the pipeline is depleting. A re-rated P/E on declining earnings can still produce a lower stock price.',
      non_obvious_signal: 'R&D spend declining from 8.4% to 6.6% is the most important long-term signal. The company is cannibalising its future to maintain current earnings. In pharma, the ANDA pipeline IS the business — each generic drug has a finite lifecycle (5-7 years of competitive returns). Without new ANDAs, revenue naturally declines. The company is "harvesting" its pipeline — a rational strategy if you\'re planning to sell, but a value trap for new investors.',
    },
  },
];

