import type { DealCase } from './types';

export const IB_CASES: DealCase[] = [
  {
    code: 'IB-001',
    role: 'Investment Banking Analyst',
    difficulty: 'Intermediate',
    title: 'Manufacturing Acquisition',
    situation: 'Your managing director has asked you to evaluate Meridian Auto Components Pvt Ltd for a potential acquisition by a mid-market private equity fund targeting ₹50-500 Cr revenue manufacturing companies. You have 45 minutes to complete your analysis and present a recommendation.',
    company_overview: 'Meridian Auto Components is a Pune-based manufacturer of precision-engineered components for passenger vehicles and commercial trucks. Founded 2008. Supplies 3 major OEMs — 78% of total revenue. 340 employees. 2 manufacturing facilities.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue', values: ['187', '214', '231'] },
        { label: 'COGS', values: ['128', '151', '168'] },
        { label: 'Gross Profit', values: ['59', '63', '63'] },
        { label: 'EBITDA', values: ['38', '41', '38'] },
        { label: 'Depreciation', values: ['12', '14', '15'] },
        { label: 'EBIT', values: ['26', '27', '23'] },
        { label: 'Interest', values: ['8', '9', '11'] },
        { label: 'PBT', values: ['18', '18', '12'] },
        { label: 'Tax', values: ['5', '5', '3'] },
        { label: 'PAT', values: ['13', '13', '9'] },
        { label: 'Total Assets', values: ['210', '238', '261'] },
        { label: 'Total Debt', values: ['82', '94', '108'] },
        { label: 'Equity', values: ['128', '144', '153'] },
        { label: 'Capex', values: ['18', '22', '24'] },
        { label: 'WC Days', values: ['67', '71', '79'] },
      ],
    },
    market_context: 'Indian auto components industry grew 12% in FY24. EV transition creates 5-10 year demand uncertainty for ICE components. Meridian has no EV development program.\n\nInterest rates rose 150bps since FY22. Company refinanced ₹40Cr debt in FY24.',
    task: '1. VALUATION\nEstimate a valuation range using at least one methodology. Show working. State all assumptions.\n\n2. RISK ASSESSMENT\nIdentify top 3 risks. For each: explain the mechanism and suggest one mitigation.\n\n3. INVESTMENT RECOMMENDATION\nProceed / Proceed with Conditions / Pass. Defend your thesis in 150-200 words.\n\nNote: No single correct answer exists. We evaluate thinking quality, not a specific output.',
    admin_only: {
      strong_response: 'Identifies gross margin stagnation (₹63Cr flat FY23-FY24 despite revenue growth), connects rising debt with capex cycle, and flags EV transition as existential risk with a timeline estimate.',
      critical_gap: 'Uses only revenue multiples without questioning margin sustainability. Ignores working capital deterioration (67→79 days). Gives generic risk list without quantification.',
      non_obvious_signal: 'Customer concentration risk (78% from 3 OEMs) combined with zero EV capability means the company faces both customer dependency AND technology obsolescence simultaneously.',
    },
  },
  {
    code: 'IB-002',
    role: 'Investment Banking Analyst',
    difficulty: 'Intermediate',
    title: 'Consumer Brand Acquisition',
    situation: 'Your MD at a mid-market IB boutique has asked you to evaluate a potential acquisition of a D2C skincare brand by a large FMCG strategic buyer. You have 45 minutes to complete your analysis.',
    company_overview: 'Lumière Skin Co. is an India-based D2C skincare brand founded in 2019. Sells through own website and quick-commerce platforms. Products: 14 SKUs across serums, moisturisers, and SPF. Average order value ₹1,400. Repeat purchase rate 38%. Customer acquisition cost ₹680. Total equity raised: ₹42 Cr across 3 rounds. Last round valuation: ₹280 Cr (Series B, 2023). Strategic buyer is Hindustan Beauté Ltd — ₹4,200 Cr revenue FMCG company seeking premium skincare entry.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['28', '61', '89'] },
        { label: 'Gross Margin', values: ['61%', '63%', '64%'] },
        { label: 'EBITDA', values: ['-8.4', '-4.2', '6.2'] },
        { label: 'EBITDA Margin', values: ['-30%', '-6.9%', '7%'] },
        { label: 'CAC (₹)', values: ['520', '640', '680'] },
        { label: 'Repeat Purchase Rate', values: ['31%', '35%', '38%'] },
        { label: 'AOV (₹)', values: ['1,180', '1,320', '1,400'] },
        { label: 'Monthly Cash Burn (₹ Cr)', values: ['1.8', '1.1', 'Breakeven Q3'] },
        { label: 'Total Equity Raised (₹ Cr)', values: ['12', '28', '42'] },
      ],
    },
    market_context: 'Indian skincare market growing 22% CAGR. D2C consolidation accelerating as unit economics normalise post-COVID growth. Large FMCG companies acquiring premium D2C brands to access younger demographics.\n\nQuick-commerce platforms (Blinkit, Zepto) becoming primary discovery channel, reducing CAC for some brands but increasing platform dependency.',
    task: '1. Advise on acquisition rationale — why should Hindustan Beauté Ltd acquire Lumière?\n\n2. Build a valuation range using revenue multiples and DCF. Justify your multiple selection.\n\n3. Assess synergy potential — distribution, brand portfolio, cost savings. Quantify where possible.\n\n4. Identify top 3 deal risks and recommend whether HBL should proceed.\n\nState all assumptions explicitly.',
    admin_only: {
      strong_response: 'Identifies that CAC is rising (₹520→₹680) while repeat rate improvement (31%→38%) is not fast enough to offset it. Calculates CAC payback period and flags unit economics sustainability.',
      critical_gap: 'Values the brand purely on revenue multiples without questioning whether ₹680 CAC is sustainable at scale. Treats the ₹280 Cr Series B valuation as an anchor without independent analysis.',
      non_obvious_signal: 'CAC trend vs repeat rate — is the brand building genuine loyalty or acquiring increasingly expensive customers? The CAC payback period is the key metric that determines whether this is a real brand or a marketing-subsidised business.',
    },
  },
  {
    code: 'IB-003',
    role: 'Investment Banking Analyst',
    difficulty: 'Advanced',
    title: 'Tech Company IPO Readiness',
    situation: 'Your VP has asked you to assess whether a SaaS company is ready for an IPO within 18 months and at what valuation range. You have 45 minutes to deliver your assessment.',
    company_overview: 'TaskFlow Technologies Pvt Ltd is a B2B SaaS project management platform based in Bengaluru. Founded 2018. Targets mid-market Indian enterprises. 340 employees. 280 paying enterprise accounts.',
    financials: {
      headers: ['', 'FY23', 'FY24'],
      rows: [
        { label: 'ARR (₹ Cr)', values: ['66', '94'] },
        { label: 'ARR Growth YoY', values: ['67%', '41%'] },
        { label: 'Net Revenue Retention', values: ['122%', '118%'] },
        { label: 'Gross Margin', values: ['73%', '71%'] },
        { label: 'Sales Efficiency (CAC/ACV months)', values: ['12', '14'] },
        { label: 'Annual Churn', values: ['6%', '8%'] },
        { label: 'EBITDA (₹ Cr)', values: ['-22', '-31'] },
        { label: 'Cash Runway (months)', values: ['34', '22'] },
        { label: 'Headcount', values: ['260', '340'] },
      ],
    },
    market_context: 'Indian SaaS IPO market reopened in 2024 after 2022-23 correction. Public market SaaS comps trading at 6-9x forward ARR. US-listed Indian SaaS companies command 15-20% premium.\n\nGrowth deceleration across the sector is a key concern for public market investors — companies trading at 8x+ ARR need to demonstrate path to profitability or sustained 40%+ growth.',
    task: '1. Assess IPO readiness across financial, operational, and governance dimensions.\n\n2. Recommend optimal timing — IPO now, in 12 months, or in 18 months? Why?\n\n3. Build a valuation range using ARR multiples and DCF.\n\n4. Identify the three most critical milestones before IPO filing.\n\nState all assumptions explicitly.',
    admin_only: {
      strong_response: 'Flags growth deceleration (67%→41%) as the primary investor concern and connects it to deteriorating sales efficiency (12→14 month CAC payback) and rising churn (6%→8%). Recommends re-accelerating growth OR demonstrating profitability path before IPO.',
      critical_gap: 'Applies a generic SaaS multiple without adjusting for growth deceleration. Treats 41% growth as "strong" without comparing to the 67% prior year or explaining the deceleration.',
      non_obvious_signal: 'Growth deceleration from 67% to 41% — is this market saturation, sales capacity constraint, or product-market fit degradation? The answer determines whether the company IPOs at 8x ARR or 5x ARR.',
    },
  },
  {
    code: 'IB-004',
    role: 'Investment Banking Analyst',
    difficulty: 'Advanced',
    title: 'Distressed Debt Restructuring',
    situation: 'Your MD is advising the lender consortium of a hotel chain that has defaulted on ₹380 Cr of term debt. You must evaluate restructuring options within 45 minutes.',
    company_overview: 'Suryavanshi Hospitality Ltd is an 18-hotel chain across Tier 1 and Tier 2 Indian cities. Founded 1998. Mix of 7 owned and 11 leased properties.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['310', '428', '389'] },
        { label: 'EBITDA (₹ Cr)', values: ['56', '73', '47'] },
        { label: 'EBITDA Margin', values: ['18.1%', '17.1%', '12.1%'] },
        { label: 'Interest Expense (₹ Cr)', values: ['42', '52', '62'] },
        { label: 'Debt Outstanding (₹ Cr)', values: ['320', '350', '380'] },
        { label: 'Asset Value — Owned Properties (₹ Cr)', values: ['480', '500', '520'] },
        { label: 'Occupancy Rate', values: ['68%', '74%', '61%'] },
        { label: 'RevPAR (₹)', values: ['4,200', '5,100', '3,800'] },
        { label: 'No. of Lenders', values: ['4', '4', '4'] },
      ],
    },
    market_context: 'Indian hospitality sector is recovering post-COVID but facing new supply in Tier 1 markets. Budget and mid-market segments seeing 15-20% new room supply in FY24-25, compressing occupancy rates for existing players.\n\nRBI guidelines on debt restructuring allow one-time restructuring for operational stress without NPA classification, provided lenders agree within 180 days of default.',
    task: '1. Evaluate three restructuring paths:\n   a) Debt-for-equity swap\n   b) Asset sale and leaseback (owned properties)\n   c) Operational turnaround with debt extension\n\n2. Quantify expected lender recovery under each path.\n\n3. Recommend which path maximises lender recovery.\n\n4. State all assumptions.',
    admin_only: {
      strong_response: 'Identifies that asset value (₹520 Cr) exceeds debt (₹380 Cr) — this is a solvency problem, not an insolvency problem. The real issue is operational underperformance, not inability to repay if assets are realised.',
      critical_gap: 'Treats this as a pure insolvency case and recommends immediate liquidation without recognising the asset cover. Fails to separate owned vs leased property economics.',
      non_obvious_signal: 'Asset value exceeds debt — the company is solvent on a balance sheet basis. The problem is cash flow, not net worth. Strong candidates will identify that lender recovery is highest under operational turnaround (preserves going concern value) rather than fire sale.',
    },
  },
  {
    code: 'IB-005',
    role: 'Investment Banking Analyst',
    difficulty: 'Advanced',
    title: 'Cross-Border M&A Advisory',
    situation: 'Your firm is advising Indus Pharmaceuticals Ltd (₹8,200 Cr revenue, listed on NSE, ₹620 Cr net cash) on acquiring Hoffmann Spezialchemie GmbH, a German specialty pharma excipients manufacturer.',
    company_overview: 'Hoffmann Spezialchemie GmbH is a Munich-based specialty pharma excipients manufacturer. Founded 1962. Family-owned, second generation. 180 employees. 3 proprietary excipients with EU regulatory approval. Customer concentration: Top 3 customers = 61% of revenue (all EU pharma majors).',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (€M)', values: ['41', '44', '47'] },
        { label: 'EBITDA (€M)', values: ['9.4', '10.2', '11.2'] },
        { label: 'EBITDA Margin', values: ['22.9%', '23.2%', '23.8%'] },
        { label: 'EBIT (€M)', values: ['7.6', '8.1', '8.9'] },
        { label: 'Net Debt (€M)', values: ['15', '13', '12'] },
        { label: 'Employees', values: ['175', '178', '180'] },
        { label: 'Synergies Claimed (€M NPV)', values: ['—', '—', '18'] },
      ],
    },
    market_context: 'Indian pharma companies are acquiring European specialty suppliers to secure API and excipient supply chains post-COVID. Three Indian pharma deals in EU specialty chemicals closed in FY23-24 at 10-14x EBITDA.\n\nGerman family businesses face succession challenges — 40% of Mittelstand companies have no identified successor. Regulatory approval for pharma-adjacent acquisitions takes 6-12 months in EU.',
    task: '1. Validate the acquisition rationale for Indus Pharmaceuticals.\n\n2. Build a cross-border valuation (INR/EUR). Apply appropriate multiples.\n\n3. Assess synergy credibility — are the €18M NPV synergies achievable?\n\n4. Identify the top 3 deal execution risks specific to a cross-border family business acquisition.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies key-man risk as the primary due diligence gap — the 3 proprietary excipients may depend on founder knowledge not documented in any process. Also flags cross-border integration complexity and FX risk on deal economics.',
      critical_gap: 'Focuses only on financial metrics and ignores the family business dynamics. Applies Indian pharma multiples to a German company without adjusting for market differences.',
      non_obvious_signal: 'Family business second generation — key man risk. The proprietary excipients may depend on founder knowledge not documented in any process. This is the primary due diligence gap that determines whether the acquisition value survives the transition.',
    },
  },
  {
    code: 'IB-006',
    role: 'Investment Banking Analyst',
    difficulty: 'Advanced',
    title: 'Leveraged Buyout Candidate',
    situation: 'A PE fund client has asked your firm to run a sell-side process for a packaging manufacturer. Your job is to prepare the investment thesis for potential LBO buyers.',
    company_overview: 'Packstar Industries Pvt Ltd is a Pune-based rigid plastic packaging manufacturer. Founded 2003. Customers: FMCG, pharma, and food companies. Long-term supply agreements with 4 anchor customers (avg 6-year tenure).',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['298', '318', '340'] },
        { label: 'EBITDA (₹ Cr)', values: ['59', '66.8', '72'] },
        { label: 'EBITDA Margin', values: ['19.8%', '21.0%', '21.2%'] },
        { label: 'Capex (₹ Cr)', values: ['25', '28', '30'] },
        { label: 'Capex as % of Revenue', values: ['8.4%', '8.8%', '8.8%'] },
        { label: 'Free Cash Flow (₹ Cr)', values: ['28', '31', '34'] },
        { label: 'Working Capital Days', values: ['48', '44', '45'] },
        { label: 'Gross Block (₹ Cr)', values: ['240', '260', '280'] },
        { label: 'Existing Debt (₹ Cr)', values: ['52', '48', '45'] },
      ],
    },
    market_context: 'Packaging sector trading at 10-14x EBITDA for quality assets. PE interest in manufacturing buyouts increasing as India becomes a global supply chain alternative.\n\nPlastic packaging faces ESG scrutiny — regulatory risk around single-use plastic bans. However, rigid packaging for pharma and food is exempt from most regulations.',
    task: '1. Build the LBO investment thesis.\n\n2. Model entry at 12x EBITDA. Assume 60% debt financing at 11% interest.\n\n3. Project whether a 25%+ IRR is achievable at exit multiples of 10-14x over a 5-year hold.\n\n4. Identify value creation levers and the key risk to the thesis.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Calculates FCF conversion (FCF/EBITDA = 47%) and identifies that capex intensity creates a cash flow problem in an LBO. Shows that debt paydown is slower than EBITDA suggests because maintenance capex consumes ~42% of EBITDA.',
      critical_gap: 'Uses EBITDA as a proxy for cash flow without calculating FCF conversion. Shows attractive IRRs that ignore the capex reality of an equipment-intensive business.',
      non_obvious_signal: 'Capex intensity (8-9% of revenue) means FCF conversion is weak despite strong EBITDA margins. EBITDA looks great but free cash flow tells the real story for an LBO — debt paydown capacity is much lower than headline numbers suggest.',
    },
  },
  {
    code: 'IB-007',
    role: 'Investment Banking Analyst',
    difficulty: 'Advanced',
    title: 'Rights Issue Advisory',
    situation: 'A listed infrastructure company needs to raise ₹1,200 Cr equity to fund a highway project and has asked your firm to advise on the optimal capital raise structure.',
    company_overview: 'Bharat Infracon Ltd is listed on BSE with a market cap of ₹3,400 Cr. Infrastructure developer — highways, bridges, and port logistics. Promoter holding: 52.3% (post-dilution floor: must stay above 51% for control).',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['1,520', '1,680', '1,840'] },
        { label: 'EBITDA (₹ Cr)', values: ['342', '378', '410'] },
        { label: 'Net Debt (₹ Cr)', values: ['1,680', '1,890', '2,100'] },
        { label: 'Net Debt/EBITDA', values: ['4.9x', '5.0x', '5.1x'] },
        { label: 'Interest Coverage', values: ['3.1x', '2.9x', '2.8x'] },
        { label: 'Share Price (₹)', values: ['—', '—', '184'] },
        { label: 'P/E (trailing)', values: ['—', '—', '18x'] },
        { label: 'Promoter Holding', values: ['54.1%', '53.2%', '52.3%'] },
        { label: 'HAM Project Pipeline (₹ Cr)', values: ['—', '—', '4,800'] },
      ],
    },
    market_context: 'Indian infrastructure sector receiving strong government capex support. HAM (Hybrid Annuity Model) highway projects require 40% equity from the developer and 60% from NHAI. Project pipeline is strong but capital-intensive.\n\nSEBI regulations require promoter holding disclosure for capital raise structures. QIP allows up to 25% dilution; rights issue has no cap but requires promoter participation proportionately.',
    task: '1. Compare three capital raise structures: Rights Issue vs QIP vs Preferential Allotment.\n\n2. Calculate dilution impact under each option.\n\n3. Model the promoter holding post-dilution — ensure it stays above 51%.\n\n4. Recommend the structure that raises ₹1,200 Cr while preserving promoter control and minimising minority dilution.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Calculates maximum dilutable shares backward from the 51% floor (52.3% current → 1.3% dilution headroom = ~24 Cr shares maximum). Then tests each option against this constraint before evaluating economics.',
      critical_gap: 'Recommends a capital raise structure without checking the promoter control floor. Suggests QIP or preferential allotment without calculating whether the dilution breaches 51%.',
      non_obvious_signal: 'Promoter control floor creates a hard constraint on dilution quantum. The math must work backward from 51% before running the numbers on each option — not forward from the amount to be raised.',
    },
  },

  /* ═══════════════════════════════════════════════
     EXPERT CASES — IB-008 through IB-015
     Final-round interview calibre cases
     ═══════════════════════════════════════════════ */

  {
    code: 'IB-008',
    role: 'Investment Banking Analyst',
    difficulty: 'Expert',
    title: 'Hostile Takeover Defence — Defending Shreshtha Pharma',
    situation: 'Your MD at a mid-market investment bank has been engaged by the Board of Shreshtha Pharma to defend against a hostile takeover bid from Apex Healthcare. Apex has launched a public offer at ₹284 per share — a 34% premium to the 3-month VWAP. The Shreshtha Board believes the offer significantly undervalues the company. You have 45 minutes to assess the defence options.',
    company_overview: 'Shreshtha Pharma Ltd — Specialty generics manufacturer. Listed on NSE. Founded 1991. Revenue FY24: ₹2,840 Cr. EBITDA FY24: ₹512 Cr (18% margin). PAT FY24: ₹298 Cr. Net Cash: ₹180 Cr (debt-free). Shares outstanding: 42 Cr. Current offer price: ₹284/share. Pre-bid price: ₹212/share. Market cap at bid: ₹11,928 Cr. EV at bid price: ₹11,748 Cr. EV/EBITDA at bid: 22.9x. Pipeline: 3 USFDA approvals pending (results expected 12-18 months). Promoter holding: 38% (cannot participate in defence buyback). Institutional holding: 41%. Bidder: Apex Healthcare Ltd — ₹8,400 Cr revenue strategic acquirer. Offer funded: 60% cash, 40% Apex shares. Apex share price volatile, down 18% in last 6 months.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['2,210', '2,540', '2,840'] },
        { label: 'EBITDA (₹ Cr)', values: ['398', '457', '512'] },
        { label: 'EBITDA Margin', values: ['18.0%', '18.0%', '18.0%'] },
        { label: 'PAT (₹ Cr)', values: ['231', '267', '298'] },
        { label: 'Net Cash (₹ Cr)', values: ['120', '150', '180'] },
        { label: 'EV/EBITDA at Bid', values: ['—', '—', '22.9x'] },
        { label: 'USFDA Pipeline Revenue Potential', values: ['—', '—', '₹400-600 Cr/yr'] },
        { label: 'Apex Offer Consideration', values: ['—', '—', '60% cash + 40% stock'] },
        { label: 'Apex Share Price Change (6M)', values: ['—', '—', '-18%'] },
      ],
    },
    market_context: 'Specialty pharma M&A multiples in India: 18-28x EBITDA for quality assets. A comparable transaction closed at 26x EBITDA 4 months ago. USFDA pending approvals represent potential revenue upside of ₹400-600 Cr annually if all three are granted.\n\nApex has a history of integrating acquisitions poorly — two prior targets saw EBITDA margins decline 400bps post-acquisition. The mixed consideration (60% cash + 40% Apex stock) must be evaluated against Apex\'s declining share price.',
    task: '1. Calculate standalone intrinsic value of Shreshtha using DCF and comparable multiples. Include the pipeline optionality value explicitly. Determine whether ₹284 undervalues the company.\n\n2. Evaluate four defence mechanisms: (a) White Knight search (b) Pac-Man counter-bid on Apex (c) Share buyback to support price (d) Litigation to delay — For each: feasibility, cost, and effectiveness.\n\n3. Advise the Board on which combination of defences to deploy in the next 72 hours and over the next 30 days.\n\n4. Identify the one scenario in which the Board should recommend shareholders accept the offer rather than fight it.',
    admin_only: {
      strong_response: 'Immediately disaggregates the offer into cash and stock components and revalues the effective offer price. With Apex stock down 18%, the effective value is approximately ₹268-271, not ₹284 headline. Quantifies USFDA pipeline optionality using probability-weighted scenario analysis. Connects the mixed consideration discount with pipeline optionality to build a two-pronged argument for rejection.',
      critical_gap: 'Focuses entirely on standalone DCF and misses that the real argument is the mixed consideration discount and the pipeline optionality. Failing to quantify USFDA optionality specifically — treating it as generic "upside" rather than modelling probability-weighted revenue scenarios. Ignores Apex\'s poor integration track record as Board-level ammunition.',
      non_obvious_signal: 'The mixed consideration (60% cash + 40% Apex stock) is the defence team\'s strongest weapon. If Apex stock is down 18%, the effective value of the offer is lower than ₹284 headline — approximately ₹268-271 depending on Apex\'s trajectory. This mirrors the standard Goldman/Morgan Stanley M&A final round question: "Walk me through how you\'d advise a target Board facing a hostile bid."',
    },
  },
  {
    code: 'IB-009',
    role: 'Investment Banking Analyst',
    difficulty: 'Expert',
    title: 'Dual-Track Process — Nirvana Consumer Brands: IPO or Strategic Sale?',
    situation: 'Your team is advising Nirvana Consumer Brands, a private FMCG company, on whether to pursue an IPO or accept an acquisition offer from a strategic buyer. The promoter wants maximum value and full exit within 18 months. Your MD needs a dual-track recommendation within the hour.',
    company_overview: 'Nirvana Consumer Brands Pvt Ltd — Premium ethnic food and beverages. Founded 2016. D2C and quick-commerce. Revenue FY24: ₹287 Cr (45% growth). EBITDA FY24: ₹38 Cr (13.2% margin). PAT FY24: ₹21 Cr. Total equity raised: ₹180 Cr. Last round (Series C 2023): ₹380 Cr post-money. Net cash: ₹42 Cr. SKU count: 48 across 6 categories. Customer retention (12-month): 41%. Gross margin: 58%. Strategic offer: Hindustan Foods Conglomerate (₹14,000 Cr revenue) has submitted a non-binding offer at 4.2x FY24 revenue = ₹1,205 Cr EV. All-cash, 90-day exclusivity requested.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['124', '198', '287'] },
        { label: 'Revenue Growth', values: ['—', '60%', '45%'] },
        { label: 'Gross Margin', values: ['56%', '57%', '58%'] },
        { label: 'EBITDA (₹ Cr)', values: ['8', '22', '38'] },
        { label: 'EBITDA Margin', values: ['6.5%', '11.1%', '13.2%'] },
        { label: 'PAT (₹ Cr)', values: ['2', '12', '21'] },
        { label: 'Customer Retention (12-mo)', values: ['36%', '39%', '41%'] },
        { label: 'Strategic Offer (EV)', values: ['—', '—', '₹1,205 Cr'] },
        { label: 'IPO Estimated Valuation', values: ['—', '—', '₹1,800-2,200 Cr'] },
      ],
    },
    market_context: 'Indian consumer sector IPOs FY24: Average revenue multiple 6-8x for high-growth brands. Listing-day premiums: 28% average for profitable consumer companies. Lock-up: 6-month promoter lock-up post-IPO. SEBI profitability requirement met — company is profitable. Investment banker estimated IPO valuation: ₹1,800-2,200 Cr.\n\nCategory average 12-month customer retention is 58%. Nirvana\'s 41% is significantly below benchmark. Quick-commerce dependency (estimated 45% of revenue) creates platform risk. Banker fees: 3% for IPO, 1.5% for M&A advisory.',
    task: '1. Value Nirvana under both scenarios. Build a DCF and revenue multiple valuation for the strategic sale. Build an IPO comparable valuation range. Calculate the promoter\'s net proceeds under each path after taxes, banker fees (3% IPO, 1.5% M&A), and lock-up risk.\n\n2. Identify the three factors that most determine which path maximises promoter value. Quantify the impact of each.\n\n3. The 41% customer retention rate is below the category average of 58%. Assess how this metric affects IPO investor appetite vs. strategic buyer motivation differently.\n\n4. Recommend which path to pursue with a specific rationale that addresses the promoter\'s stated priority of "maximum value and full exit within 18 months."',
    admin_only: {
      strong_response: 'Identifies that the 41% customer retention rate has opposite implications for the two paths: IPO investors will model it into LTV/CAC and suppress the public market multiple, while a strategic buyer like Hindustan Foods cares less about retention because they plan to integrate distribution channels. Calculates net proceeds after fees, taxes, and lock-up risk for each path rather than comparing headline valuations.',
      critical_gap: 'Simply compares headline valuations (₹1,205 Cr vs ₹2,000 Cr IPO) and recommends IPO. Missing the lock-up risk, banker fees, and the retention issue\'s differential impact on public vs. strategic valuation is the failure mode.',
      non_obvious_signal: 'The same data point — 41% customer retention — has opposite implications for the two paths. This mirrors the Lazard/Rothschild/Avendus final interview question: "How do you run a dual-track process?" The answer requires understanding that the same metric can strengthen one path while weakening the other.',
    },
  },
  {
    code: 'IB-010',
    role: 'Investment Banking Analyst',
    difficulty: 'Expert',
    title: 'Leveraged Recapitalisation — Should Primus Engineering Return Capital or Acquire?',
    situation: 'Primus Engineering has ₹2,100 Cr of excess cash on its balance sheet and is under pressure from its largest activist investor (12.4% stake) to deploy or return it. The activist has publicly demanded either a leveraged recap or an acquisition. Your MD has 45 minutes before the Board meeting starts.',
    company_overview: 'Primus Engineering Ltd — Industrial automation and robotics. Listed. Revenue FY24: ₹4,200 Cr. EBITDA FY24: ₹756 Cr (18% margin). PAT FY24: ₹504 Cr. Current debt: ₹0 (debt-free). Cash and investments: ₹2,100 Cr. Market cap: ₹12,600 Cr. P/E: 25x trailing. EV/EBITDA: 14x (ex-cash). ROCE: 28%. Beta: 0.8. Shares: 120 Cr at ₹105/share. Activist demand: "Return ₹1,500 Cr via leveraged buyback within 6 months or announce an acquisition." Alternative: Acquire Automax Robotics (private) for ₹1,800 Cr. Automax Revenue: ₹280 Cr. Automax EBITDA: ₹42 Cr (15% margin). Strategic fit: High. Integration risk: Management has never executed an acquisition.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['3,600', '3,880', '4,200'] },
        { label: 'EBITDA (₹ Cr)', values: ['648', '699', '756'] },
        { label: 'PAT (₹ Cr)', values: ['432', '466', '504'] },
        { label: 'Cash & Investments (₹ Cr)', values: ['1,500', '1,800', '2,100'] },
        { label: 'ROCE', values: ['26%', '27%', '28%'] },
        { label: 'P/E (trailing)', values: ['22x', '24x', '25x'] },
        { label: 'EV/EBITDA (ex-cash)', values: ['12x', '13x', '14x'] },
        { label: 'Automax Asking Price', values: ['—', '—', '₹1,800 Cr (42.9x EBITDA)'] },
        { label: 'Proposed Buyback Price', values: ['—', '—', '₹120/share (15% premium)'] },
      ],
    },
    market_context: 'Activist investor has threatened to call an EGM if the Board does not respond within 30 days. Three Indian industrials faced similar activist demands in FY24 — two conceded, one fought and won but share price declined 22% during the dispute.\n\nThe proposed leveraged recap: Raise ₹800 Cr debt at 9% interest and combine with ₹700 Cr cash for a ₹1,500 Cr buyback at ₹120/share (15% premium). This would retire 12.5 Cr shares (10.4% of outstanding).',
    task: '1. Model the leveraged recap scenario: Raise ₹800 Cr debt at 9% interest and combine with ₹700 Cr cash for a ₹1,500 Cr buyback at ₹120/share. Calculate post-recap EPS accretion/dilution, new leverage ratio, and interest coverage. Show impact on share price under different re-rating scenarios.\n\n2. Model the acquisition scenario: Buy Automax for ₹1,800 Cr (all cash). Calculate acquisition multiple, synergy required to justify price, combined EBITDA, and post-acquisition leverage. At what synergy level does this become value-accretive?\n\n3. The activist investor has threatened to call an EGM if the Board does not respond within 30 days. Evaluate the legal and governance risk of ignoring the demand vs. engaging.\n\n4. Recommend one path — leveraged recap or acquisition — with explicit reasoning that addresses the activist\'s economic interest specifically.',
    admin_only: {
      strong_response: 'Calculates earnings yield (PAT/Market Cap = 504/12,600 = 4%) and compares it to cost of debt (9%). Since the earnings yield is BELOW the cost of debt, the leveraged recap destroys value on a pure return basis — buying back shares at 25x P/E using 9% debt means you are paying more for equity than the return it generates. Identifies that the acquisition may be more value-accretive despite the high price, because Automax\'s EBITDA can grow under Primus\'s automation platform.',
      critical_gap: 'Sees "activist demanding buyback" and immediately recommends the buyback without calculating whether the return on the buyback justifies the debt cost. Treats the buyback as automatically accretive because share count decreases, without comparing earnings yield to cost of debt.',
      non_obvious_signal: 'With P/E of 25x (earnings yield 4%) and cost of debt at 9%, the leveraged recap destroys value. The answer is counterintuitive — the acquisition may be more value-accretive even at a high acquisition price. Strong candidates calculate the earnings yield comparison before recommending either path.',
    },
  },
  {
    code: 'IB-011',
    role: 'Investment Banking Analyst',
    difficulty: 'Expert',
    title: 'Fairness Opinion — Is ₹340 Per Share Fair for Meridian Retail\'s Minority?',
    situation: 'You are advising an independent committee of minority shareholders in Meridian Retail Ltd, a listed company where the promoter group holds 68% and has proposed taking the company private at ₹340 per share. Your firm has been engaged to provide a fairness opinion. The minority shareholders control 32% of the company.',
    company_overview: 'Meridian Retail Ltd — Multi-format retail chain. Listed BSE. Revenue FY24: ₹3,150 Cr (declining from ₹3,280 Cr). EBITDA FY24: ₹189 Cr (6% margin). PAT FY24: ₹62 Cr. Net Debt: ₹420 Cr. Total stores: 240 (owned: 40, leased: 200). Owned real estate value: ₹1,100 Cr (independent valuation). Current offer: ₹340/share. 52-week high: ₹412/share. 52-week low: ₹278/share. Shares outstanding: 28 Cr. Market cap at offer: ₹9,520 Cr. EV at offer: ₹9,940 Cr.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['3,100', '3,280', '3,150'] },
        { label: 'EBITDA (₹ Cr)', values: ['217', '230', '189'] },
        { label: 'EBITDA Margin', values: ['7.0%', '7.0%', '6.0%'] },
        { label: 'PAT (₹ Cr)', values: ['84', '92', '62'] },
        { label: 'Net Debt (₹ Cr)', values: ['380', '400', '420'] },
        { label: 'Owned Real Estate Value', values: ['₹980 Cr', '₹1,040 Cr', '₹1,100 Cr'] },
        { label: 'Stores (Owned/Leased)', values: ['42/195', '41/198', '40/200'] },
        { label: 'EV/EBITDA at Offer', values: ['—', '—', '52.6x'] },
        { label: 'Comparable Txn Multiples', values: ['—', '—', '7.6-9.1x'] },
      ],
    },
    market_context: 'Comparable retail transactions in India (last 18 months): Transaction 1: 8.2x EV/EBITDA. Transaction 2: 7.6x EV/EBITDA. Transaction 3: 9.1x EV/EBITDA. All for companies with positive same-store sales growth — Meridian has negative same-store growth.\n\nThe promoter argues the offer is fair because revenue is declining. However, the owned real estate portfolio of ₹1,100 Cr represents a significant floor value that a going-concern DCF would not capture. Retail margin recovery to 7.5% over 3 years is plausible if store rationalisation is executed.',
    task: '1. Provide a valuation range using three methodologies: DCF (assuming retail margin recovery to 7.5% over 3 years), comparable transaction multiples, and sum-of-parts (operating business + real estate). Calculate implied price per share under each method.\n\n2. The 52-week high was ₹412. The offer is ₹340 — 17.5% below the 52-week high. The promoter argues the current offer is fair because revenue is declining. Assess this argument specifically and determine whether it is valid.\n\n3. Identify two methodologies where ₹340 appears fair and two where it appears inadequate. What does this tell you about the appropriate fairness opinion?\n\n4. Draft the operative conclusion of the fairness opinion: is ₹340 per share fair, inadequate, or within a range that requires further negotiation? Defend your conclusion.',
    admin_only: {
      strong_response: 'Calculates a liquidation floor by separating the owned real estate (₹1,100 Cr gross) from the operating business. In a liquidation scenario where stores are closed and real estate sold, the floor value provides a baseline that makes the going-concern DCF defensible. Recognises that comparable transaction multiples apply to growing retailers, not declining ones, and adjusts accordingly.',
      critical_gap: 'Uses only one valuation methodology or applies comparable multiples without adjusting for Meridian\'s negative growth. Treats the 52-week high as irrelevant without analysing why the stock traded at ₹412 and what has changed. Ignores the real estate floor value entirely.',
      non_obvious_signal: 'The owned real estate value of ₹1,100 Cr is productive (store locations), not separable assets — but a liquidation scenario where stores are closed and real estate sold yields approximately ₹1,100 Cr gross. The floor test is what makes a fairness opinion defensible. Strong candidates calculate this floor and compare it to the going-concern value to determine whether ₹340 captures the asset base adequately.',
    },
  },
  {
    code: 'IB-012',
    role: 'Investment Banking Analyst',
    difficulty: 'Expert',
    title: 'Carve-Out and Spin-Off — Separating Bharat Conglomerate\'s Chemical Division',
    situation: 'Bharat Conglomerate Ltd, a diversified industrial group, is considering spinning off its specialty chemicals division into a separately listed entity. Activist pressure and conglomerate discount of 28% vs. sum-of-parts have driven the Board to evaluate this. You have 45 minutes to assess feasibility and structure.',
    company_overview: 'Parent: Bharat Conglomerate Ltd — Revenue FY24 (consolidated): ₹18,400 Cr. EBITDA FY24: ₹2,760 Cr (15% margin). Market cap: ₹42,000 Cr. Sum-of-parts estimated: ₹58,000 Cr. Conglomerate discount: 28%. Segments: Chemicals (28% revenue), Textiles (31%), Infrastructure (24%), FMCG (17%). Chemical Division: Revenue FY24: ₹5,152 Cr. EBITDA: ₹1,134 Cr (22% margin). PAT: ₹648 Cr. Standalone net debt: ₹480 Cr. ROCE: 31%. Growth: 18% CAGR last 3 years. Top 3 customers: 38% of revenue. Shared services from parent (HR, IT, treasury, legal): ₹180 Cr annual allocation.',
    financials: {
      headers: ['', 'Chemical Div', 'Rest of Bharat', 'Consolidated'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['5,152', '13,248', '18,400'] },
        { label: 'EBITDA (₹ Cr)', values: ['1,134', '1,626', '2,760'] },
        { label: 'EBITDA Margin', values: ['22.0%', '12.3%', '15.0%'] },
        { label: 'PAT (₹ Cr)', values: ['648', '—', '—'] },
        { label: 'ROCE', values: ['31%', '—', '—'] },
        { label: 'Net Debt (₹ Cr)', values: ['480', '—', '—'] },
        { label: 'Shared Services Allocation', values: ['₹180 Cr', '—', '—'] },
        { label: 'Listed Peer EV/EBITDA Range', values: ['18-24x', '—', '—'] },
        { label: 'Listed Peer P/E Range', values: ['24-32x', '—', '—'] },
      ],
    },
    market_context: 'Listed specialty chemicals peers trading at 24-32x P/E and 18-24x EV/EBITDA. The conglomerate discount of 28% implies that the market values the chemicals division at a fraction of its standalone potential. Activist investor has publicly demanded separation.\n\nKey structural challenge: The ₹180 Cr of shared services currently allocated from the parent will need to be replicated or outsourced. As a ₹5,152 Cr standalone entity, the cost of replicating functions that are shared across a ₹18,400 Cr group will be materially higher per unit — diseconomies of scale.',
    task: '1. Value the chemical division as a standalone listed entity using peer multiples. Calculate the implied enterprise value and equity value. What discount should you apply for the first 12 months as a new independent company?\n\n2. The ₹180 Cr of shared services currently allocated from the parent will need to be replicated or outsourced. Model three scenarios: (a) full replication at 120% of current allocation (b) outsourcing at 90% of allocation (c) TSA with parent for 24 months at 85% then step-up to market rates. Show EBITDA impact of each.\n\n3. Identify the top three structural risks of the spin-off and rank them by severity. Customer concentration is one — identify two more that most analysts would miss.\n\n4. Should Bharat Conglomerate spin off the chemical division now, wait 18 months, or pursue a partial stake sale via block deal instead? Recommend one path with specific reasoning.',
    admin_only: {
      strong_response: 'Models the shared services diseconomy specifically: ₹180 Cr allocated at conglomerate scale will cost ₹216-250 Cr to replicate standalone, destroying 3.2-6.2% of EBITDA. Identifies that the conglomerate discount elimination must exceed the shared services cost increase plus the IPO/listing discount for the spin-off to create net value. Calculates the breakeven point.',
      critical_gap: 'Values the standalone entity using peer multiples without deducting standalone costs. Treats shared services as a simple line item transfer rather than modelling the diseconomies of scale. Says "shared services need to be replaced" without quantifying the cost differential.',
      non_obvious_signal: 'The shared services cost of ₹180 Cr is based on the parent\'s cost structure. As a standalone entity, the chemical division will pay materially more per unit than when shared across a ₹18,400 Cr conglomerate. The diseconomies of scale on shared services is the non-obvious cost that can destroy the spin-off thesis if not properly modelled.',
    },
  },
  {
    code: 'IB-013',
    role: 'Investment Banking Analyst',
    difficulty: 'Expert',
    title: 'Cross-Border Regulatory Arbitrage — Olympia Steel\'s Singapore Holding Structure',
    situation: 'Your firm is advising Olympia Steel Ltd on an inbound M&A transaction where the acquirer is a Singapore-based holding company (SPV) owned by a US private equity fund. The deal has attracted CCI and FIPB scrutiny. A third party has filed a complaint with CCI alleging the Singapore SPV is a shell used to disguise Chinese beneficial ownership. You have 45 minutes to assess the deal risks.',
    company_overview: 'Target: Olympia Steel Ltd — Indian listed steel manufacturer. Revenue FY24: ₹9,400 Cr. EBITDA: ₹940 Cr (10% margin). Acquirer offer: ₹6,200 Cr for 51% controlling stake (implying 100% EV of ₹12,157 Cr, 12.9x EV/EBITDA). Acquirer structure: Singapore SPV (100% owned by Meridian Capital Partners, a Delaware-registered PE fund). The Singapore entity has no operating assets — incorporated 4 months ago. Complication: One LP from Hong Kong holds 8% LP interest in the PE fund. CCI complaint filed alleging Chinese beneficial ownership.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['8,200', '8,800', '9,400'] },
        { label: 'EBITDA (₹ Cr)', values: ['820', '880', '940'] },
        { label: 'EBITDA Margin', values: ['10.0%', '10.0%', '10.0%'] },
        { label: 'Offer Value (51% stake)', values: ['—', '—', '₹6,200 Cr'] },
        { label: 'Implied EV/EBITDA', values: ['—', '—', '12.9x'] },
        { label: 'SPV Incorporation', values: ['—', '—', '4 months ago'] },
        { label: 'HK LP Interest in Fund', values: ['—', '—', '8%'] },
        { label: 'PMLA Beneficial Ownership Threshold', values: ['—', '—', '10% (companies)'] },
        { label: 'Combined Market Share (Flat Steel)', values: ['—', '—', '>15%'] },
      ],
    },
    market_context: 'Steel sector: FDI allowed up to 100% under automatic route. CCI filing required as combined market share exceeds 15% in flat steel products. Press Note 3 (2020) requires government approval for FDI from countries sharing a land border with India — aimed at China. The question of whether 8% LP interest constitutes "beneficial ownership" is genuinely contested.\n\nPMLA defines beneficial ownership at 10% for companies and 15% for LLPs. However, regulatory intent matters alongside legal threshold — regulators are alert to layered structures (Delaware PE → Singapore SPV → Indian target) designed to obscure ultimate beneficiary.',
    task: '1. Analyse the FDI regulatory framework applicable to this transaction. Is the Singapore SPV structure legally permissible and commercially rational, or does it create unacceptable regulatory risk?\n\n2. The CCI complaint alleges Chinese beneficial ownership through the Hong Kong LP. What specific legal tests apply under PMLA and Press Note 3 (2020)? Does 8% LP interest constitute beneficial ownership? What additional information do you need to advise definitively?\n\n3. Model three deal timeline scenarios: (a) CCI approves in 30 days (b) CCI investigation adds 6-month delay — cost impact to deal (c) CCI blocks the deal — what are the break-fee mechanics?\n\n4. Advise whether Olympia\'s Board should proceed with this deal, renegotiate the structure, or walk away. If renegotiate — what specific structural change removes the regulatory risk?',
    admin_only: {
      strong_response: 'Identifies that 8% LP interest is below the PMLA threshold of 10% for companies, but acknowledges that regulatory intent under Press Note 3 goes beyond strict legal thresholds. Recognises the genuine uncertainty — the answer is not clear-cut — and frames the advice around risk probability rather than definitive legal opinion. Recommends structural remediation: require the Hong Kong LP to divest or restructure as a FVCI.',
      critical_gap: 'Definitively states that 8% does not trigger Press Note 3 (because it\'s below 10%) without acknowledging the regulatory uncertainty. Ignores the SPV structure itself as a red flag — a 4-month-old entity with no operating assets is the exact pattern regulators investigate.',
      non_obvious_signal: 'Press Note 3 (2020) is aimed at preventing Chinese FDI through layered structures. An 8% LP interest from a Hong Kong entity in a Delaware PE fund holding through a Singapore SPV is exactly the type of layered structure regulators are alert to. The threshold question (8% vs 10%) is genuinely contested — strong candidates identify this uncertainty rather than definitively ruling it in or out.',
    },
  },
  {
    code: 'IB-014',
    role: 'Investment Banking Analyst',
    difficulty: 'Expert',
    title: 'IPO Pricing Under Market Stress — Pricing UrbanGrid\'s IPO in a Falling Market',
    situation: 'UrbanGrid Infrastructure filed its DRHP 8 weeks ago and the IPO was oversubscribed in anchor allocation. But in the past 10 days the Nifty has fallen 9% due to global macro concerns. Your MD must decide today whether to proceed with IPO pricing at the original band or pull back.',
    company_overview: 'UrbanGrid Infrastructure Ltd — Urban utility and smart grid operator. Revenue FY24: ₹1,840 Cr. EBITDA: ₹552 Cr (30% margin). PAT: ₹298 Cr. Asset-heavy: ₹8,400 Cr fixed assets. Net debt: ₹3,200 Cr. Regulatory business — 80% revenue from government concessions. Original IPO band: ₹420-440/share. At ₹440: Market cap ₹22,000 Cr, EV ₹25,200 Cr, EV/EBITDA 45.6x. Fresh issue: ₹3,000 Cr. OFS: ₹2,000 Cr (promoter exit). Total IPO size: ₹5,000 Cr.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['1,480', '1,650', '1,840'] },
        { label: 'EBITDA (₹ Cr)', values: ['444', '495', '552'] },
        { label: 'EBITDA Margin', values: ['30%', '30%', '30%'] },
        { label: 'PAT (₹ Cr)', values: ['198', '248', '298'] },
        { label: 'Net Debt (₹ Cr)', values: ['2,800', '3,000', '3,200'] },
        { label: 'Original IPO Band', values: ['—', '—', '₹420-440'] },
        { label: 'Nifty Change (10 days)', values: ['—', '—', '-9%'] },
        { label: 'Comparable Infra Stock Change', values: ['—', '—', '-14%'] },
        { label: 'Anchor Investors at Risk', values: ['—', '—', '3 of 12'] },
      ],
    },
    market_context: 'Market has moved since anchor allocation: Nifty down 9% in 10 days. Comparable listed infra company down 14% in same period. 3 of 12 anchor investors have sent informal signals they may not honor commitment. Under SEBI regulations, anchor investors are legally bound to their commitment but enforcement is relationship-dependent.\n\nThe OFS component of ₹2,000 Cr is the promoter exit. In a falling market, the promoter being seen to exit at peak prices creates reputational damage for both the company and the banker.',
    task: '1. Calculate the revised fair value of UrbanGrid given the 9% market decline. Should the band be revised down, and by how much? Distinguish between market re-rating (beta impact) and company-specific value change (none has occurred).\n\n2. Three anchor investors are signalling they may not honor their commitment. Under SEBI regulations, what are the legal obligations of anchor investors? What happens to the IPO if anchor commitments fall short?\n\n3. Model four options: (a) proceed at original band ₹420-440 (b) revise band down to ₹370-390 (c) pull the IPO and refile in 6 months (d) proceed with fresh issue only, withdraw OFS. For each: quantify the impact on promoter proceeds, fresh capital raised, and post-listing price stability risk.\n\n4. Recommend one option. Your recommendation must address what happens to the relationship with anchor investors if you proceed at a price where they lose money on listing day.',
    admin_only: {
      strong_response: 'Identifies that pulling back the OFS while keeping the fresh issue preserves the company\'s capital raise while removing the reputational damage of the promoter exiting at peak prices. This "fresh issue only" structure resolves most competing tensions simultaneously: company gets capital, promoter doesn\'t appear opportunistic, anchor investors are more comfortable, and listing price stability improves.',
      critical_gap: 'Focuses solely on repricing the band without considering the structural option of separating fresh issue from OFS. Treats the IPO as a binary proceed/pull decision without exploring hybrid structures. Ignores the relationship dimension with anchor investors.',
      non_obvious_signal: 'The OFS component is the key. Pulling OFS but keeping fresh issue is the non-obvious solution that resolves most competing tensions. The promoter delays exit (not ideal) but the company raises needed capital, anchors are protected, and listing stability is preserved. This mirrors real IPO banking decisions during market stress.',
    },
  },
  {
    code: 'IB-015',
    role: 'Investment Banking Analyst',
    difficulty: 'Expert',
    title: 'Distressed M&A — Vulture or Saviour: Acquiring Starline Aviation',
    situation: 'Starline Aviation has entered voluntary insolvency under IBC. Your firm represents a strategic acquirer (domestic airline) interested in the resolution plan. The Committee of Creditors (CoC) meets in 12 days. You have 45 minutes to assess the bid.',
    company_overview: 'Target: Starline Aviation Ltd (Insolvent). Pre-insolvency Revenue FY23: ₹4,200 Cr. EBITDA FY23: -₹180 Cr (loss-making). Admitted claims: ₹6,800 Cr (financial creditors: ₹5,200 Cr, operational creditors: ₹1,600 Cr). Assets: 18 aircraft (15 owned, 3 leased), slots at 12 airports (4 Tier-1 pairs), brand and operating certificates, ₹180 Cr cash in escrow. Aircraft market value: ₹2,100 Cr. Slot value estimated: ₹800-1,400 Cr. Liquidation value: ₹2,800 Cr total.',
    financials: {
      headers: ['', 'Bid A (Your Client)', 'Bid B (Asset Stripper)', 'Bid C (Foreign Airline)'],
      rows: [
        { label: 'Bid Amount', values: ['₹3,200 Cr', '₹2,600 Cr', '₹3,800 Cr'] },
        { label: 'Structure', values: ['Resume operations', 'Liquidate assets', 'Resume operations'] },
        { label: 'Employee Retention', values: ['2,800 of 4,200', '0', '3,500 of 4,200'] },
        { label: 'Regulatory Approval', values: ['None needed', 'None needed', '6-9 months'] },
        { label: 'Deal Certainty', values: ['High', 'High', 'Low'] },
        { label: 'Creditor Recovery Rate', values: ['47%', '38%', '56%'] },
        { label: 'Slot Preservation', values: ['Yes', 'No (destroyed)', 'Yes'] },
        { label: 'Going Concern Value', values: ['Preserved', 'Destroyed', 'Preserved'] },
      ],
    },
    market_context: 'IBC mandates that the CoC must consider whether the resolution plan maximises the value of assets AND is in the interest of all stakeholders — not just maximum cash recovery. The airport slots valued at ₹800-1,400 Cr cannot be independently sold — they transfer with the operating certificate. If operations cease, slots revert to the airport authority.\n\nBid C (foreign airline) offers ₹600 Cr more but requires 6-9 months of government approval for foreign ownership of a domestic airline. The opportunity cost of waiting at 12% per annum is material. The IBC 270-day timeline creates urgency.',
    task: '1. Calculate the recovery rate for financial creditors under each of the three bids. Under IBC waterfall provisions, how are proceeds distributed between financial creditors, operational creditors, and employees? Which bid maximises creditor recovery?\n\n2. The airport slots are valued at ₹800-1,400 Cr — a wide range. What drives this uncertainty? How would you arrive at a defensible slot valuation for the CoC presentation? Note: Slots cannot be independently sold — they transfer with the operating certificate.\n\n3. The foreign airline bid (Bid C) offers ₹600 Cr more but requires 6-9 months of government approval. Calculate the NPV of waiting for Bid C vs. accepting Bid A today at a creditor opportunity cost of 12% per annum.\n\n4. Your client (Bid A) wants to win. What specific modifications to their bid would make it more competitive without increasing the cash component? Recommend one structural change.',
    admin_only: {
      strong_response: 'Applies the IBC standard correctly — "maximum value" under IBC is not synonymous with highest immediate cash offer. Bid B (asset stripper at ₹2,600 Cr) actually destroys significant value by making slots worthless without an operating certificate. Recognises that Bid A preserves going-concern value, employment, and slot value. Calculates NPV of Bid C delay and shows the time value erodes the premium.',
      critical_gap: 'Ranks bids purely by headline number (₹3,800 > ₹3,200 > ₹2,600) without applying the IBC stakeholder test. Fails to recognise that Bid B destroys slot value (₹800-1,400 Cr) by ceasing operations. Ignores the NPV impact of Bid C\'s 6-9 month approval delay.',
      non_obvious_signal: 'IBC\'s "maximum value of assets" standard means Bid B (highest certainty but lowest amount) destroys more value than it captures because slots become worthless without operations. Bid A at ₹3,200 Cr preserves going-concern value AND employment — which are IBC statutory considerations beyond just cash recovery. This is how real IBC advisory works.',
    },
  },
];

