import type { DealCase } from './types';

export const IB_CASES: DealCase[] = [
  {
    code: 'IB-001',
    role: 'Investment Banking Analyst',
    difficulty: 'Intermediate',
    title: 'Manufacturing Acquisition',
    situation: 'Your managing director has asked you to evaluate Meridian Auto Components Pvt Ltd for a potential acquisition by a mid-market private equity fund targeting ₹50-500 Cr revenue manufacturing companies. You have 45 minutes to complete your analysis and present a recommendation.',
    company_overview: 'Meridian Auto Components is a Pune-based manufacturer of precision-engineered components for passenger vehicles and commercial trucks. Founded 2008. Supplies 3 major OEMs — 78% of total revenue. 340 employees. 2 manufacturing facilities.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue', values: ['187', '214', '231'] },
        { label: 'COGS', values: ['128', '151', '168'] },
        { label: 'Gross Profit', values: ['59', '63', '63'] },
        { label: 'EBITDA', values: ['38', '41', '38'] },
        { label: 'Depreciation', values: ['12', '14', '15'] },
        { label: 'EBIT', values: ['26', '27', '23'] },
        { label: 'Interest', values: ['8', '9', '11'] },
        { label: 'PBT', values: ['18', '18', '12'] },
        { label: 'Tax', values: ['5', '5', '3'] },
        { label: 'PAT', values: ['13', '13', '9'] },
        { label: 'Total Assets', values: ['210', '238', '261'] },
        { label: 'Total Debt', values: ['82', '94', '108'] },
        { label: 'Equity', values: ['128', '144', '153'] },
        { label: 'Capex', values: ['18', '22', '24'] },
        { label: 'WC Days', values: ['67', '71', '79'] },
      ],
    },
    market_context: 'Indian auto components industry grew 12% in FY24. EV transition creates 5-10 year demand uncertainty for ICE components. Meridian has no EV development program.\n\nInterest rates rose 150bps since FY22. Company refinanced ₹40Cr debt in FY24.',
    task: '1. VALUATION\nEstimate a valuation range using at least one methodology. Show working. State all assumptions.\n\n2. RISK ASSESSMENT\nIdentify top 3 risks. For each: explain the mechanism and suggest one mitigation.\n\n3. INVESTMENT RECOMMENDATION\nProceed / Proceed with Conditions / Pass. Defend your thesis in 150-200 words.\n\nNote: No single correct answer exists. We evaluate thinking quality, not a specific output.',
    admin_only: {
      strong_response: 'Identifies gross margin stagnation (₹63Cr flat FY23-FY24 despite revenue growth), connects rising debt with capex cycle, and flags EV transition as existential risk with a timeline estimate.',
      critical_gap: 'Uses only revenue multiples without questioning margin sustainability. Ignores working capital deterioration (67→79 days). Gives generic risk list without quantification.',
      non_obvious_signal: 'Customer concentration risk (78% from 3 OEMs) combined with zero EV capability means the company faces both customer dependency AND technology obsolescence simultaneously.',
    },
  },
  {
    code: 'IB-002',
    role: 'Investment Banking Analyst',
    difficulty: 'Intermediate',
    title: 'Consumer Brand Acquisition',
    situation: 'Your MD at a mid-market IB boutique has asked you to evaluate a potential acquisition of a D2C skincare brand by a large FMCG strategic buyer. You have 45 minutes to complete your analysis.',
    company_overview: 'Lumière Skin Co. is an India-based D2C skincare brand founded in 2019. Sells through own website and quick-commerce platforms. Products: 14 SKUs across serums, moisturisers, and SPF. Average order value ₹1,400. Repeat purchase rate 38%. Customer acquisition cost ₹680. Total equity raised: ₹42 Cr across 3 rounds. Last round valuation: ₹280 Cr (Series B, 2023). Strategic buyer is Hindustan Beauté Ltd — ₹4,200 Cr revenue FMCG company seeking premium skincare entry.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['28', '61', '89'] },
        { label: 'Gross Margin', values: ['61%', '63%', '64%'] },
        { label: 'EBITDA', values: ['-8.4', '-4.2', '6.2'] },
        { label: 'EBITDA Margin', values: ['-30%', '-6.9%', '7%'] },
        { label: 'CAC (₹)', values: ['520', '640', '680'] },
        { label: 'Repeat Purchase Rate', values: ['31%', '35%', '38%'] },
        { label: 'AOV (₹)', values: ['1,180', '1,320', '1,400'] },
        { label: 'Monthly Cash Burn (₹ Cr)', values: ['1.8', '1.1', 'Breakeven Q3'] },
        { label: 'Total Equity Raised (₹ Cr)', values: ['12', '28', '42'] },
      ],
    },
    market_context: 'Indian skincare market growing 22% CAGR. D2C consolidation accelerating as unit economics normalise post-COVID growth. Large FMCG companies acquiring premium D2C brands to access younger demographics.\n\nQuick-commerce platforms (Blinkit, Zepto) becoming primary discovery channel, reducing CAC for some brands but increasing platform dependency.',
    task: '1. Advise on acquisition rationale — why should Hindustan Beauté Ltd acquire Lumière?\n\n2. Build a valuation range using revenue multiples and DCF. Justify your multiple selection.\n\n3. Assess synergy potential — distribution, brand portfolio, cost savings. Quantify where possible.\n\n4. Identify top 3 deal risks and recommend whether HBL should proceed.\n\nState all assumptions explicitly.',
    admin_only: {
      strong_response: 'Identifies that CAC is rising (₹520→₹680) while repeat rate improvement (31%→38%) is not fast enough to offset it. Calculates CAC payback period and flags unit economics sustainability.',
      critical_gap: 'Values the brand purely on revenue multiples without questioning whether ₹680 CAC is sustainable at scale. Treats the ₹280 Cr Series B valuation as an anchor without independent analysis.',
      non_obvious_signal: 'CAC trend vs repeat rate — is the brand building genuine loyalty or acquiring increasingly expensive customers? The CAC payback period is the key metric that determines whether this is a real brand or a marketing-subsidised business.',
    },
  },
  {
    code: 'IB-003',
    role: 'Investment Banking Analyst',
    difficulty: 'Advanced',
    title: 'Tech Company IPO Readiness',
    situation: 'Your VP has asked you to assess whether a SaaS company is ready for an IPO within 18 months and at what valuation range. You have 45 minutes to deliver your assessment.',
    company_overview: 'TaskFlow Technologies Pvt Ltd is a B2B SaaS project management platform based in Bengaluru. Founded 2018. Targets mid-market Indian enterprises. 340 employees. 280 paying enterprise accounts.',
    financials: {
      headers: ['', 'FY23', 'FY24'],
      rows: [
        { label: 'ARR (₹ Cr)', values: ['66', '94'] },
        { label: 'ARR Growth YoY', values: ['67%', '41%'] },
        { label: 'Net Revenue Retention', values: ['122%', '118%'] },
        { label: 'Gross Margin', values: ['73%', '71%'] },
        { label: 'Sales Efficiency (CAC/ACV months)', values: ['12', '14'] },
        { label: 'Annual Churn', values: ['6%', '8%'] },
        { label: 'EBITDA (₹ Cr)', values: ['-22', '-31'] },
        { label: 'Cash Runway (months)', values: ['34', '22'] },
        { label: 'Headcount', values: ['260', '340'] },
      ],
    },
    market_context: 'Indian SaaS IPO market reopened in 2024 after 2022-23 correction. Public market SaaS comps trading at 6-9x forward ARR. US-listed Indian SaaS companies command 15-20% premium.\n\nGrowth deceleration across the sector is a key concern for public market investors — companies trading at 8x+ ARR need to demonstrate path to profitability or sustained 40%+ growth.',
    task: '1. Assess IPO readiness across financial, operational, and governance dimensions.\n\n2. Recommend optimal timing — IPO now, in 12 months, or in 18 months? Why?\n\n3. Build a valuation range using ARR multiples and DCF.\n\n4. Identify the three most critical milestones before IPO filing.\n\nState all assumptions explicitly.',
    admin_only: {
      strong_response: 'Flags growth deceleration (67%→41%) as the primary investor concern and connects it to deteriorating sales efficiency (12→14 month CAC payback) and rising churn (6%→8%). Recommends re-accelerating growth OR demonstrating profitability path before IPO.',
      critical_gap: 'Applies a generic SaaS multiple without adjusting for growth deceleration. Treats 41% growth as "strong" without comparing to the 67% prior year or explaining the deceleration.',
      non_obvious_signal: 'Growth deceleration from 67% to 41% — is this market saturation, sales capacity constraint, or product-market fit degradation? The answer determines whether the company IPOs at 8x ARR or 5x ARR.',
    },
  },
  {
    code: 'IB-004',
    role: 'Investment Banking Analyst',
    difficulty: 'Advanced',
    title: 'Distressed Debt Restructuring',
    situation: 'Your MD is advising the lender consortium of a hotel chain that has defaulted on ₹380 Cr of term debt. You must evaluate restructuring options within 45 minutes.',
    company_overview: 'Suryavanshi Hospitality Ltd is an 18-hotel chain across Tier 1 and Tier 2 Indian cities. Founded 1998. Mix of 7 owned and 11 leased properties.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['310', '428', '389'] },
        { label: 'EBITDA (₹ Cr)', values: ['56', '73', '47'] },
        { label: 'EBITDA Margin', values: ['18.1%', '17.1%', '12.1%'] },
        { label: 'Interest Expense (₹ Cr)', values: ['42', '52', '62'] },
        { label: 'Debt Outstanding (₹ Cr)', values: ['320', '350', '380'] },
        { label: 'Asset Value — Owned Properties (₹ Cr)', values: ['480', '500', '520'] },
        { label: 'Occupancy Rate', values: ['68%', '74%', '61%'] },
        { label: 'RevPAR (₹)', values: ['4,200', '5,100', '3,800'] },
        { label: 'No. of Lenders', values: ['4', '4', '4'] },
      ],
    },
    market_context: 'Indian hospitality sector is recovering post-COVID but facing new supply in Tier 1 markets. Budget and mid-market segments seeing 15-20% new room supply in FY24-25, compressing occupancy rates for existing players.\n\nRBI guidelines on debt restructuring allow one-time restructuring for operational stress without NPA classification, provided lenders agree within 180 days of default.',
    task: '1. Evaluate three restructuring paths:\n   a) Debt-for-equity swap\n   b) Asset sale and leaseback (owned properties)\n   c) Operational turnaround with debt extension\n\n2. Quantify expected lender recovery under each path.\n\n3. Recommend which path maximises lender recovery.\n\n4. State all assumptions.',
    admin_only: {
      strong_response: 'Identifies that asset value (₹520 Cr) exceeds debt (₹380 Cr) — this is a solvency problem, not an insolvency problem. The real issue is operational underperformance, not inability to repay if assets are realised.',
      critical_gap: 'Treats this as a pure insolvency case and recommends immediate liquidation without recognising the asset cover. Fails to separate owned vs leased property economics.',
      non_obvious_signal: 'Asset value exceeds debt — the company is solvent on a balance sheet basis. The problem is cash flow, not net worth. Strong candidates will identify that lender recovery is highest under operational turnaround (preserves going concern value) rather than fire sale.',
    },
  },
  {
    code: 'IB-005',
    role: 'Investment Banking Analyst',
    difficulty: 'Advanced',
    title: 'Cross-Border M&A Advisory',
    situation: 'Your firm is advising Indus Pharmaceuticals Ltd (₹8,200 Cr revenue, listed on NSE, ₹620 Cr net cash) on acquiring Hoffmann Spezialchemie GmbH, a German specialty pharma excipients manufacturer.',
    company_overview: 'Hoffmann Spezialchemie GmbH is a Munich-based specialty pharma excipients manufacturer. Founded 1962. Family-owned, second generation. 180 employees. 3 proprietary excipients with EU regulatory approval. Customer concentration: Top 3 customers = 61% of revenue (all EU pharma majors).',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (€M)', values: ['41', '44', '47'] },
        { label: 'EBITDA (€M)', values: ['9.4', '10.2', '11.2'] },
        { label: 'EBITDA Margin', values: ['22.9%', '23.2%', '23.8%'] },
        { label: 'EBIT (€M)', values: ['7.6', '8.1', '8.9'] },
        { label: 'Net Debt (€M)', values: ['15', '13', '12'] },
        { label: 'Employees', values: ['175', '178', '180'] },
        { label: 'Synergies Claimed (€M NPV)', values: ['—', '—', '18'] },
      ],
    },
    market_context: 'Indian pharma companies are acquiring European specialty suppliers to secure API and excipient supply chains post-COVID. Three Indian pharma deals in EU specialty chemicals closed in FY23-24 at 10-14x EBITDA.\n\nGerman family businesses face succession challenges — 40% of Mittelstand companies have no identified successor. Regulatory approval for pharma-adjacent acquisitions takes 6-12 months in EU.',
    task: '1. Validate the acquisition rationale for Indus Pharmaceuticals.\n\n2. Build a cross-border valuation (INR/EUR). Apply appropriate multiples.\n\n3. Assess synergy credibility — are the €18M NPV synergies achievable?\n\n4. Identify the top 3 deal execution risks specific to a cross-border family business acquisition.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies key-man risk as the primary due diligence gap — the 3 proprietary excipients may depend on founder knowledge not documented in any process. Also flags cross-border integration complexity and FX risk on deal economics.',
      critical_gap: 'Focuses only on financial metrics and ignores the family business dynamics. Applies Indian pharma multiples to a German company without adjusting for market differences.',
      non_obvious_signal: 'Family business second generation — key man risk. The proprietary excipients may depend on founder knowledge not documented in any process. This is the primary due diligence gap that determines whether the acquisition value survives the transition.',
    },
  },
  {
    code: 'IB-006',
    role: 'Investment Banking Analyst',
    difficulty: 'Advanced',
    title: 'Leveraged Buyout Candidate',
    situation: 'A PE fund client has asked your firm to run a sell-side process for a packaging manufacturer. Your job is to prepare the investment thesis for potential LBO buyers.',
    company_overview: 'Packstar Industries Pvt Ltd is a Pune-based rigid plastic packaging manufacturer. Founded 2003. Customers: FMCG, pharma, and food companies. Long-term supply agreements with 4 anchor customers (avg 6-year tenure).',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['298', '318', '340'] },
        { label: 'EBITDA (₹ Cr)', values: ['59', '66.8', '72'] },
        { label: 'EBITDA Margin', values: ['19.8%', '21.0%', '21.2%'] },
        { label: 'Capex (₹ Cr)', values: ['25', '28', '30'] },
        { label: 'Capex as % of Revenue', values: ['8.4%', '8.8%', '8.8%'] },
        { label: 'Free Cash Flow (₹ Cr)', values: ['28', '31', '34'] },
        { label: 'Working Capital Days', values: ['48', '44', '45'] },
        { label: 'Gross Block (₹ Cr)', values: ['240', '260', '280'] },
        { label: 'Existing Debt (₹ Cr)', values: ['52', '48', '45'] },
      ],
    },
    market_context: 'Packaging sector trading at 10-14x EBITDA for quality assets. PE interest in manufacturing buyouts increasing as India becomes a global supply chain alternative.\n\nPlastic packaging faces ESG scrutiny — regulatory risk around single-use plastic bans. However, rigid packaging for pharma and food is exempt from most regulations.',
    task: '1. Build the LBO investment thesis.\n\n2. Model entry at 12x EBITDA. Assume 60% debt financing at 11% interest.\n\n3. Project whether a 25%+ IRR is achievable at exit multiples of 10-14x over a 5-year hold.\n\n4. Identify value creation levers and the key risk to the thesis.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Calculates FCF conversion (FCF/EBITDA = 47%) and identifies that capex intensity creates a cash flow problem in an LBO. Shows that debt paydown is slower than EBITDA suggests because maintenance capex consumes ~42% of EBITDA.',
      critical_gap: 'Uses EBITDA as a proxy for cash flow without calculating FCF conversion. Shows attractive IRRs that ignore the capex reality of an equipment-intensive business.',
      non_obvious_signal: 'Capex intensity (8-9% of revenue) means FCF conversion is weak despite strong EBITDA margins. EBITDA looks great but free cash flow tells the real story for an LBO — debt paydown capacity is much lower than headline numbers suggest.',
    },
  },
  {
    code: 'IB-007',
    role: 'Investment Banking Analyst',
    difficulty: 'Advanced',
    title: 'Rights Issue Advisory',
    situation: 'A listed infrastructure company needs to raise ₹1,200 Cr equity to fund a highway project and has asked your firm to advise on the optimal capital raise structure.',
    company_overview: 'Bharat Infracon Ltd is listed on BSE with a market cap of ₹3,400 Cr. Infrastructure developer — highways, bridges, and port logistics. Promoter holding: 52.3% (post-dilution floor: must stay above 51% for control).',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['1,520', '1,680', '1,840'] },
        { label: 'EBITDA (₹ Cr)', values: ['342', '378', '410'] },
        { label: 'Net Debt (₹ Cr)', values: ['1,680', '1,890', '2,100'] },
        { label: 'Net Debt/EBITDA', values: ['4.9x', '5.0x', '5.1x'] },
        { label: 'Interest Coverage', values: ['3.1x', '2.9x', '2.8x'] },
        { label: 'Share Price (₹)', values: ['—', '—', '184'] },
        { label: 'P/E (trailing)', values: ['—', '—', '18x'] },
        { label: 'Promoter Holding', values: ['54.1%', '53.2%', '52.3%'] },
        { label: 'HAM Project Pipeline (₹ Cr)', values: ['—', '—', '4,800'] },
      ],
    },
    market_context: 'Indian infrastructure sector receiving strong government capex support. HAM (Hybrid Annuity Model) highway projects require 40% equity from the developer and 60% from NHAI. Project pipeline is strong but capital-intensive.\n\nSEBI regulations require promoter holding disclosure for capital raise structures. QIP allows up to 25% dilution; rights issue has no cap but requires promoter participation proportionately.',
    task: '1. Compare three capital raise structures: Rights Issue vs QIP vs Preferential Allotment.\n\n2. Calculate dilution impact under each option.\n\n3. Model the promoter holding post-dilution — ensure it stays above 51%.\n\n4. Recommend the structure that raises ₹1,200 Cr while preserving promoter control and minimising minority dilution.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Calculates maximum dilutable shares backward from the 51% floor (52.3% current → 1.3% dilution headroom = ~24 Cr shares maximum). Then tests each option against this constraint before evaluating economics.',
      critical_gap: 'Recommends a capital raise structure without checking the promoter control floor. Suggests QIP or preferential allotment without calculating whether the dilution breaches 51%.',
      non_obvious_signal: 'Promoter control floor creates a hard constraint on dilution quantum. The math must work backward from 51% before running the numbers on each option — not forward from the amount to be raised.',
    },
  },
];
