import type { DealCase } from './types';

export const PE_CASES: DealCase[] = [
  {
    code: 'PE-001',
    role: 'Private Equity Analyst',
    difficulty: 'Intermediate',
    title: 'Control Buyout — Food Services',
    situation: 'Your fund (₹2,000 Cr mid-market PE) is evaluating a control buyout of a quick service restaurant chain. You have 45 minutes to build the investment thesis.',
    company_overview: 'Spice Route QSR Pvt Ltd is a South Indian QSR chain. Founded 2014. 78 outlets across Karnataka, Tamil Nadu, Kerala. Mix: 31 owned, 47 franchised.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['128', '156', '184'] },
        { label: 'System Sales incl. Franchise (₹ Cr)', values: ['192', '231', '267'] },
        { label: 'EBITDA (₹ Cr)', values: ['18', '24', '31'] },
        { label: 'EBITDA Margin', values: ['14.1%', '15.4%', '16.8%'] },
        { label: 'Owned Store EBITDA Margin', values: ['19%', '21%', '22%'] },
        { label: 'Franchise Royalty Margin', values: ['92%', '93%', '94%'] },
        { label: 'New Store Payback (months)', values: ['30', '28', '26'] },
        { label: 'Same-Store Sales Growth', values: ['5.8%', '6.4%', '7.2%'] },
        { label: 'Total Debt (₹ Cr)', values: ['22', '24', '28'] },
      ],
    },
    market_context: 'Indian QSR market growing 18% CAGR. South Indian cuisine is the fastest-growing segment. Franchise-heavy models commanding premium valuations (18-22x EBITDA) vs owned-store models (12-15x).\n\nKey risk: Labour cost inflation in food services averaging 8-10% annually. Rental escalations in mall/high-street locations averaging 6% annually.',
    task: '1. Build the investment thesis for a control buyout.\n\n2. Model LBO at 16x entry (negotiated down from 18x asking). Assume 55% debt at 11% interest.\n\n3. Identify the top value creation levers.\n\n4. Project exit at 14-18x EBITDA in year 5. Calculate IRR sensitivity across entry and exit multiples.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Models franchise economics separately from owned stores. Identifies franchise mix (94% margin) as the real asset. Recommends accelerating owned-to-franchised conversion as the primary value creation lever.',
      critical_gap: 'Treats all 78 outlets as identical. Misses the economic difference between owned (22% margin) and franchised (94% royalty margin) stores. Uses blended EBITDA without segmenting.',
      non_obvious_signal: 'Franchise mix matters more than total revenue. The capital-light franchise model at 94% margin is the real asset. The value creation plan should push owned-to-franchised conversion, not just expand store count.',
    },
  },
  {
    code: 'PE-002',
    role: 'Private Equity Analyst',
    difficulty: 'Intermediate',
    title: 'Growth Equity — EdTech',
    situation: 'Your fund is evaluating a ₹120 Cr Series C growth equity investment in an edtech company focused on upskilling working professionals.',
    company_overview: 'UpGrade Professionals Pvt Ltd is an online upskilling platform based in Bengaluru. Founded 2017. Programs: Data Science, Product Management, Finance, Digital Marketing. 14,200 learners enrolled in FY24.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['42', '68', '98'] },
        { label: 'Gross Margin', values: ['54%', '56%', '58%'] },
        { label: 'EBITDA (₹ Cr)', values: ['-18', '-22', '-24'] },
        { label: 'CAC per Learner (₹)', values: ['14,200', '16,400', '18,400'] },
        { label: 'Course Completion Rate', values: ['62%', '65%', '67%'] },
        { label: 'Placement Rate (of completers)', values: ['68%', '70%', '71%'] },
        { label: 'Avg Salary Increment Post-Course', values: ['28%', '31%', '34%'] },
        { label: 'Refund Rate', values: ['9.8%', '8.8%', '8.2%'] },
        { label: 'Cohort Revenue Retention (12-mo)', values: ['18%', '20%', '22%'] },
      ],
    },
    market_context: 'Indian online education market at $6B, growing 32% CAGR. However, edtech funding has declined 70% from 2021 peak. Investors now demand path to profitability, not just growth.\n\nCompetitor models are shifting to subscription-based or bundled course offerings that generate higher LTV. Single-course models face CAC inflation as platforms compete for the same learner pool.',
    task: '1. Evaluate the ₹120 Cr investment at ₹680 Cr post-money valuation.\n\n2. Build a 5-year financial model. Assess path to profitability.\n\n3. Identify the 3 risks that could prevent the fund from returning 3x.\n\n4. Recommend: invest / do not invest. Defend your thesis.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Flags low cohort revenue retention (22%) as the fundamental weakness. The business depends on continuously acquiring new learners at rising CAC rather than monetising existing relationships. Compares to subscription models and identifies LTV/CAC deterioration.',
      critical_gap: 'Focuses on topline growth (42→98 Cr) and placement rates without questioning the customer acquisition cost trajectory. Treats 22% cohort retention as acceptable without benchmarking.',
      non_obvious_signal: 'Low cohort revenue retention at 22% is the critical unit economics problem. The business model is a leaky bucket — it must continuously acquire expensive new learners. Compare to competitors offering subscription bundles with 60%+ retention.',
    },
  },
  {
    code: 'PE-003',
    role: 'Private Equity Analyst',
    difficulty: 'Advanced',
    title: 'Portfolio Company Monitoring',
    situation: 'You are the deal analyst covering Brightfield Energy Solutions — a portfolio company your fund invested in 18 months ago. The company has missed its EBITDA target by 31% in Year 1. Your MD wants a situation analysis and recovery plan.',
    company_overview: 'Brightfield Energy Solutions is a Solar EPC (Engineering, Procurement, Construction) company. Fund investment: ₹85 Cr for 34% equity at ₹250 Cr valuation.',
    financials: {
      headers: ['', 'Target Y1', 'Actual Y1', 'Variance'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['280', '204', '-27%'] },
        { label: 'EBITDA (₹ Cr)', values: ['42', '29', '-31%'] },
        { label: 'EBITDA Margin', values: ['15.0%', '14.2%', '-80bps'] },
        { label: 'Cash Position (₹ Cr)', values: ['28', '18', '-36%'] },
        { label: 'Debt (₹ Cr)', values: ['60', '65', '+8%'] },
        { label: 'DSCR', values: ['1.45x', '1.21x', 'Below covenant'] },
        { label: 'Pipeline — Signed LOIs (₹ Cr)', values: ['—', '340', 'Strong'] },
        { label: 'Debt Interest Rate', values: ['—', '12.5%', '—'] },
        { label: 'Covenant DSCR Floor', values: ['—', '1.30x', 'Breached'] },
      ],
    },
    market_context: 'Indian solar sector growing rapidly but project execution depends on government grid connectivity approvals which can delay projects 3-6 months. Customer bankruptcy risk is elevated in the commercial solar segment.\n\nRBI has tightened DSCR covenant enforcement — lenders are more proactive about accelerating debt when covenants are breached. Typical response time: 90 days from breach notification.',
    task: '1. Diagnose which miss drivers are structural vs temporary:\n   - Project delays (government approvals)\n   - Customer bankruptcies (₹38 Cr revenue lost)\n   - Equipment cost overruns (8% above budget)\n\n2. Assess debt covenant breach risk and options.\n\n3. Build a recovery scenario for Year 2.\n\n4. Recommend: provide bridge financing (₹25 Cr) or begin strategic options.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies the DSCR covenant breach (1.21x vs 1.30x covenant) as the most urgent issue — not the revenue miss. Addresses lender intervention risk before recovery planning. Recommends securing a covenant waiver or amendment as the immediate priority.',
      critical_gap: 'Focuses on the revenue miss and builds a recovery plan without addressing the covenant breach. Fails to recognise that lenders can accelerate debt within 90 days, making the recovery plan moot.',
      non_obvious_signal: 'The DSCR covenant breach is time-critical and will trigger lender intervention if not addressed before the next quarterly test. This is more urgent than the revenue miss — you cannot recover if lenders accelerate the debt.',
    },
  },
  {
    code: 'PE-004',
    role: 'Private Equity Analyst',
    difficulty: 'Advanced',
    title: 'Secondary Buyout',
    situation: 'Your fund is considering buying a 60% stake from an incumbent PE fund that has held the asset for 6 years. This is a secondary buyout.',
    company_overview: 'ClearPath Diagnostics Pvt Ltd is a pathology lab network with 62 labs across Maharashtra, Gujarat, and MP. Founded 2011. PE-backed since 2018. Incumbent fund asking 16x EBITDA.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['168', '189', '210'] },
        { label: 'EBITDA (₹ Cr)', values: ['40', '46', '52'] },
        { label: 'EBITDA Margin', values: ['23.8%', '24.3%', '24.8%'] },
        { label: 'Capex (₹ Cr)', values: ['10', '12', '14'] },
        { label: 'Free Cash Flow (₹ Cr)', values: ['24', '28', '31'] },
        { label: 'Debt (₹ Cr)', values: ['52', '46', '40'] },
        { label: 'Labs Operating', values: ['48', '55', '62'] },
        { label: 'Revenue per Lab (₹ Cr)', values: ['3.5', '3.4', '3.4'] },
        { label: 'Tests per Day (avg across network)', values: ['12,400', '14,200', '15,800'] },
      ],
    },
    market_context: 'Indian diagnostics market growing 14% CAGR. Consolidation trend — large chains acquiring single-lab operators at 6-8x EBITDA. Network effects: more labs = better brand = higher volume per lab.\n\nIncumbent PE fund life expiring in 18 months — liquidity pressure to exit. 4 years of organic growth remaining before market saturation in current geographies.',
    task: '1. Evaluate secondary buyout rationale. Why is the incumbent selling now?\n\n2. Build IRR model at 16x entry / 14x exit (multiple compression scenario).\n\n3. Identify what new value creation levers remain after 6 years of PE ownership.\n\n4. Recommend: proceed or pass.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Questions seller motivation — fund life expiry creates forced seller dynamics. Analyses remaining value creation levers after 6 years of optimisation. Identifies that revenue per lab has plateaued (₹3.4 Cr) suggesting same-store growth exhaustion.',
      critical_gap: 'Treats the secondary as a normal buyout without questioning what the prior PE fund already optimised. Assumes revenue and margin growth will continue at the same rate without analysing same-store trends.',
      non_obvious_signal: 'In a secondary, the critical question is: what does the new buyer actually do to create value? If the prior fund already optimised margins and lab density, the new buyer is paying a premium for a stabilised asset with limited upside.',
    },
  },
  {
    code: 'PE-005',
    role: 'Private Equity Analyst',
    difficulty: 'Advanced',
    title: 'Turnaround Investment',
    situation: 'Your fund specialises in operational turnarounds. You are evaluating a distressed footwear retailer with strong brand equity but poor operations.',
    company_overview: 'Heritage Footwear Ltd is India\'s 3rd largest footwear retailer. Founded 1978. 340 EBO stores + 1,200 MBO points across India. Brand NPS: 71 (best in category). 3,400 employees (12% above optimal). Promoter willing to sell 70% at ₹420 Cr enterprise value (2.5x EV/Sales).',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['720', '698', '680'] },
        { label: 'EBITDA (₹ Cr)', values: ['79', '28', '8'] },
        { label: 'EBITDA Margin', values: ['11.0%', '4.0%', '1.2%'] },
        { label: 'Working Capital Days', values: ['72', '98', '124'] },
        { label: 'Inventory (₹ Cr)', values: ['110', '168', '210'] },
        { label: 'Slow-Moving Inventory (₹ Cr)', values: ['—', '—', '22'] },
        { label: 'Debt (₹ Cr)', values: ['120', '150', '180'] },
        { label: 'Debt Interest Rate', values: ['11%', '12%', '13.5%'] },
        { label: 'Mature Store EBITDA Margin (pre-FY23)', values: ['19%', '—', '—'] },
      ],
    },
    market_context: 'Indian footwear market growing 12% CAGR but shifting online. D2C footwear brands gaining share in metro markets. Heritage brands retain strong loyalty in Tier 2-3 cities.\n\nExcess inventory across the retail sector post-COVID. Inventory liquidation at 40-50 paise on the rupee is common for distressed retail situations. Working capital optimisation can unlock 200-400bps of margin improvement in retail turnarounds.',
    task: '1. Diagnose the turnaround thesis. What went wrong in FY23?\n\n2. Model EBITDA recovery to 8% margin within 3 years.\n\n3. Quantify value unlocked by: inventory reduction, store rationalisation, working capital improvement.\n\n4. Build IRR at entry price of ₹420 Cr and project exit at 8x EBITDA in year 4.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Separates structural improvements (AR reduction, AP extension, store closure) from one-time actions (₹22 Cr slow-moving inventory liquidation). Models the inventory liquidation P&L impact separately — markdown loss vs working capital release NPV.',
      critical_gap: 'Proposes a generic cost-cutting plan without identifying the ₹22 Cr slow-moving inventory as a specific problem requiring a specific solution. Ignores the difference between process improvement and one-time actions.',
      non_obvious_signal: 'The ₹22 Cr slow-moving inventory is both the problem and the opportunity. Liquidating at 40-50 paise destroys value short-term but frees working capital and resets the balance sheet. The NPV of working capital release vs markdown loss is the key decision.',
    },
  },
  {
    code: 'PE-006',
    role: 'Private Equity Analyst',
    difficulty: 'Advanced',
    title: 'Sector Roll-Up Strategy',
    situation: 'Your fund has acquired a chain of veterinary clinics as a platform and is evaluating the first add-on acquisition to build a national network.',
    company_overview: 'Platform: PetCare Plus Pvt Ltd — 7 premium veterinary clinics in Mumbai, ₹31 Cr revenue, ₹8.2 Cr EBITDA. Add-on target: Bangalore Pets & Vets Ltd — 6 clinics in Bengaluru, ₹18 Cr revenue, ₹4.1 Cr EBITDA. Asking price: ₹52 Cr (12.7x EBITDA).',
    financials: {
      headers: ['', 'Platform', 'Add-on Target', 'Combined (Pro Forma)'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['31', '18', '49'] },
        { label: 'EBITDA (₹ Cr)', values: ['8.2', '4.1', '12.3'] },
        { label: 'EBITDA Margin', values: ['26.5%', '22.8%', '25.1%'] },
        { label: 'Clinics', values: ['7', '6', '13'] },
        { label: 'Veterinarians', values: ['18', '12', '30'] },
        { label: 'Cost Synergies (₹ Cr)', values: ['—', '—', '1.8'] },
        { label: 'Revenue Synergies (₹ Cr)', values: ['—', '—', '0.8'] },
        { label: 'Platform Entry Valuation (x EBITDA)', values: ['11x', '—', '—'] },
        { label: 'Target Asking (x EBITDA)', values: ['—', '12.7x', '—'] },
      ],
    },
    market_context: 'Indian petcare market growing 21% CAGR. Veterinary services highly fragmented — 94% are single-clinic owners. National chains command 15-18x EBITDA at exit vs 8-10x for single clinics.\n\nKey constraint in scaling vet clinics is veterinarian availability — India has 0.4 vets per 10,000 pets vs 3.2 in the US. Vet retention post-acquisition is the primary integration risk.',
    task: '1. Evaluate the add-on acquisition at 12.7x EBITDA.\n\n2. Model combined platform value creation. Calculate synergy-adjusted IRR.\n\n3. Assess whether the entry multiple is justified by the roll-up premium.\n\n4. Build a 6→30 clinic growth model showing platform value compounding.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies vet availability as the binding constraint in scaling, not capital. Recommends that the roll-up thesis depends on retaining target vets post-acquisition and building a vet training and retention programme.',
      critical_gap: 'Models the roll-up purely as a financial exercise (buy at 12x, exit at 16x) without considering operational bottlenecks. Ignores the human capital constraint.',
      non_obvious_signal: 'Vet availability — not capital — is the binding constraint. The roll-up thesis depends on retaining the target\'s vets post-acquisition. If key vets leave, the acquisition destroys value because patients follow vets, not clinic brands.',
    },
  },
  {
    code: 'PE-007',
    role: 'Private Equity Analyst',
    difficulty: 'Advanced',
    title: 'Exit Strategy Analysis',
    situation: 'Your fund has held an agri-tech company for 4 years. The fund needs to exit within 12 months. You must evaluate and recommend the optimal exit route.',
    company_overview: 'KisanMitra Agritech Pvt Ltd is a precision agriculture SaaS platform. Connects farmers with soil testing, crop advisory, and input marketplace. 340,000 active farmer users. Fund entry: 4 years ago at ₹80 Cr for 40% stake.',
    financials: {
      headers: ['', 'Entry (4 yrs ago)', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['12', '31', '42'] },
        { label: 'EBITDA (₹ Cr)', values: ['-4', '3.2', '6.8'] },
        { label: 'ARR Growth YoY', values: ['—', '42%', '34%'] },
        { label: 'Active Farmer Users', values: ['82,000', '260,000', '340,000'] },
        { label: 'NPS', values: ['—', '74', '78'] },
        { label: '40% Stake Carrying Value (₹ Cr)', values: ['80', '110', '140'] },
        { label: 'Interested Strategic Acquirers', values: ['—', '—', '3'] },
        { label: 'Interested PE Secondary Buyers', values: ['—', '—', '2'] },
      ],
    },
    market_context: 'Indian agritech sector attracted $2.1B of VC/PE funding in last 5 years. Strategic acquirers see value in farmer relationships and crop data for input distribution, credit, and procurement.\n\nIPO route is limited — EBITDA too small for standalone listing (minimum ₹50 Cr EBITDA expected by Indian IPO investors). Strategic value is significantly higher than financial value for this asset.',
    task: '1. Evaluate each exit route:\n   - 3 strategic acquirers (FMCG, agri-input, bank)\n   - 2 PE secondary buyers\n   - IPO\n\n2. Recommend the route that maximises fund return within 12 months.\n\n3. Quantify expected proceeds under each route.\n\n4. State the negotiation strategy for your recommended route.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Recognises that strategic value (farmer relationships + data) is higher than financial value (DCF). Models strategic value separately and uses it to negotiate with strategic acquirers rather than accepting PE secondaries at financial multiples.',
      critical_gap: 'Values the company using only DCF or EBITDA multiples, ignoring the strategic premium that farmer data and relationships command. Recommends accepting the highest financial bid without exploring strategic value.',
      non_obvious_signal: 'The 340,000 active farmer relationships and soil/crop data are worth more to a strategic acquirer than any DCF implies. Strategic value should be modelled separately from financial value to capture the real exit opportunity.',
    },
  },

  /* ═══════════════════════════════════════════════
     EXPERT CASES — PE-008 through PE-015
     ═══════════════════════════════════════════════ */

  {
    code: 'PE-008',
    role: 'Private Equity Analyst',
    difficulty: 'Expert',
    title: 'Covenant Breach Management — Kaleidoscope Packaging: The DSCR Breach',
    situation: 'Your fund invested ₹180 Cr for 45% equity in Kaleidoscope Packaging 2 years ago. The company has just reported quarterly results showing DSCR of 1.18x — breaching the 1.35x covenant in the loan agreement. The lender has sent a reservation of rights letter. You have 45 minutes before the IC call.',
    company_overview: 'Kaleidoscope Packaging Ltd — Rigid packaging for pharma and food. Entry EV: ₹400 Cr (9x EBITDA FY22). Entry EBITDA: ₹44 Cr. Fund equity: ₹180 Cr (45%). Management equity: 15%. Remaining 40%: promoter. Revenue FY24: ₹310 Cr. EBITDA FY24: ₹38 Cr (12.3% margin vs 14.2% at entry — compressed). Debt outstanding: ₹165 Cr at 11.5%. Cash balance: ₹12 Cr. Undrawn revolving credit: ₹8 Cr. Next principal payment: ₹20 Cr due in 45 days.',
    financials: {
      headers: ['', 'At Entry (FY22)', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['268', '290', '310'] },
        { label: 'EBITDA (₹ Cr)', values: ['44', '42', '38'] },
        { label: 'EBITDA Margin', values: ['14.2%', '14.5%', '12.3%'] },
        { label: 'Debt Outstanding (₹ Cr)', values: ['140', '155', '165'] },
        { label: 'Interest Rate', values: ['11.0%', '11.0%', '11.5%'] },
        { label: 'Interest Expense (₹ Cr)', values: ['15.4', '17.1', '18.975'] },
        { label: 'Annual Principal Repayment (₹ Cr)', values: ['15', '18', '20'] },
        { label: 'Total Debt Service (₹ Cr)', values: ['30.4', '35.1', '38.975'] },
        { label: 'Reported DSCR', values: ['1.45x', '1.20x', '1.18x (VERIFY)'] },
      ],
    },
    market_context: 'Root cause of margin compression: HDPE raw material cost up 28% YoY (key packaging input). One anchor customer renegotiated pricing down 6% citing competition. A new competitor entered the market with 15% lower pricing on commodity SKUs.\n\nThe company has presented DSCR of 1.18x to the lender. However, interest alone on ₹165 Cr at 11.5% is ₹18.975 Cr, plus principal of ₹20 Cr = ₹38.975 Cr total debt service. EBITDA is ₹38 Cr. Actual DSCR = 0.975x — below 1.0x.',
    task: '1. Recalculate the actual DSCR using the correct debt service figure. The company has presented DSCR of 1.18x to the lender — is this calculation correct? If not, what is the accurate figure?\n\n2. The lender has three options: waive the breach, demand cure, or accelerate the debt. Calculate what happens to the fund\'s equity value under each scenario. Assume acceleration leads to liquidation at 6x EBITDA.\n\n3. The fund can inject ₹40 Cr of additional equity to cure the covenant. Model the return impact: (a) fund injects equity (b) fund does not inject and negotiates a covenant reset. What are the conditions under which equity injection is value-accretive?\n\n4. Recommend the specific actions to take in the next 72 hours with the lender. What is the fund\'s negotiating position and what will you concede?',
    admin_only: {
      strong_response: 'Recalculates DSCR correctly: ₹38 Cr EBITDA ÷ ₹38.975 Cr debt service = 0.975x, not 1.18x. Immediately flags that the company has misrepresented its DSCR to the lender — this is not just a financial problem but a disclosure problem that creates potential lender fraud liability. Addresses the misrepresentation as the most urgent issue before any financial restructuring discussion.',
      critical_gap: 'Accepts the company\'s reported DSCR of 1.18x without verification. Focuses on operational turnaround plans without addressing the lender relationship. Fails to calculate that the actual DSCR is below 1.0x, meaning cash flow does not cover debt service.',
      non_obvious_signal: 'The actual DSCR is approximately 0.975x — below 1.0x — not 1.18x as reported. The company has misrepresented its covenant position. This transforms a "negotiate with lender" problem into a "disclosure and legal risk" problem. The fund must address the misrepresentation before any other action.',
    },
  },
  {
    code: 'PE-009',
    role: 'Private Equity Analyst',
    difficulty: 'Expert',
    title: 'Management Buyout Dynamics — CEO Wants to Buy the Company from the Fund',
    situation: 'The CEO of Zenith Healthcare (a portfolio company) has approached your fund with a management buyout proposal. He wants to buy out the fund\'s 60% stake. Your fund has held the investment for 5 years and was planning a strategic sale. You have 45 minutes to evaluate.',
    company_overview: 'Zenith Healthcare Pvt Ltd — Diagnostic lab network. 58 labs. Fund entry: 5 years ago at ₹160 Cr for 60% (entry EV: ₹267 Cr, 7x EBITDA). Entry EBITDA: ₹38 Cr. Current EBITDA FY24: ₹94 Cr. Current estimated EV: ₹1,128 Cr (12x EBITDA). Fund\'s 60% stake value: ₹677 Cr. CEO holds 5% personal equity. CEO MBO proposal: ₹200 Cr personal wealth, ₹400 Cr bank debt, ₹77 Cr vendor financing from fund at 8% for 3 years. Total: ₹677 Cr — exactly at current estimated EV with no premium.',
    financials: {
      headers: ['', 'At Entry', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['152', '340', '412'] },
        { label: 'EBITDA (₹ Cr)', values: ['38', '78', '94'] },
        { label: 'EBITDA Margin', values: ['25%', '23%', '22.8%'] },
        { label: 'Labs Operating', values: ['22', '48', '58'] },
        { label: 'Entry Valuation (EV)', values: ['₹267 Cr', '—', '—'] },
        { label: 'Current Estimated EV', values: ['—', '—', '₹1,128 Cr (12x)'] },
        { label: 'Strategic Buyer Interest', values: ['—', '—', '14-16x EBITDA'] },
        { label: 'PE Secondary Interest', values: ['—', '—', '12-13x EBITDA'] },
        { label: 'IPO Estimated Valuation', values: ['—', '—', '18-22x EBITDA'] },
      ],
    },
    market_context: 'CEO argument: "I built this business. I know more than any external buyer. A strategic sale will disrupt the culture I\'ve built." CEO\'s 5% personal equity gives him access to all non-public pipeline information — upcoming lab licenses, expansion plans, regulatory approvals. He is offering exactly the current estimate with no premium.\n\nStrategic alternatives: 2 hospital chains have expressed interest at 14-16x EBITDA. 3 PE funds have informally indicated interest at 12-13x. IPO valuations for diagnostics sector: 18-22x EBITDA.',
    task: '1. Calculate the fund\'s return under all four scenarios: MBO at current estimate, strategic sale at 15x, PE secondary at 12.5x, IPO at 20x (with 6-month lockup and 15% listing discount). Include gross IRR and MOIC for each scenario.\n\n2. The CEO\'s MBO offers no premium to current estimated value. What premium should the fund demand and why? What is the fair price for a controlling stake with a buyer who has information advantage?\n\n3. The CEO is requesting vendor financing (₹77 Cr at 8% for 3 years from the fund). What are the risks of the fund providing this? What covenants would you require?\n\n4. Your IC is split: half want to support the CEO (long working relationship), half want to run a full process for maximum return. Recommend what to do and address the fiduciary duty dimension specifically — does the fund owe more to its LPs (maximum return) or to the CEO (relationship)?',
    admin_only: {
      strong_response: 'Identifies the information asymmetry as the primary issue: the CEO has access to non-public information and is offering exactly the current estimate — no premium. If the CEO believes the company is worth more (which his insider knowledge likely confirms), the fund\'s fiduciary duty to LPs requires running a competitive process rather than accepting the MBO.',
      critical_gap: 'Evaluates the MBO on financial terms alone without identifying the information asymmetry problem. Accepts that "CEO knows the business best" as an argument FOR the MBO rather than recognising it as the key reason TO run a competitive process.',
      non_obvious_signal: 'The CEO has a 5% personal stake and full access to pipeline information. He is offering exactly the current estimate with zero premium. This information asymmetry is the primary reason to run a competitive process — if the CEO knows something that makes the company worth more, the fund\'s LP fiduciary duty requires not accepting the no-premium offer.',
    },
  },
  {
    code: 'PE-010',
    role: 'Private Equity Analyst',
    difficulty: 'Expert',
    title: 'Fund Mechanics and GP/LP Dynamics — Cascade Capital\'s Distribution Waterfall',
    situation: 'You are an analyst at Cascade Capital (a PE fund). The fund is about to make its first exit after 6 years. Before presenting to LPs, your GP needs you to model the exact distribution waterfall and explain why the GP\'s carried interest calculation is being challenged by the largest LP.',
    company_overview: 'Cascade Capital Fund I — Fund size: ₹500 Cr. GP commitment: 2% = ₹10 Cr. LP commitment: 98% = ₹490 Cr. Management fee: 2% per annum on committed capital for 5 years = ₹10 Cr/year = ₹50 Cr total. Carried interest: 20% above 8% hurdle rate (hard hurdle, American waterfall). Catch-up: 100% GP catch-up until 20% carry achieved.',
    financials: {
      headers: ['', 'Company A (Exit)', 'Company B (Held)', 'Companies C-F (Held)'],
      rows: [
        { label: 'Amount Invested', values: ['₹80 Cr', '₹100 Cr', '₹220 Cr'] },
        { label: 'Current Value/Proceeds', values: ['₹220 Cr', '₹60 Cr', '₹290 Cr'] },
        { label: 'Return Multiple', values: ['2.75x', '0.60x', '1.32x'] },
        { label: 'Status', values: ['Exited', 'Unrealised loss', 'Unrealised'] },
        { label: 'Hold Period', values: ['6 years', '—', '—'] },
        { label: 'Preferred Return (8% compounded)', values: ['₹47.2 Cr on ₹80 Cr', '—', '—'] },
        { label: 'LP Dispute', values: ['American vs European waterfall', '—', '—'] },
        { label: 'Mgmt Fees Paid to Date', values: ['₹50 Cr total', '—', '—'] },
      ],
    },
    market_context: 'Under an American waterfall, the GP can take carry on individual exits before the whole fund portfolio is returned. Under a European waterfall, the entire fund must return capital and preferred return before any carry is paid. The LP holding 30% of the fund argues the hurdle should be calculated on the whole fund portfolio.\n\nThe difference in GP carry between the two methods is material — approximately ₹15-20 Cr in this case. Company B is sitting at a ₹40 Cr unrealised loss. The management fee of ₹50 Cr is typically deducted from gross returns in the hurdle calculation.',
    task: '1. Calculate the exact distribution from Company A\'s exit of ₹220 Cr under an American waterfall: (a) Return of capital to LPs (b) Preferred return at 8% (on the ₹80 Cr invested, compounded for 6 years) (c) GP catch-up (d) Remaining split 80/20. Show exact rupee amounts to each party.\n\n2. Recalculate using a European waterfall where carry is calculated on the whole fund. Given Company B is worth ₹60 Cr on ₹100 Cr invested (unrealised loss of ₹40 Cr), what happens to the GP\'s carry entitlement?\n\n3. The management fee of ₹50 Cr is typically deducted from the fund\'s gross returns in the hurdle calculation. Has the GP correctly accounted for this? Show the impact of including vs. excluding management fees in the hurdle base.\n\n4. Advise the GP on how to resolve the LP dispute. Is the LP\'s position legally and commercially valid? What concession should the GP make if any?',
    admin_only: {
      strong_response: 'Calculates both waterfalls precisely and shows the ₹15-20 Cr difference in GP carry. Under European waterfall, the ₹40 Cr unrealised loss on Company B wipes out significant carry entitlement. Correctly includes management fees in the hurdle calculation and shows they materially increase the capital base over which the 8% hurdle must be earned. Identifies that the dispute has merit on both sides — the LPA language determines the legal answer, but commercially the GP should offer a clawback provision.',
      critical_gap: 'Cannot calculate the distribution waterfall correctly or conflates American and European methods. Ignores the management fee impact on hurdle calculation. Treats the LP dispute as either clearly right or clearly wrong without analysing the LPA terms.',
      non_obvious_signal: 'Under American waterfall, the GP takes carry on Company A\'s profit while Company B sits at a ₹40 Cr loss. Under European, the full fund must clear the hurdle first — meaning no carry until Company B\'s loss is absorbed. The difference is approximately ₹15-20 Cr. Both sides have merit; the LPA language is determinative.',
    },
  },
  {
    code: 'PE-011',
    role: 'Private Equity Analyst',
    difficulty: 'Expert',
    title: '100-Day Plan for Highrise Logistics',
    situation: 'Your fund closed the acquisition of Highrise Logistics 3 weeks ago at ₹840 Cr (12x EBITDA). The investment committee approved a target exit at 2.5x MOIC in 5 years. You must present the 100-day operational value creation plan at the post-close IC. You have 45 minutes.',
    company_overview: 'Highrise Logistics Ltd — Last-mile delivery for e-commerce. Revenue FY24: ₹480 Cr. EBITDA FY24: ₹70 Cr (14.6% margin). PAT: ₹28 Cr. Total debt post-acquisition: ₹420 Cr (fund added ₹210 Cr LBO debt). Interest: ₹50 Cr annually. DSCR post-deal: 1.4x (tight). Delivery partners (gig workers): 6,200 across 28 cities. On-time delivery rate: 91.4%. Top 2 clients: 68% of revenue. Revenue per delivery: ₹44. Cost per delivery: ₹38. Contribution per delivery: ₹6. Volume: 300,000 deliveries/month.',
    financials: {
      headers: ['', 'FY24 (Current)', 'Exit Target (Year 5)', 'Gap'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['480', '—', '—'] },
        { label: 'EBITDA (₹ Cr)', values: ['70', '175', '+₹105 Cr'] },
        { label: 'EBITDA Margin', values: ['14.6%', '—', '—'] },
        { label: 'Total Debt (₹ Cr)', values: ['420', '—', '—'] },
        { label: 'DSCR', values: ['1.4x', '—', '—'] },
        { label: 'Cost per Delivery (₹)', values: ['38', '—', '—'] },
        { label: 'Revenue per Delivery (₹)', values: ['44', '—', '—'] },
        { label: 'Customer Concentration (Top 2)', values: ['68%', '—', '—'] },
        { label: 'Gig Worker Regulation Risk', values: ['₹8-12/delivery cost increase', '—', '—'] },
      ],
    },
    market_context: 'Target: 2.5x MOIC on ₹840 Cr = ₹2,100 Cr exit EV. At 12x exit multiple: need ₹175 Cr EBITDA (currently ₹70 Cr — 150% improvement required). The government has proposed classifying gig workers as employees (consultation paper published 2 months ago). If implemented: estimated labour cost increase of ₹8-12 per delivery.\n\nOn 300,000 deliveries/month, the gig worker regulation would add ₹28-43 Cr annual cost — potentially wiping out EBITDA entirely. Additionally, DSCR of 1.4x is tight. If EBITDA falls, DSCR drops below covenant levels.',
    task: '1. Identify the five highest-impact operational levers to grow EBITDA from ₹70 Cr to ₹175 Cr over 5 years. Quantify the EBITDA contribution of each lever specifically.\n\n2. The gig worker reclassification regulation adds ₹8-12 per delivery in cost — ₹28-43 Cr annual EBITDA impact. Model how this changes the exit scenario. At what volume growth rate does the business still achieve 2.5x MOIC despite this headwind?\n\n3. The 100-day plan must be specific. For each of the first three months, state exactly one operational priority, the decision that needs to be made, and the metric that proves it worked.\n\n4. The fund paid 12x EBITDA for a business with 68% customer concentration and tightening gig worker regulation. With 3 weeks of ownership, identify the one assumption most likely to be wrong and how to address it.',
    admin_only: {
      strong_response: 'Models the DSCR impact of the gig worker regulation: if EBITDA falls by ₹28-43 Cr, DSCR drops to approximately 0.6-0.8x — a covenant breach. Recognises the regulatory risk is not just a value creation problem but an existential covenant risk. Addresses both the MOIC impact AND the debt service coverage impact in the same analysis.',
      critical_gap: 'Lists generic operational improvements (pricing, efficiency, new clients) without quantifying each lever specifically. Models the regulatory risk impact on EBITDA only, ignoring the DSCR covenant cascade. Presents a 100-day plan that reads like a management consulting deck rather than specific, measurable actions.',
      non_obvious_signal: 'The DSCR of 1.4x post-deal is tight. If the gig worker regulation passes and EBITDA falls by ₹28-43 Cr, DSCR drops to approximately 0.6-0.8x — a covenant breach. The regulatory risk is not just a value creation problem — it is an existential covenant risk that must be modelled separately.',
    },
  },
  {
    code: 'PE-012',
    role: 'Private Equity Analyst',
    difficulty: 'Expert',
    title: 'Co-Investment Evaluation — Should We Co-Invest in Atlas Specialty Chemicals?',
    situation: 'A larger PE fund (lead investor) has offered your fund a co-investment opportunity in Atlas Specialty Chemicals. The lead fund has already done 6 months of diligence and is offering co-investors a reduced fee/carry structure but expects a decision in 72 hours. You have 45 minutes.',
    company_overview: 'Lead fund: Investing ₹300 Cr for 60% equity at 12x EV/EBITDA. Co-investment offered: ₹80 Cr for 16% equity. Economics: 0% management fee, 10% carry (vs lead\'s 2%/20%). No Board seat. No veto on exit. Tag-along and drag-along rights only. Atlas Specialty Chemicals: Custom chemical synthesis for pharma/agrochemical. Revenue FY24: ₹520 Cr. EBITDA: ₹109 Cr (21% margin). PAT: ₹68 Cr. Net debt: ₹48 Cr. Top 3 customers: 52% of revenue. ROCE: 24%. Capex plan: ₹180 Cr over 3 years to double capacity.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['380', '448', '520'] },
        { label: 'EBITDA (₹ Cr)', values: ['76', '90', '109'] },
        { label: 'EBITDA Margin', values: ['20%', '20.1%', '21%'] },
        { label: 'PAT (₹ Cr)', values: ['44', '54', '68'] },
        { label: 'ROCE', values: ['22%', '23%', '24%'] },
        { label: 'Co-invest Economics', values: ['—', '—', '0% fee / 10% carry'] },
        { label: 'Board Representation', values: ['—', '—', 'None'] },
        { label: 'Exit Veto Rights', values: ['—', '—', 'None'] },
        { label: 'Decision Timeline', values: ['—', '—', '72 hours'] },
      ],
    },
    market_context: 'Lead fund thesis: Specialty chemicals for pharma growing 18% CAGR. China+1 strategy driving Indian manufacturers. Capacity expansion will 3x EBITDA by Year 5. Lead fund has completed 6 months of diligence. Your fund has 72 hours — enough for a management presentation and basic financial review, but not full operational or commercial diligence.\n\nCo-investment without board representation means your fund has no ability to control exit timing or price. The lead fund can drag you along at any price they choose (subject to tag-along). If the lead fund\'s LPs need liquidity in Year 3, they can force an early exit at a suboptimal price.',
    task: '1. Calculate returns under three exit scenarios: (a) Lead fund exits at 5 years at 16x EBITDA (bull) (b) Exit at 12x (base) (c) Exit at 9x (bear). Include your carry economics. Compare to deploying ₹80 Cr in a deal where you have board control.\n\n2. Identify three specific risks unique to co-investment (as opposed to lead investment) that your IC must understand before approving.\n\n3. The 72-hour deadline is a pressure tactic. What diligence can you realistically complete in 72 hours that would change your decision? What cannot be done in that timeframe?\n\n4. Recommend whether to co-invest with a specific condition list. If no — what would need to be true about the deal to change it?',
    admin_only: {
      strong_response: 'Identifies exit alignment as the critical co-investment risk — not just lack of diligence time or reduced governance. Without board representation, the lead fund controls exit timing. If the lead\'s LPs need liquidity in Year 3, they can force an early exit, dragging the co-investor along. Quantifies the IRR difference between a Year 3 forced exit vs a Year 5 optimal exit.',
      critical_gap: 'Focuses entirely on the 72-hour diligence constraint and the attractive 0% fee/10% carry economics. Treats co-investment as "same deal, better economics" without analysing the governance and exit alignment risks. Assumes the lead fund\'s exit interests are aligned with theirs.',
      non_obvious_signal: 'Co-investment without board representation means your fund has no control over exit timing or price. The lead fund can drag you along. If the lead fund\'s LPs need liquidity in Year 3, they can force an early exit at a suboptimal price. Exit alignment is the critical risk — not the lack of diligence time.',
    },
  },
  {
    code: 'PE-013',
    role: 'Private Equity Analyst',
    difficulty: 'Expert',
    title: 'Platform Acquisition Stress Test — Vertex Hospitals: Build or Crack?',
    situation: 'Your fund\'s platform hospital company (Vertex Hospitals) has made 4 acquisitions in 18 months and is proposing a 5th. The CFO is warning that integration capacity is stretched. Your IC wants an honest assessment of whether the roll-up is working before approving acquisition #5.',
    company_overview: 'Vertex Hospitals Pvt Ltd — Primary care and diagnostics network. Fund investment: ₹220 Cr for 55% stake. Original thesis: 10 acquisitions over 5 years, exit at 15x EBITDA, MOIC target: 3.5x. Total invested to date: ₹220 Cr (platform) + ₹223 Cr (4 acquisitions) = ₹443 Cr fund capital deployed. Proposed Acq #5: ₹120 Cr for 18 clinics in Rajasthan.',
    financials: {
      headers: ['', 'Invested (₹ Cr)', 'Underwritten EBITDA', 'Actual EBITDA', 'Miss %'],
      rows: [
        { label: 'Acq #1 (Month 1) — 3 clinics, MH', values: ['28', '₹6.0 Cr', '₹4.2 Cr', '-30%'] },
        { label: 'Acq #2 (Month 4) — 5 clinics, KA', values: ['45', '₹9.0 Cr', '₹5.1 Cr', '-43%'] },
        { label: 'Acq #3 (Month 9) — 8 clinics, TN', values: ['62', '₹11.4 Cr', '₹3.8 Cr', '-67%'] },
        { label: 'Acq #4 (Month 14) — 12 clinics, NCR', values: ['88', '₹16.8 Cr', '₹2.1 Cr', '-88%'] },
        { label: 'Proposed Acq #5 — 18 clinics, RJ', values: ['120', '₹22.0 Cr', '?', '?'] },
        { label: 'Integration Completion %', values: ['100%', '70%', '30%', '5%'] },
        { label: 'Total Fund Capital Deployed', values: ['—', '—', '—', '₹443 Cr'] },
      ],
    },
    market_context: 'Management argument: "Each acquisition gets us closer to scale. EBITDA will come once integration is complete." However, the EBITDA miss is accelerating — Acq #1 missed by 30%, Acq #2 by 43%, Acq #3 by 67%, Acq #4 by 88%. This pattern suggests management bandwidth is the binding constraint, not integration timing.\n\nHealthcare clinic roll-ups typically underperform because patient volumes follow individual doctors, not clinic brands. When doctors leave post-acquisition (which happens in 30-40% of cases), patient revenue follows them out the door.',
    task: '1. Calculate the integration performance score across acquisitions #1-4. Build a metric: actual EBITDA as % of underwritten EBITDA at current integration completion %. What does the trend tell you?\n\n2. Management argues "EBITDA will come once integration is complete." Test this: if all 4 acquisitions achieved 100% of underwritten EBITDA eventually, what total EBITDA would the platform produce? What multiple of fund capital does that represent?\n\n3. Identify the specific operational reason why healthcare clinic roll-ups typically underperform underwriting assumptions. Use the data to support your argument.\n\n4. Recommend whether to approve acquisition #5. If no — what specific metrics must be achieved in acquisitions #1-4 before you would approve the next deal?',
    admin_only: {
      strong_response: 'Identifies the worsening trend — misses of 30%, 43%, 67%, 88% — not just the absolute numbers. This is the classic roll-up failure mode: management bandwidth is the binding constraint and it degrades with each additional acquisition. Extrapolates that Acq #5 will likely miss by 80%+ based on trend. Recommends a moratorium on acquisitions until Acqs #1-3 reach 80%+ of underwritten EBITDA.',
      critical_gap: 'Treats each acquisition miss independently rather than identifying the worsening trend. Accepts the "integration takes time" argument without testing it against the accelerating miss pattern. Recommends proceeding because the thesis calls for 10 acquisitions.',
      non_obvious_signal: 'The pattern is not "integration takes time" — the pattern is "each acquisition is harder to integrate than the last." This is the classic roll-up failure mode: management bandwidth is the binding constraint and it degrades with each additional deal. Strong candidates identify the worsening trend and flag that Acq #5 will likely miss by 80%+ based on trend extrapolation.',
    },
  },
  {
    code: 'PE-014',
    role: 'Private Equity Analyst',
    difficulty: 'Expert',
    title: 'Secondaries and LP Interests — Buying an LP Stake in a Maturing Fund',
    situation: 'An institutional LP is selling its ₹80 Cr commitment in a 7-year-old PE fund (Fund IV by Prism Capital). You are evaluating whether to buy this LP interest in the secondary market at a proposed price of 85 cents on the dollar (NAV).',
    company_overview: 'Prism Capital Fund IV — Total fund size: ₹600 Cr. Vintage year: 2019. Current NAV: ₹840 Cr (reported by GP, unaudited). LP interest being sold: ₹80 Cr original commitment = 13.3% of fund. LP has received ₹45 Cr in distributions to date. Portfolio: 3 strong performers (estimated ₹380 Cr, IPO/M&A exit likely in 12-18 months), 6 stable mediocre (estimated ₹280 Cr, 2-4 year hold), 3 underperformers (your estimate ₹90 Cr vs GP\'s ₹110 Cr).',
    financials: {
      headers: ['', 'Strong (3 cos)', 'Stable (6 cos)', 'Underperformers (3 cos)'],
      rows: [
        { label: 'Your Estimated Value', values: ['₹380 Cr', '₹280 Cr', '₹90 Cr'] },
        { label: 'GP Reported Value', values: ['₹380 Cr', '₹350 Cr', '₹110 Cr'] },
        { label: 'GP NAV Total', values: ['—', '—', '₹840 Cr'] },
        { label: 'Your NAV Estimate', values: ['—', '—', '₹750 Cr'] },
        { label: 'Proposed Price (85% of GP NAV)', values: ['—', '—', '₹95 Cr'] },
        { label: 'Your Price (85% of YOUR NAV)', values: ['—', '—', '₹84 Cr'] },
        { label: 'LP Distributions to Date', values: ['—', '—', '₹45 Cr'] },
        { label: 'Expected Hold to Full Exit', values: ['12-18 months', '2-4 years', '3+ years'] },
      ],
    },
    market_context: 'The NAV of ₹840 Cr exceeds the fund\'s total committed capital of ₹600 Cr — showing a paper gain of 40%. However, GP marks on underperformers are often inflated to maintain management fee relevance. Your estimate for underperformers is ₹90 Cr vs GP\'s ₹110 Cr — a 22% overstatement.\n\nSecondary market dynamics: Sellers typically accept 10-20% discount to NAV for liquidity. Buyers earn returns through the discount AND through future value appreciation. The J-curve for secondaries is shorter since you enter a maturing fund.',
    task: '1. Build your own NAV estimate using the portfolio data. Compare to the GP\'s reported ₹840 Cr. What discount to reported NAV is implied by your analysis?\n\n2. The GP reports underperformers at ₹110 Cr but your estimate is ₹90 Cr. How do you challenge the GP\'s valuation in a secondary diligence process given you have no direct access to portfolio company financials?\n\n3. Calculate IRR and MOIC for the secondary buyer under three scenarios: (a) NAV accurate, exit in 3 years at 1.2x NAV (b) NAV overstated by 15%, exit in 3 years at 1.2x true NAV (c) Top 3 exit at full value, rest return cost only.\n\n4. What price would you offer and why? If the seller demands 90 cents on the dollar, do you walk or negotiate?',
    admin_only: {
      strong_response: 'Recalculates true NAV at approximately ₹750 Cr (not ₹840 Cr), implying the 85% headline discount is actually only 95% of true NAV — barely a discount at all. GP marks on underperformers are inflated by 22%, and stable companies may also be marked optimistically. Negotiates based on true NAV, not GP NAV, and offers 78-80 cents on the GP dollar (which is approximately 85-88 cents on true NAV).',
      critical_gap: 'Accepts the GP\'s reported NAV of ₹840 Cr and calculates returns based on 85% of that figure. Does not independently verify the portfolio valuations. Treats the 15% secondary discount as adequate without comparing it to the NAV overstatement.',
      non_obvious_signal: 'The GP reports underperformers at ₹110 Cr when the estimate is ₹90 Cr — a 22% overstatement. For a fund this size, GP marks on underperformers are often inflated to maintain management fee relevance. The headline 15% discount to GP NAV may actually be a 0-5% discount to true NAV once you haircut the underperformers.',
    },
  },
  {
    code: 'PE-015',
    role: 'Private Equity Analyst',
    difficulty: 'Expert',
    title: 'Portfolio Company Exit Complexity — Four Bidders, Four Structures, Which Deal?',
    situation: 'Your fund\'s portfolio company (Meridian EdTech) has received four acquisition offers after a formal M&A process. The offers have materially different structures. Your fund must choose one within 5 days. You have 45 minutes.',
    company_overview: 'Meridian EdTech Pvt Ltd — Online skills platform for working professionals. Fund investment: ₹90 Cr for 40% equity (5 years ago). Revenue FY24: ₹280 Cr. EBITDA FY24: ₹52 Cr. Current 40% stake value at recent comparable: ₹208-260 Cr. Fund approaching end of life — must exit within 6 months.',
    financials: {
      headers: ['', 'Offer A', 'Offer B', 'Offer C', 'Offer D'],
      rows: [
        { label: 'Bidder', values: ['Large EdTech', 'Global PE Fund', 'US-Listed EdTech', 'Indian HNI Consortium'] },
        { label: 'Enterprise Value', values: ['₹600 Cr (11.5x)', '₹720 Cr (13.8x)', '₹650 Cr (12.5x)', '₹780 Cr (15x)'] },
        { label: 'Cash at Closing', values: ['100%', '70%', '20%', '50%'] },
        { label: 'Non-Cash Component', values: ['None', '30% rollover equity', '80% US-listed stock', '50% seller note (24-mo)'] },
        { label: 'Regulatory Risk', values: ['CCI (30-45 days)', 'None', 'FEMA+RBI (90-120 days)', 'None'] },
        { label: 'Deal Certainty', values: ['High', 'Medium', 'Low', 'Medium'] },
        { label: 'Fund Constraint', values: ['—', 'Cannot hold rollover equity', 'FX risk + lockup', '₹390 Cr deferred'] },
        { label: 'Fund\'s 40% Cash Proceeds', values: ['₹240 Cr', '₹168 Cr cash', '₹52 Cr cash', '₹195 Cr now'] },
      ],
    },
    market_context: 'The fund is approaching end of life and must exit within 6 months. This creates a hard constraint that eliminates options requiring extended timelines. Offer B requires the fund to hold rollover equity — which it cannot do if the fund is winding down. Offer C requires FEMA/RBI approval that may take 90-120 days, and the 80% stock consideration creates FX risk.\n\nOffer D has the highest headline at ₹780 Cr but only 50% is cash upfront — the remaining ₹390 Cr is a seller note over 24 months at 9% interest. The HNI consortium\'s ability to honor the deferred payment depends on their balance sheet strength.',
    task: '1. Calculate the risk-adjusted value of each offer to the fund\'s 40% stake. Discount non-cash components for illiquidity, timing, and counterparty risk. Rank the offers on risk-adjusted value, not headline value.\n\n2. The fund cannot hold rollover equity (Offer B) and must exit within 6 months (constraining Offer C). How do these constraints change your analysis? Which offers are structurally feasible?\n\n3. Offer D offers the highest headline (₹780 Cr) but half is deferred. Calculate the NPV of the deferred component at a 15% discount rate (reflecting counterparty risk). Compare to Offer A\'s lower but all-cash value.\n\n4. Recommend one offer with specific reasoning. Address what happens if your recommended deal falls through — what is your fallback?',
    admin_only: {
      strong_response: 'Eliminates Offers B and C immediately due to structural infeasibility (fund cannot hold rollover equity; FEMA timeline exceeds fund life). Between A and D: calculates NPV of Offer D\'s deferred payment (₹390 Cr over 24 months at 15% discount = approximately ₹310-320 Cr NPV) and shows that Offer A\'s all-cash ₹600 Cr yields ₹240 Cr to the fund vs Offer D\'s risk-adjusted ₹195 Cr + ₹124-128 Cr = ₹319-323 Cr. The analysis hinges on counterparty risk assessment of the HNI consortium.',
      critical_gap: 'Compares headline enterprise values (₹780 Cr > ₹720 Cr > ₹650 Cr > ₹600 Cr) and recommends the highest without risk-adjusting for structure. Fails to eliminate structurally infeasible offers. Ignores the fund\'s end-of-life constraint.',
      non_obvious_signal: 'Offer D\'s headline of ₹780 Cr is highest, but with 50% deferred and counterparty risk, the risk-adjusted value to the fund may actually be lower than Offer A\'s clean ₹600 Cr all-cash. The fund\'s end-of-life constraint makes deal certainty and cash-at-closing more valuable than headline price. Strong candidates discount non-cash components and rank on risk-adjusted proceeds.',
    },
  },
];

