import type { DealCase } from './types';

export const PE_CASES: DealCase[] = [
  {
    code: 'PE-001',
    role: 'Private Equity Analyst',
    difficulty: 'Intermediate',
    title: 'Control Buyout — Food Services',
    situation: 'Your fund (₹2,000 Cr mid-market PE) is evaluating a control buyout of a quick service restaurant chain. You have 90 minutes to build the investment thesis.',
    company_overview: 'Spice Route QSR Pvt Ltd is a South Indian QSR chain. Founded 2014. 78 outlets across Karnataka, Tamil Nadu, Kerala. Mix: 31 owned, 47 franchised.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['128', '156', '184'] },
        { label: 'System Sales incl. Franchise (₹ Cr)', values: ['192', '231', '267'] },
        { label: 'EBITDA (₹ Cr)', values: ['18', '24', '31'] },
        { label: 'EBITDA Margin', values: ['14.1%', '15.4%', '16.8%'] },
        { label: 'Owned Store EBITDA Margin', values: ['19%', '21%', '22%'] },
        { label: 'Franchise Royalty Margin', values: ['92%', '93%', '94%'] },
        { label: 'New Store Payback (months)', values: ['30', '28', '26'] },
        { label: 'Same-Store Sales Growth', values: ['5.8%', '6.4%', '7.2%'] },
        { label: 'Total Debt (₹ Cr)', values: ['22', '24', '28'] },
      ],
    },
    market_context: 'Indian QSR market growing 18% CAGR. South Indian cuisine is the fastest-growing segment. Franchise-heavy models commanding premium valuations (18-22x EBITDA) vs owned-store models (12-15x).\n\nKey risk: Labour cost inflation in food services averaging 8-10% annually. Rental escalations in mall/high-street locations averaging 6% annually.',
    task: '1. Build the investment thesis for a control buyout.\n\n2. Model LBO at 16x entry (negotiated down from 18x asking). Assume 55% debt at 11% interest.\n\n3. Identify the top value creation levers.\n\n4. Project exit at 14-18x EBITDA in year 5. Calculate IRR sensitivity across entry and exit multiples.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Models franchise economics separately from owned stores. Identifies franchise mix (94% margin) as the real asset. Recommends accelerating owned-to-franchised conversion as the primary value creation lever.',
      critical_gap: 'Treats all 78 outlets as identical. Misses the economic difference between owned (22% margin) and franchised (94% royalty margin) stores. Uses blended EBITDA without segmenting.',
      non_obvious_signal: 'Franchise mix matters more than total revenue. The capital-light franchise model at 94% margin is the real asset. The value creation plan should push owned-to-franchised conversion, not just expand store count.',
    },
  },
  {
    code: 'PE-002',
    role: 'Private Equity Analyst',
    difficulty: 'Intermediate',
    title: 'Growth Equity — EdTech',
    situation: 'Your fund is evaluating a ₹120 Cr Series C growth equity investment in an edtech company focused on upskilling working professionals.',
    company_overview: 'UpGrade Professionals Pvt Ltd is an online upskilling platform based in Bengaluru. Founded 2017. Programs: Data Science, Product Management, Finance, Digital Marketing. 14,200 learners enrolled in FY24.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['42', '68', '98'] },
        { label: 'Gross Margin', values: ['54%', '56%', '58%'] },
        { label: 'EBITDA (₹ Cr)', values: ['-18', '-22', '-24'] },
        { label: 'CAC per Learner (₹)', values: ['14,200', '16,400', '18,400'] },
        { label: 'Course Completion Rate', values: ['62%', '65%', '67%'] },
        { label: 'Placement Rate (of completers)', values: ['68%', '70%', '71%'] },
        { label: 'Avg Salary Increment Post-Course', values: ['28%', '31%', '34%'] },
        { label: 'Refund Rate', values: ['9.8%', '8.8%', '8.2%'] },
        { label: 'Cohort Revenue Retention (12-mo)', values: ['18%', '20%', '22%'] },
      ],
    },
    market_context: 'Indian online education market at $6B, growing 32% CAGR. However, edtech funding has declined 70% from 2021 peak. Investors now demand path to profitability, not just growth.\n\nCompetitor models are shifting to subscription-based or bundled course offerings that generate higher LTV. Single-course models face CAC inflation as platforms compete for the same learner pool.',
    task: '1. Evaluate the ₹120 Cr investment at ₹680 Cr post-money valuation.\n\n2. Build a 5-year financial model. Assess path to profitability.\n\n3. Identify the 3 risks that could prevent the fund from returning 3x.\n\n4. Recommend: invest / do not invest. Defend your thesis.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Flags low cohort revenue retention (22%) as the fundamental weakness. The business depends on continuously acquiring new learners at rising CAC rather than monetising existing relationships. Compares to subscription models and identifies LTV/CAC deterioration.',
      critical_gap: 'Focuses on topline growth (42→98 Cr) and placement rates without questioning the customer acquisition cost trajectory. Treats 22% cohort retention as acceptable without benchmarking.',
      non_obvious_signal: 'Low cohort revenue retention at 22% is the critical unit economics problem. The business model is a leaky bucket — it must continuously acquire expensive new learners. Compare to competitors offering subscription bundles with 60%+ retention.',
    },
  },
  {
    code: 'PE-003',
    role: 'Private Equity Analyst',
    difficulty: 'Advanced',
    title: 'Portfolio Company Monitoring',
    situation: 'You are the deal analyst covering Brightfield Energy Solutions — a portfolio company your fund invested in 18 months ago. The company has missed its EBITDA target by 31% in Year 1. Your MD wants a situation analysis and recovery plan.',
    company_overview: 'Brightfield Energy Solutions is a Solar EPC (Engineering, Procurement, Construction) company. Fund investment: ₹85 Cr for 34% equity at ₹250 Cr valuation.',
    financials: {
      headers: ['', 'Target Y1', 'Actual Y1', 'Variance'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['280', '204', '-27%'] },
        { label: 'EBITDA (₹ Cr)', values: ['42', '29', '-31%'] },
        { label: 'EBITDA Margin', values: ['15.0%', '14.2%', '-80bps'] },
        { label: 'Cash Position (₹ Cr)', values: ['28', '18', '-36%'] },
        { label: 'Debt (₹ Cr)', values: ['60', '65', '+8%'] },
        { label: 'DSCR', values: ['1.45x', '1.21x', 'Below covenant'] },
        { label: 'Pipeline — Signed LOIs (₹ Cr)', values: ['—', '340', 'Strong'] },
        { label: 'Debt Interest Rate', values: ['—', '12.5%', '—'] },
        { label: 'Covenant DSCR Floor', values: ['—', '1.30x', 'Breached'] },
      ],
    },
    market_context: 'Indian solar sector growing rapidly but project execution depends on government grid connectivity approvals which can delay projects 3-6 months. Customer bankruptcy risk is elevated in the commercial solar segment.\n\nRBI has tightened DSCR covenant enforcement — lenders are more proactive about accelerating debt when covenants are breached. Typical response time: 90 days from breach notification.',
    task: '1. Diagnose which miss drivers are structural vs temporary:\n   - Project delays (government approvals)\n   - Customer bankruptcies (₹38 Cr revenue lost)\n   - Equipment cost overruns (8% above budget)\n\n2. Assess debt covenant breach risk and options.\n\n3. Build a recovery scenario for Year 2.\n\n4. Recommend: provide bridge financing (₹25 Cr) or begin strategic options.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies the DSCR covenant breach (1.21x vs 1.30x covenant) as the most urgent issue — not the revenue miss. Addresses lender intervention risk before recovery planning. Recommends securing a covenant waiver or amendment as the immediate priority.',
      critical_gap: 'Focuses on the revenue miss and builds a recovery plan without addressing the covenant breach. Fails to recognise that lenders can accelerate debt within 90 days, making the recovery plan moot.',
      non_obvious_signal: 'The DSCR covenant breach is time-critical and will trigger lender intervention if not addressed before the next quarterly test. This is more urgent than the revenue miss — you cannot recover if lenders accelerate the debt.',
    },
  },
  {
    code: 'PE-004',
    role: 'Private Equity Analyst',
    difficulty: 'Advanced',
    title: 'Secondary Buyout',
    situation: 'Your fund is considering buying a 60% stake from an incumbent PE fund that has held the asset for 6 years. This is a secondary buyout.',
    company_overview: 'ClearPath Diagnostics Pvt Ltd is a pathology lab network with 62 labs across Maharashtra, Gujarat, and MP. Founded 2011. PE-backed since 2018. Incumbent fund asking 16x EBITDA.',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['168', '189', '210'] },
        { label: 'EBITDA (₹ Cr)', values: ['40', '46', '52'] },
        { label: 'EBITDA Margin', values: ['23.8%', '24.3%', '24.8%'] },
        { label: 'Capex (₹ Cr)', values: ['10', '12', '14'] },
        { label: 'Free Cash Flow (₹ Cr)', values: ['24', '28', '31'] },
        { label: 'Debt (₹ Cr)', values: ['52', '46', '40'] },
        { label: 'Labs Operating', values: ['48', '55', '62'] },
        { label: 'Revenue per Lab (₹ Cr)', values: ['3.5', '3.4', '3.4'] },
        { label: 'Tests per Day (avg across network)', values: ['12,400', '14,200', '15,800'] },
      ],
    },
    market_context: 'Indian diagnostics market growing 14% CAGR. Consolidation trend — large chains acquiring single-lab operators at 6-8x EBITDA. Network effects: more labs = better brand = higher volume per lab.\n\nIncumbent PE fund life expiring in 18 months — liquidity pressure to exit. 4 years of organic growth remaining before market saturation in current geographies.',
    task: '1. Evaluate secondary buyout rationale. Why is the incumbent selling now?\n\n2. Build IRR model at 16x entry / 14x exit (multiple compression scenario).\n\n3. Identify what new value creation levers remain after 6 years of PE ownership.\n\n4. Recommend: proceed or pass.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Questions seller motivation — fund life expiry creates forced seller dynamics. Analyses remaining value creation levers after 6 years of optimisation. Identifies that revenue per lab has plateaued (₹3.4 Cr) suggesting same-store growth exhaustion.',
      critical_gap: 'Treats the secondary as a normal buyout without questioning what the prior PE fund already optimised. Assumes revenue and margin growth will continue at the same rate without analysing same-store trends.',
      non_obvious_signal: 'In a secondary, the critical question is: what does the new buyer actually do to create value? If the prior fund already optimised margins and lab density, the new buyer is paying a premium for a stabilised asset with limited upside.',
    },
  },
  {
    code: 'PE-005',
    role: 'Private Equity Analyst',
    difficulty: 'Advanced',
    title: 'Turnaround Investment',
    situation: 'Your fund specialises in operational turnarounds. You are evaluating a distressed footwear retailer with strong brand equity but poor operations.',
    company_overview: 'Heritage Footwear Ltd is India\'s 3rd largest footwear retailer. Founded 1978. 340 EBO stores + 1,200 MBO points across India. Brand NPS: 71 (best in category). 3,400 employees (12% above optimal). Promoter willing to sell 70% at ₹420 Cr enterprise value (2.5x EV/Sales).',
    financials: {
      headers: ['', 'FY22', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['720', '698', '680'] },
        { label: 'EBITDA (₹ Cr)', values: ['79', '28', '8'] },
        { label: 'EBITDA Margin', values: ['11.0%', '4.0%', '1.2%'] },
        { label: 'Working Capital Days', values: ['72', '98', '124'] },
        { label: 'Inventory (₹ Cr)', values: ['110', '168', '210'] },
        { label: 'Slow-Moving Inventory (₹ Cr)', values: ['—', '—', '22'] },
        { label: 'Debt (₹ Cr)', values: ['120', '150', '180'] },
        { label: 'Debt Interest Rate', values: ['11%', '12%', '13.5%'] },
        { label: 'Mature Store EBITDA Margin (pre-FY23)', values: ['19%', '—', '—'] },
      ],
    },
    market_context: 'Indian footwear market growing 12% CAGR but shifting online. D2C footwear brands gaining share in metro markets. Heritage brands retain strong loyalty in Tier 2-3 cities.\n\nExcess inventory across the retail sector post-COVID. Inventory liquidation at 40-50 paise on the rupee is common for distressed retail situations. Working capital optimisation can unlock 200-400bps of margin improvement in retail turnarounds.',
    task: '1. Diagnose the turnaround thesis. What went wrong in FY23?\n\n2. Model EBITDA recovery to 8% margin within 3 years.\n\n3. Quantify value unlocked by: inventory reduction, store rationalisation, working capital improvement.\n\n4. Build IRR at entry price of ₹420 Cr and project exit at 8x EBITDA in year 4.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Separates structural improvements (AR reduction, AP extension, store closure) from one-time actions (₹22 Cr slow-moving inventory liquidation). Models the inventory liquidation P&L impact separately — markdown loss vs working capital release NPV.',
      critical_gap: 'Proposes a generic cost-cutting plan without identifying the ₹22 Cr slow-moving inventory as a specific problem requiring a specific solution. Ignores the difference between process improvement and one-time actions.',
      non_obvious_signal: 'The ₹22 Cr slow-moving inventory is both the problem and the opportunity. Liquidating at 40-50 paise destroys value short-term but frees working capital and resets the balance sheet. The NPV of working capital release vs markdown loss is the key decision.',
    },
  },
  {
    code: 'PE-006',
    role: 'Private Equity Analyst',
    difficulty: 'Advanced',
    title: 'Sector Roll-Up Strategy',
    situation: 'Your fund has acquired a chain of veterinary clinics as a platform and is evaluating the first add-on acquisition to build a national network.',
    company_overview: 'Platform: PetCare Plus Pvt Ltd — 7 premium veterinary clinics in Mumbai, ₹31 Cr revenue, ₹8.2 Cr EBITDA. Add-on target: Bangalore Pets & Vets Ltd — 6 clinics in Bengaluru, ₹18 Cr revenue, ₹4.1 Cr EBITDA. Asking price: ₹52 Cr (12.7x EBITDA).',
    financials: {
      headers: ['', 'Platform', 'Add-on Target', 'Combined (Pro Forma)'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['31', '18', '49'] },
        { label: 'EBITDA (₹ Cr)', values: ['8.2', '4.1', '12.3'] },
        { label: 'EBITDA Margin', values: ['26.5%', '22.8%', '25.1%'] },
        { label: 'Clinics', values: ['7', '6', '13'] },
        { label: 'Veterinarians', values: ['18', '12', '30'] },
        { label: 'Cost Synergies (₹ Cr)', values: ['—', '—', '1.8'] },
        { label: 'Revenue Synergies (₹ Cr)', values: ['—', '—', '0.8'] },
        { label: 'Platform Entry Valuation (x EBITDA)', values: ['11x', '—', '—'] },
        { label: 'Target Asking (x EBITDA)', values: ['—', '12.7x', '—'] },
      ],
    },
    market_context: 'Indian petcare market growing 21% CAGR. Veterinary services highly fragmented — 94% are single-clinic owners. National chains command 15-18x EBITDA at exit vs 8-10x for single clinics.\n\nKey constraint in scaling vet clinics is veterinarian availability — India has 0.4 vets per 10,000 pets vs 3.2 in the US. Vet retention post-acquisition is the primary integration risk.',
    task: '1. Evaluate the add-on acquisition at 12.7x EBITDA.\n\n2. Model combined platform value creation. Calculate synergy-adjusted IRR.\n\n3. Assess whether the entry multiple is justified by the roll-up premium.\n\n4. Build a 6→30 clinic growth model showing platform value compounding.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Identifies vet availability as the binding constraint in scaling, not capital. Recommends that the roll-up thesis depends on retaining target vets post-acquisition and building a vet training and retention programme.',
      critical_gap: 'Models the roll-up purely as a financial exercise (buy at 12x, exit at 16x) without considering operational bottlenecks. Ignores the human capital constraint.',
      non_obvious_signal: 'Vet availability — not capital — is the binding constraint. The roll-up thesis depends on retaining the target\'s vets post-acquisition. If key vets leave, the acquisition destroys value because patients follow vets, not clinic brands.',
    },
  },
  {
    code: 'PE-007',
    role: 'Private Equity Analyst',
    difficulty: 'Advanced',
    title: 'Exit Strategy Analysis',
    situation: 'Your fund has held an agri-tech company for 4 years. The fund needs to exit within 12 months. You must evaluate and recommend the optimal exit route.',
    company_overview: 'KisanMitra Agritech Pvt Ltd is a precision agriculture SaaS platform. Connects farmers with soil testing, crop advisory, and input marketplace. 340,000 active farmer users. Fund entry: 4 years ago at ₹80 Cr for 40% stake.',
    financials: {
      headers: ['', 'Entry (4 yrs ago)', 'FY23', 'FY24'],
      rows: [
        { label: 'Revenue (₹ Cr)', values: ['12', '31', '42'] },
        { label: 'EBITDA (₹ Cr)', values: ['-4', '3.2', '6.8'] },
        { label: 'ARR Growth YoY', values: ['—', '42%', '34%'] },
        { label: 'Active Farmer Users', values: ['82,000', '260,000', '340,000'] },
        { label: 'NPS', values: ['—', '74', '78'] },
        { label: '40% Stake Carrying Value (₹ Cr)', values: ['80', '110', '140'] },
        { label: 'Interested Strategic Acquirers', values: ['—', '—', '3'] },
        { label: 'Interested PE Secondary Buyers', values: ['—', '—', '2'] },
      ],
    },
    market_context: 'Indian agritech sector attracted $2.1B of VC/PE funding in last 5 years. Strategic acquirers see value in farmer relationships and crop data for input distribution, credit, and procurement.\n\nIPO route is limited — EBITDA too small for standalone listing (minimum ₹50 Cr EBITDA expected by Indian IPO investors). Strategic value is significantly higher than financial value for this asset.',
    task: '1. Evaluate each exit route:\n   - 3 strategic acquirers (FMCG, agri-input, bank)\n   - 2 PE secondary buyers\n   - IPO\n\n2. Recommend the route that maximises fund return within 12 months.\n\n3. Quantify expected proceeds under each route.\n\n4. State the negotiation strategy for your recommended route.\n\nState all assumptions.',
    admin_only: {
      strong_response: 'Recognises that strategic value (farmer relationships + data) is higher than financial value (DCF). Models strategic value separately and uses it to negotiate with strategic acquirers rather than accepting PE secondaries at financial multiples.',
      critical_gap: 'Values the company using only DCF or EBITDA multiples, ignoring the strategic premium that farmer data and relationships command. Recommends accepting the highest financial bid without exploring strategic value.',
      non_obvious_signal: 'The 340,000 active farmer relationships and soil/crop data are worth more to a strategic acquirer than any DCF implies. Strategic value should be modelled separately from financial value to capture the real exit opportunity.',
    },
  },
];
