/* ═══════════════════════════════════════════════
   30-Day Improvement Plans — FinApply.ai
   Pre-authored daily actions for each dimension pair.
   ═══════════════════════════════════════════════ */

export type Dimension = 'FR' | 'ST' | 'RI' | 'DC';
export type ActionType = 'read' | 'practice' | 'calculate' | 'review';

export interface DailyAction {
  day: number;
  dimension: Dimension;
  action: string;
  type: ActionType;
  resource?: string;
}

/** Each key is a sorted dimension pair like "FR_ST". */
export const IMPROVEMENT_PLANS: Record<string, DailyAction[]> = {
  /* ─── Financial Reasoning + Structured Thinking ─── */
  'FR_ST': [
    { day: 1, dimension: 'FR', type: 'read', action: 'Read Damodaran\'s "The Little Book of Valuation" Chapter 1 — understand intrinsic vs relative valuation.', resource: 'Damodaran, NYU Stern' },
    { day: 2, dimension: 'ST', type: 'practice', action: 'Take any company\'s 10-K and write a 1-page investment thesis using the SCQA framework (Situation-Complication-Question-Answer).' },
    { day: 3, dimension: 'FR', type: 'calculate', action: 'Build a 3-statement model for a public company using only their latest annual report. Focus on linking statements correctly.' },
    { day: 4, dimension: 'ST', type: 'review', action: 'Review 3 equity research reports. For each, outline the analyst\'s logical structure — what framework did they use?' },
    { day: 5, dimension: 'FR', type: 'practice', action: 'Calculate WACC for 3 companies in different sectors. Note how capital structure and beta differ by industry.' },
    { day: 6, dimension: 'ST', type: 'practice', action: 'Practice the "pyramid principle": write a 200-word recommendation, then restructure it so the conclusion comes first.' },
    { day: 7, dimension: 'FR', type: 'read', action: 'Study the difference between FCFF and FCFE. When does the choice of free cash flow measure change your valuation?' },
    { day: 8, dimension: 'ST', type: 'calculate', action: 'Create a decision tree for a real M&A deal. Map each decision point to specific financial metrics.' },
    { day: 9, dimension: 'FR', type: 'practice', action: 'Reverse-engineer a company\'s implied growth rate from its current stock price using a DCF framework.' },
    { day: 10, dimension: 'ST', type: 'review', action: 'Read a failed M&A case study. Identify where the analytical framework broke down.' },
    { day: 11, dimension: 'FR', type: 'calculate', action: 'Build a sensitivity table for a DCF showing how changes in WACC and terminal growth affect enterprise value.' },
    { day: 12, dimension: 'ST', type: 'practice', action: 'Write a 500-word memo about any business problem. Time yourself: structure should take 3 minutes, writing should take 12.' },
    { day: 13, dimension: 'FR', type: 'read', action: 'Study comparable company analysis: how do you select comps, which multiples to use, and common pitfalls.' },
    { day: 14, dimension: 'ST', type: 'practice', action: 'Take yesterday\'s comp analysis and present your findings using the "So What?" test — every data point must lead to an insight.' },
    { day: 15, dimension: 'FR', type: 'calculate', action: 'Calculate LBO returns for a hypothetical deal: $500M purchase, 60% leverage, 5x EBITDA entry. What IRR does the sponsor need?' },
    { day: 16, dimension: 'ST', type: 'review', action: 'Read 2 consulting case interviews. Note how top candidates structure their answers vs. average candidates.' },
    { day: 17, dimension: 'FR', type: 'practice', action: 'Compare two companies in the same sector using EV/EBITDA, P/E, and EV/Revenue. Explain which metric is most relevant and why.' },
    { day: 18, dimension: 'ST', type: 'practice', action: 'Practice issue trees: given "revenue declined 15%", build a complete MECE breakdown of possible causes.' },
    { day: 19, dimension: 'FR', type: 'read', action: 'Study working capital management: how changes in DSO, DPO, and DIO affect free cash flow and company valuation.' },
    { day: 20, dimension: 'ST', type: 'calculate', action: 'Build a weighted scoring matrix to evaluate 3 strategic options for a company. Define criteria, weights, and scoring.' },
    { day: 21, dimension: 'FR', type: 'practice', action: 'Analyze a company\'s revenue quality: recurring vs. one-time, organic vs. inorganic, customer concentration.' },
    { day: 22, dimension: 'ST', type: 'practice', action: 'Write a one-page recommendation memo using the Minto Pyramid: key message → supporting arguments → evidence.' },
    { day: 23, dimension: 'FR', type: 'calculate', action: 'Build a merger model: calculate accretion/dilution for a hypothetical all-stock deal between two public companies.' },
    { day: 24, dimension: 'ST', type: 'review', action: 'Review your own writing from Day 12. Identify structural weaknesses and rewrite using tighter logical flow.' },
    { day: 25, dimension: 'FR', type: 'read', action: 'Study credit analysis fundamentals: leverage ratios, coverage ratios, and what rating agencies look for.' },
    { day: 26, dimension: 'ST', type: 'practice', action: 'Given a complex business scenario, create a 2x2 matrix to classify strategic options by feasibility and impact.' },
    { day: 27, dimension: 'FR', type: 'calculate', action: 'Perform a sum-of-the-parts valuation for a conglomerate. When does SOTP diverge significantly from a blended approach?' },
    { day: 28, dimension: 'ST', type: 'practice', action: 'Practice "3 minutes of structure": set a timer and outline your approach to any business case before writing.' },
    { day: 29, dimension: 'FR', type: 'review', action: 'Review all financial models you\'ve built this month. Identify your most common calculation errors.' },
    { day: 30, dimension: 'ST', type: 'practice', action: 'Final exercise: write a complete 45-minute case analysis. Focus on structure first, financial depth second. Then retake your FISS simulation.' },
  ],

  /* ─── Financial Reasoning + Risk Identification ─── */
  'FR_RI': [
    { day: 1, dimension: 'FR', type: 'read', action: 'Study the relationship between margin trends and business risk — when do declining margins signal structural vs. cyclical issues?' },
    { day: 2, dimension: 'RI', type: 'practice', action: 'Read a company\'s 10-K risk factors section. Classify each risk as: operational, financial, regulatory, or market.' },
    { day: 3, dimension: 'FR', type: 'calculate', action: 'Build a sensitivity table showing how revenue decline scenarios affect EBITDA margins, cash flow, and debt covenants.' },
    { day: 4, dimension: 'RI', type: 'review', action: 'Study 3 corporate failures (e.g., WeWork, Theranos, Enron). What risks were visible in the financials before collapse?' },
    { day: 5, dimension: 'FR', type: 'practice', action: 'Analyze a company\'s customer concentration. Calculate revenue at risk if the top client churns.' },
    { day: 6, dimension: 'RI', type: 'practice', action: 'For any public company, identify 5 risks NOT mentioned in their investor presentation but visible in their financials.' },
    { day: 7, dimension: 'FR', type: 'read', action: 'Study how working capital cycles create hidden liquidity risk. When does a profitable company run out of cash?' },
    { day: 8, dimension: 'RI', type: 'calculate', action: 'Build a probability-weighted risk matrix for a company. Assign probability and financial impact to each identified risk.' },
    { day: 9, dimension: 'FR', type: 'practice', action: 'Analyze a company\'s debt maturity schedule. When is refinancing risk highest? What are the covenant implications?' },
    { day: 10, dimension: 'RI', type: 'review', action: 'Read about "second-order risks": risks that emerge from the interaction of two separate risk factors.' },
    { day: 11, dimension: 'FR', type: 'calculate', action: 'Model a scenario where a company loses its second-largest customer. How does this cascade through the financial statements?' },
    { day: 12, dimension: 'RI', type: 'practice', action: 'Practice the "pre-mortem" technique: assume a deal failed. List the top 5 reasons why, working backwards.' },
    { day: 13, dimension: 'FR', type: 'read', action: 'Study how inflation affects different business models. Which margin structures are most vulnerable?' },
    { day: 14, dimension: 'RI', type: 'practice', action: 'Read a recent M&A announcement. Identify 3 integration risks the acquiring company hasn\'t publicly addressed.' },
    { day: 15, dimension: 'FR', type: 'calculate', action: 'Build a break-even analysis for a company: at what revenue level does cash flow turn negative? How quickly could this happen?' },
    { day: 16, dimension: 'RI', type: 'review', action: 'Study supply chain risk: analyze a company\'s supplier concentration and geographic exposure.' },
    { day: 17, dimension: 'FR', type: 'practice', action: 'Analyze the quality of a company\'s earnings: one-time items, accounting choices, revenue recognition timing.' },
    { day: 18, dimension: 'RI', type: 'practice', action: 'Practice identifying "non-obvious" risks: regulatory changes, technology disruption, ESG factors that could affect valuation.' },
    { day: 19, dimension: 'FR', type: 'calculate', action: 'Model the impact of a 200bp interest rate increase on a leveraged company\'s interest coverage and free cash flow.' },
    { day: 20, dimension: 'RI', type: 'review', action: 'Read a short-seller report. Study how they identify financial risks that long-only analysts miss.' },
    { day: 21, dimension: 'FR', type: 'practice', action: 'Analyze a company\'s capital allocation: how much is going to maintenance capex vs. growth capex? What does this signal?' },
    { day: 22, dimension: 'RI', type: 'practice', action: 'For a company in a regulated industry, map the top 3 regulatory risks and their potential financial impact.' },
    { day: 23, dimension: 'FR', type: 'calculate', action: 'Build a 3-scenario model (base, bull, bear) and calculate the expected value of an investment.' },
    { day: 24, dimension: 'RI', type: 'practice', action: 'Practice writing risk mitigation strategies: for each risk, propose a specific, measurable action.' },
    { day: 25, dimension: 'FR', type: 'read', action: 'Study how FX exposure affects multinational companies\' earnings and why hedging strategies matter.' },
    { day: 26, dimension: 'RI', type: 'calculate', action: 'Quantify the "tail risk" for a portfolio: what happens in the 5th percentile scenario?' },
    { day: 27, dimension: 'FR', type: 'practice', action: 'Analyze the relationship between a company\'s revenue mix and its risk profile. Diversification vs. focus.' },
    { day: 28, dimension: 'RI', type: 'review', action: 'Review your risk assessments from this month. Which risks did you initially miss? What pattern do your blind spots follow?' },
    { day: 29, dimension: 'FR', type: 'calculate', action: 'Build a covenant compliance model: at what EBITDA level does the company breach its debt covenants?' },
    { day: 30, dimension: 'RI', type: 'practice', action: 'Final exercise: complete a full case analysis focusing on risk identification. Then retake your FISS simulation.' },
  ],

  /* ─── Financial Reasoning + Decision Clarity ─── */
  'FR_DC': [
    { day: 1, dimension: 'DC', type: 'read', action: 'Study the "newspaper test": if your recommendation appeared as a headline, would it be clear? Read 3 analyst recommendations and evaluate their clarity.' },
    { day: 2, dimension: 'FR', type: 'calculate', action: 'Build a DCF and practice stating your valuation conclusion in one sentence before showing any math.' },
    { day: 3, dimension: 'DC', type: 'practice', action: 'Write 5 investment recommendations in 1 sentence each. Each must include: direction (buy/sell/hold), conviction level, and key condition.' },
    { day: 4, dimension: 'FR', type: 'read', action: 'Study how terminal value assumptions drive DCF outcomes. What does your terminal growth rate assumption actually imply?' },
    { day: 5, dimension: 'DC', type: 'practice', action: 'Practice the "elevator pitch" format: summarize a complex financial analysis in 30 seconds with a clear ask.' },
    { day: 6, dimension: 'FR', type: 'calculate', action: 'Build a comp analysis and state your conclusion first: "Company X is overvalued by 15% because..." then show evidence.' },
    { day: 7, dimension: 'DC', type: 'review', action: 'Find examples of hedged language in your own writing ("might consider", "could potentially"). Replace each with direct alternatives.' },
    { day: 8, dimension: 'FR', type: 'practice', action: 'Analyze a company\'s margin trajectory. Practice stating whether margins will expand or compress and committing to a number.' },
    { day: 9, dimension: 'DC', type: 'practice', action: 'Write 3 recommendations where you disagree with consensus. Practice defending a contrarian view with specific evidence.' },
    { day: 10, dimension: 'FR', type: 'calculate', action: 'Run a scenario analysis. Practice choosing your base case and explaining why — not hedging across all scenarios equally.' },
    { day: 11, dimension: 'DC', type: 'read', action: 'Study how top analysts communicate uncertainty: they state their view clearly, then add bounds — not the other way around.' },
    { day: 12, dimension: 'FR', type: 'practice', action: 'Practice mental math speed: estimate enterprise values, multiples, and growth rates without a calculator.' },
    { day: 13, dimension: 'DC', type: 'practice', action: 'Write a recommendation memo. Delete every sentence that doesn\'t directly support your thesis. How much did you cut?' },
    { day: 14, dimension: 'FR', type: 'calculate', action: 'Build an accretion/dilution model. Practice stating: "This deal is accretive/dilutive by X% because..." in one line.' },
    { day: 15, dimension: 'DC', type: 'practice', action: 'Practice conditional recommendations: "I recommend X, contingent on conditions Y and Z, with threshold values of..."' },
    { day: 16, dimension: 'FR', type: 'read', action: 'Study how different valuation methods triangulate. Practice reconciling when DCF and comps give different answers.' },
    { day: 17, dimension: 'DC', type: 'review', action: 'Review 5 earnings call transcripts. Note how CFOs deflect vs. answer directly. Practice the direct-answer approach.' },
    { day: 18, dimension: 'FR', type: 'calculate', action: 'Build a waterfall analysis showing how value flows from enterprise to equity. State each step\'s impact clearly.' },
    { day: 19, dimension: 'DC', type: 'practice', action: 'Practice the "3-point landing": every recommendation ends with (1) your view, (2) the key risk, (3) what changes your mind.' },
    { day: 20, dimension: 'FR', type: 'practice', action: 'Analyze a company with ambiguous data. Practice making a call despite incomplete information — this is the real skill.' },
    { day: 21, dimension: 'DC', type: 'practice', action: 'Write a pass recommendation with as much conviction as a buy. Practice saying "no" clearly with supporting evidence.' },
    { day: 22, dimension: 'FR', type: 'calculate', action: 'Build a quick-and-dirty valuation in 15 minutes. Practice speed and decisiveness over precision.' },
    { day: 23, dimension: 'DC', type: 'review', action: 'Read Warren Buffett\'s annual letters. Study how he communicates complex investment theses with simple, direct language.' },
    { day: 24, dimension: 'FR', type: 'practice', action: 'Analyze two conflicting data points in a company. Practice choosing which signal is stronger and explaining why.' },
    { day: 25, dimension: 'DC', type: 'practice', action: 'Write the same recommendation for 3 audiences: your MD, a client, and a first-year analyst. Adjust clarity level for each.' },
    { day: 26, dimension: 'FR', type: 'calculate', action: 'Calculate implied probabilities from a company\'s option chain. What is the market pricing in? Do you agree?' },
    { day: 27, dimension: 'DC', type: 'practice', action: 'Practice "steel-manning" the opposite view: if you\'re bullish, write the strongest bearish case, then refute it specifically.' },
    { day: 28, dimension: 'FR', type: 'review', action: 'Review all your work this month. Score each recommendation\'s clarity from 1-5. Identify the pattern in your weakest ones.' },
    { day: 29, dimension: 'DC', type: 'practice', action: 'Write a complete investment memo in 30 minutes. Your conclusion paragraph must be writable from memory — no hedging.' },
    { day: 30, dimension: 'DC', type: 'practice', action: 'Final exercise: complete a full case analysis. State your recommendation in the first sentence. Then retake your FISS simulation.' },
  ],

  /* ─── Structured Thinking + Risk Identification ─── */
  'RI_ST': [
    { day: 1, dimension: 'ST', type: 'read', action: 'Study the MECE principle: every analysis should be mutually exclusive and collectively exhaustive. Practice decomposing a business problem.' },
    { day: 2, dimension: 'RI', type: 'practice', action: 'Read a company\'s annual report. Create a risk register with categories: financial, operational, strategic, regulatory, and market.' },
    { day: 3, dimension: 'ST', type: 'practice', action: 'Build an issue tree for "Should Company X acquire Company Y?" — ensure every branch is MECE.' },
    { day: 4, dimension: 'RI', type: 'calculate', action: 'For each risk in your Day 2 register, assign a probability (1-5) and impact score (1-5). Plot on a risk matrix.' },
    { day: 5, dimension: 'ST', type: 'review', action: 'Read a McKinsey or BCG case study. Map the consultant\'s analytical structure as a visual framework.' },
    { day: 6, dimension: 'RI', type: 'practice', action: 'Practice the "5 Whys" technique on a business failure to find root causes beyond surface-level explanations.' },
    { day: 7, dimension: 'ST', type: 'practice', action: 'Organize a complex analysis into a "pyramid": 1 main message, 3 supporting points, 2-3 evidence items per point.' },
    { day: 8, dimension: 'RI', type: 'read', action: 'Study how tail risks compound: learn about correlation risk and why diversification fails during crises.' },
    { day: 9, dimension: 'ST', type: 'calculate', action: 'Create a weighted decision matrix for a real business decision. Define criteria, assign weights, score options.' },
    { day: 10, dimension: 'RI', type: 'practice', action: 'Practice "red team" thinking: take the opposing view on an investment thesis and find its weaknesses.' },
    { day: 11, dimension: 'ST', type: 'practice', action: 'Practice segmentation: take a market and break it into meaningful sub-segments using 3 different criteria.' },
    { day: 12, dimension: 'RI', type: 'review', action: 'Study 2 deals that failed post-acquisition. What risks were predictable from pre-deal information?' },
    { day: 13, dimension: 'ST', type: 'read', action: 'Learn the difference between deductive and inductive reasoning. When should you use each in financial analysis?' },
    { day: 14, dimension: 'RI', type: 'practice', action: 'Identify "hidden dependencies" in a company: what single points of failure could cascade through the business?' },
    { day: 15, dimension: 'ST', type: 'practice', action: 'Write a case analysis using the "situation-complication-resolution" framework. Time yourself: 5 min structure, 25 min writing.' },
    { day: 16, dimension: 'RI', type: 'calculate', action: 'Build a Monte Carlo simulation (or manual scenario fan) to model the range of outcomes for an investment.' },
    { day: 17, dimension: 'ST', type: 'review', action: 'Review your Day 15 analysis. Check every paragraph: does it logically follow from the previous one?' },
    { day: 18, dimension: 'RI', type: 'practice', action: 'Map the competitive landscape risks: who could disrupt this company? What would trigger customer switching?' },
    { day: 19, dimension: 'ST', type: 'practice', action: 'Practice prioritization: given 10 issues in a business, rank them by impact and urgency. Justify your top 3.' },
    { day: 20, dimension: 'RI', type: 'read', action: 'Study regulatory risk: read about a recent regulation change and analyze how it affected company valuations.' },
    { day: 21, dimension: 'ST', type: 'calculate', action: 'Build a Porter\'s Five Forces analysis with quantitative scoring for each force. Use data, not intuition.' },
    { day: 22, dimension: 'RI', type: 'practice', action: 'Practice identifying "leading indicators" of risk: what signals appear before a risk materializes?' },
    { day: 23, dimension: 'ST', type: 'practice', action: 'Write a memo that makes a recommendation using only 3 data points. Practice extreme analytical discipline.' },
    { day: 24, dimension: 'RI', type: 'review', action: 'Review your risk assessments from this month. Which category of risk do you consistently underweight?' },
    { day: 25, dimension: 'ST', type: 'read', action: 'Study "hypothesis-driven analysis": start with a hypothesis, then test it — don\'t just gather data and hope a story emerges.' },
    { day: 26, dimension: 'RI', type: 'practice', action: 'Practice writing risk mitigation strategies that are specific and measurable, not vague ("monitor the situation").' },
    { day: 27, dimension: 'ST', type: 'practice', action: 'Take a complex business situation and create 3 different analytical frameworks. Choose the best one and explain why.' },
    { day: 28, dimension: 'RI', type: 'calculate', action: 'Quantify the top 3 risks for a company as % of enterprise value at risk. Which one is the true valuation driver?' },
    { day: 29, dimension: 'ST', type: 'review', action: 'Review all your frameworks this month. Which structural pattern produces your clearest analysis?' },
    { day: 30, dimension: 'RI', type: 'practice', action: 'Final exercise: complete a full case with structured risk analysis. Then retake your FISS simulation.' },
  ],

  /* ─── Structured Thinking + Decision Clarity ─── */
  'DC_ST': [
    { day: 1, dimension: 'ST', type: 'read', action: 'Study the pyramid principle by Barbara Minto. Every structured analysis should lead to a clear, singular recommendation.' },
    { day: 2, dimension: 'DC', type: 'practice', action: 'Write 5 one-sentence conclusions for 5 different business problems. No hedging, no qualifiers.' },
    { day: 3, dimension: 'ST', type: 'practice', action: 'Practice "top-down" communication: write your conclusion first, then organize supporting evidence below it.' },
    { day: 4, dimension: 'DC', type: 'review', action: 'Read 3 analyst reports. Rate each recommendation\'s clarity 1-5. What makes the best ones compelling?' },
    { day: 5, dimension: 'ST', type: 'calculate', action: 'Build a decision tree for a strategic choice. Each branch should lead to a clear action, not "it depends."' },
    { day: 6, dimension: 'DC', type: 'practice', action: 'Practice the "because" rule: every recommendation must include "I recommend X BECAUSE Y, with threshold Z."' },
    { day: 7, dimension: 'ST', type: 'practice', action: 'Organize a messy data set into a coherent story. Practice the "so what?" test at every level of your analysis.' },
    { day: 8, dimension: 'DC', type: 'read', action: 'Study how conviction is communicated in finance: word choice, sentence structure, and the role of specificity.' },
    { day: 9, dimension: 'ST', type: 'review', action: 'Take your Day 7 analysis and cut 30% of the words. Does the structure still hold? It should be stronger.' },
    { day: 10, dimension: 'DC', type: 'practice', action: 'Write a contrarian recommendation. Practice saying "the market is wrong because..." with specific evidence.' },
    { day: 11, dimension: 'ST', type: 'practice', action: 'Create a "logic chain": connect 5 data points into a sequential argument where each builds on the previous.' },
    { day: 12, dimension: 'DC', type: 'practice', action: 'Practice conditional clarity: "I recommend X. This changes if A exceeds 20% or B falls below $50M."' },
    { day: 13, dimension: 'ST', type: 'calculate', action: 'Build a pros/cons analysis that goes beyond listing: weight each factor by importance and likelihood.' },
    { day: 14, dimension: 'DC', type: 'review', action: 'Review your own writing from this month. Circle every use of "might", "could", "perhaps". Replace each with a commitment.' },
    { day: 15, dimension: 'ST', type: 'practice', action: 'Practice "grouping": take 15 disparate facts and organize them into 3-4 meaningful groups with labels.' },
    { day: 16, dimension: 'DC', type: 'practice', action: 'Write the same recommendation at 3 conviction levels: low, medium, high. Notice how your language changes.' },
    { day: 17, dimension: 'ST', type: 'read', action: 'Study how consulting firms structure client deliverables. Focus on how every slide/page serves the overall narrative.' },
    { day: 18, dimension: 'DC', type: 'practice', action: 'Practice "landing the plane": write 5 conclusion paragraphs that leave zero ambiguity about what you recommend.' },
    { day: 19, dimension: 'ST', type: 'practice', action: 'Build a "storyboard" for a case analysis: plan the sequence of arguments before writing a single word.' },
    { day: 20, dimension: 'DC', type: 'review', action: 'Read investment committee memos. Study how portfolio managers make clear allocation decisions with imperfect info.' },
    { day: 21, dimension: 'ST', type: 'calculate', action: 'Create a prioritization matrix with 2 axes. Place 10 business issues on it and explain your placement.' },
    { day: 22, dimension: 'DC', type: 'practice', action: 'Practice speed-to-decision: given a new company, form an investment view in 10 minutes and defend it.' },
    { day: 23, dimension: 'ST', type: 'practice', action: 'Write a 1-page memo using only bullet points. Each bullet must logically flow from the previous one.' },
    { day: 24, dimension: 'DC', type: 'practice', action: 'Practice "the 80/20 of conviction": identify the 20% of information that drives 80% of your recommendation.' },
    { day: 25, dimension: 'ST', type: 'review', action: 'Review your storyboard from Day 19. Did your actual analysis follow the plan? Where did you deviate and why?' },
    { day: 26, dimension: 'DC', type: 'read', action: 'Study how Jeff Bezos\'s shareholder letters communicate strategic decisions: clear, specific, and forward-looking.' },
    { day: 27, dimension: 'ST', type: 'practice', action: 'Take a complex case and create a "1-slide summary": the entire analysis on one page. Force ruthless prioritization.' },
    { day: 28, dimension: 'DC', type: 'practice', action: 'Practice the "3-second test": can someone understand your recommendation in 3 seconds? If not, rewrite it.' },
    { day: 29, dimension: 'ST', type: 'review', action: 'Review all your frameworks this month. Which structural approach produced your clearest, most decisive output?' },
    { day: 30, dimension: 'DC', type: 'practice', action: 'Final exercise: complete a full case analysis. First sentence = your recommendation. Then retake your FISS simulation.' },
  ],

  /* ─── Risk Identification + Decision Clarity ─── */
  'DC_RI': [
    { day: 1, dimension: 'RI', type: 'read', action: 'Study how risk identification differs from risk management. The first step is always: see the risk clearly before solving it.' },
    { day: 2, dimension: 'DC', type: 'practice', action: 'Write a recommendation that explicitly addresses its biggest risk: "I recommend X despite risk Y because Z mitigates it."' },
    { day: 3, dimension: 'RI', type: 'practice', action: 'Read a company\'s financials and list 10 risks in 10 minutes. Speed is important — you\'re training pattern recognition.' },
    { day: 4, dimension: 'DC', type: 'review', action: 'Review 3 investment recommendations. Did the analyst address risks directly in their conclusion, or bury them?' },
    { day: 5, dimension: 'RI', type: 'calculate', action: 'For your Day 3 risks, calculate the expected financial impact: probability × magnitude for each.' },
    { day: 6, dimension: 'DC', type: 'practice', action: 'Practice making decisions under uncertainty: "Given risks A, B, C, my recommendation is still X because..."' },
    { day: 7, dimension: 'RI', type: 'practice', action: 'Practice identifying "second-order effects": if Risk A materializes, what other risks does it trigger?' },
    { day: 8, dimension: 'DC', type: 'practice', action: 'Write pass recommendations for 3 different companies. Practice being decisive about what NOT to invest in.' },
    { day: 9, dimension: 'RI', type: 'read', action: 'Study counterparty risk and concentration risk. How do these affect your confidence in a recommendation?' },
    { day: 10, dimension: 'DC', type: 'review', action: 'Review your Day 8 pass recommendations. Were you specific about WHY you\'re passing? Vague passes aren\'t decisions.' },
    { day: 11, dimension: 'RI', type: 'practice', action: 'Map a company\'s supply chain end-to-end. Identify the 3 weakest links and their potential impact.' },
    { day: 12, dimension: 'DC', type: 'practice', action: 'Practice "bounded recommendations": "I\'m 70% confident this works. Here\'s what I\'d need to reach 90%."' },
    { day: 13, dimension: 'RI', type: 'calculate', action: 'Build a stress test: what revenue decline would push a company from investment-grade to high-yield credit?' },
    { day: 14, dimension: 'DC', type: 'practice', action: 'Practice "risk-adjusted recommendations": adjust your view based on the severity of identified risks.' },
    { day: 15, dimension: 'RI', type: 'practice', action: 'Practice the "pre-mortem": it\'s 2 years later and the investment failed. Write the post-mortem. What went wrong?' },
    { day: 16, dimension: 'DC', type: 'read', action: 'Study how hedge fund managers communicate risk-adjusted views: position sizing, stop-losses, and risk/reward ratios.' },
    { day: 17, dimension: 'RI', type: 'review', action: 'Read 3 short-seller reports. How do they identify risks that the market is ignoring? What\'s their evidence standard?' },
    { day: 18, dimension: 'DC', type: 'practice', action: 'Write a recommendation that includes a specific "kill switch": "We exit if metric X crosses threshold Y."' },
    { day: 19, dimension: 'RI', type: 'practice', action: 'Practice differentiating "priced-in" risks from "unpriced" risks. Only unpriced risks should change your view.' },
    { day: 20, dimension: 'DC', type: 'practice', action: 'Practice the "one thing" exercise: if you could only communicate one insight from your analysis, what is it?' },
    { day: 21, dimension: 'RI', type: 'calculate', action: 'Model a "black swan" scenario for a company. What would it take to destroy 50%+ of equity value?' },
    { day: 22, dimension: 'DC', type: 'review', action: 'Review all your recommendations this month. Rate each on a 1-5 clarity scale. What pattern do you see?' },
    { day: 23, dimension: 'RI', type: 'practice', action: 'Practice "risk layering": categorize risks by time horizon (1mo, 6mo, 1yr, 3yr). Which layer is most dangerous?' },
    { day: 24, dimension: 'DC', type: 'practice', action: 'Practice conveying conviction through specificity: replace "growing quickly" with "growing at 23% YoY, accelerating from 18%."' },
    { day: 25, dimension: 'RI', type: 'read', action: 'Study how regulatory change creates asymmetric risk: small probability but massive impact. Find 2 current examples.' },
    { day: 26, dimension: 'DC', type: 'practice', action: 'Write a recommendation email to your MD in 5 sentences. Every sentence must either state your view or defend it.' },
    { day: 27, dimension: 'RI', type: 'practice', action: 'For a company you analyzed this month, list the risks you initially missed. What cognitive bias caused each blind spot?' },
    { day: 28, dimension: 'DC', type: 'review', action: 'Review your Day 26 email. Would your MD know exactly what to do after reading it? If not, rewrite it.' },
    { day: 29, dimension: 'RI', type: 'calculate', action: 'Build a final risk-reward analysis: expected upside vs. probability-weighted downside. Is the ratio attractive?' },
    { day: 30, dimension: 'DC', type: 'practice', action: 'Final exercise: complete a full case with clear risk identification and a decisive recommendation. Then retake your FISS simulation.' },
  ],
};
